project:
  type: book
  output-dir: _book

book:
  title: "Learning Statistics with R"
  author: "Danielle Navarro"
  site-url: https://learningstatisticswithr.com/
  repo-url: https://github.com/djnavarro/rbook/

  page-footer:
    left: |
      Learning Statistics with R was written by <a href="https://djnavarro.net">Danielle Navarro</a>.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  chapters:
    - index.qmd
    - chapters/preface.qmd
    - chapters/introduction.qmd
    
    - part: Getting started
      chapters:
        - chapters/installation.qmd
        - chapters/commands.qmd
        - chapters/calculations.qmd
        - chapters/variables.qmd
        - chapters/file-system.qmd
        - chapters/packages.qmd
        
    - part: Working with data 
      chapters:
        - chapters/data-objects.qmd
        - chapters/reading-data.qmd
        #- chapters/descriptive-statistics.qmd
        #- chapters/data-visualisation.qmd
        #- chapters/data-wrangling.qmd
        #- chapters/basic-programming.qmd
        
    # - part: Statistical theory
    #   chapters:
    #     - chapters/prelude-to-inference.qmd
    #     - chapters/probability.qmd
    #     - chapters/estimation.qmd
    #     - chapters/hypothesis-testing.qmd
    
    # - part: Statistical tools
    #   chapters:
    #       - chapters/categorical-data-analysis.qmd
    #       - chapters/comparing-two-group-means.qmd
    #       - chapters/one-way-anova.qmd
    #       - chapters/linear-regression.qmd
    #       - chapters/factorial-anova.qmd
        
    - chapters/references.qmd

bibliography: build/references.bib

format:
  html:
    theme: cosmo
    author-meta: "Danielle Navarro"
    include-in-header: "build/header.html"
  #pdf:
  #  documentclass: scrreprt
  
editor: source

