### How to read the help documentation

I have somewhat mixed feelings about the help documentation in R. On the plus side, there's a lot of it, and it's very thorough. On the minus side, there's a lot of it, and it's very thorough. There's so much help documentation that it sometimes doesn't help, and most of it is written with an advanced user in mind. Often it feels like most of the help files work on the assumption that the reader already understands everything about R except for the specific topic that it's providing help for. What that means is that, once you've been using R for a long time and are beginning to get a feel for how to use it, the help documentation is *awesome*. These days, I find myself really liking the help files (most of them anyway). But when I first started using R I found it very dense.

To some extent, there's not much I can do to help you with this. You just have to work at it yourself; once you're moving away from being a pure beginner and are becoming a skilled user, you'll start finding the help documentation more and more helpful. In the meantime, I'll help as much as I can by trying to explain to you what you're looking at when you open a help file. To that end, let's look at the help documentation for the `load()` function. To do so, I type either of the following:
  ```
> ?load
> help("load")
```
When I do that, R goes looking for the help file for the `"load"` topic. If it finds one, Rstudio takes it and displays it in the help panel. Alternatively, you can try a fuzzy search for a help topic:  
  ```
> ??load
> help.search("load")
```
This will bring up a list of possible topics that you might want to follow up in. 

Regardless, at some point you'll find yourself looking at an actual help file. And when you do, you'll see there's a quite a lot of stuff written down there, and it comes in a pretty standardised format. So let's go through it slowly, using the `"load"` topic as our example. Firstly, at the very top we see this:
  ```
load (base)	                                              R Documentation
```
The `R Documentation` part isn't terribly interesting, but the `load (base)`	 part is telling you that this is in reference to the `load()` function (obviously) and that this function is in the `base` package. Next, we get the "title" information, and a short "description" of what the function does:
```

**Reload Saved Datasets**

**Description**

Reload datasets written with the function @helpcode{save}.
```

Fairly straightforward. The next section describes how the function is used:

```

**Usage**

@helpcode{load(file, envir = parent.frame())}

```
In this instance, the usage section is actually pretty readable. It's telling you that there are two arguments to the `load()` function: the first one is called `file`, and the second one is called `envir`. It's also telling you that there is a default value for the `envir` argument; so if the user doesn't specify what the value of `envir` should be, then R will assume that `envir = parent.frame()`. In contrast, the `file` argument has no default value at all, so the user *must* specify a value for it. So in one sense, this section is very straightforward. 

The problem, of course, is that you don't know what the `parent.frame()` function actually does, so it's hard for you to know what the `envir = parent.frame()` bit is all about. What you *could* do is then go look up the help documents for the `parent.frame()` function (and sometimes that's actually a good idea), but often you'll find that the help documents for those functions are just as dense (if not more dense) than the help file that you're currently reading. As an alternative, my general approach when faced with something like this is to skim over it, see if I can make any sense of it. If so, great. If not, I find that the best thing to do is ignore it. In fact, the first time I read the help file for the `load()` function, I had no idea what any of the `envir` related stuff was about. But fortunately I didn't have to: the default setting here (i.e.,   `envir = parent.frame()`) is actually the thing you want in about 99% of cases, so it's safe to ignore it. 
                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                               Basically, what I'm trying to say is: don't let the scary, incomprehensible parts of the help file intimidate you. Especially because there's often some parts of the help file that will make sense. Of course, I guarantee you that sometimes this strategy will lead you to make mistakes... often embarrassing mistakes. But it's still better than getting paralysed with fear.  
                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                               So, let's continue on. The next part of the help documentation discusses each of the arguments, and what they're supposed to do:
                                                                                                                                                                                                                                                                               ```
                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                               **Arguments**
                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                               @helpcode{file}	a (readable binary-mode) connection or a character string giving the name
                                                                                                                                                                                                                                                                               of the file to load (when tilde expansion is done).
                                                                                                                                                                                                                                                                               @helpcode{envir}	the environment where the data should be loaded.
                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                               ```
                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                               Okay, so what this is telling us is that the `file` argument needs to be a string (i.e., text data) which tells R the name of the file to load. It also seems to be hinting that there's other possibilities too (e.g., a "binary mode connection"), and you probably aren't quite sure what "tilde expansion" means^[It's extremely simple, by the way. We discussed it in Section \@ref(navigation), though I didn't call it by that name. Tilde expansion is the thing where R recognises that, in the context of specifying a file location, the tilde symbol~{\tt \~{]} corresponds to the user home directory (e.g., /Users/dan/).}. But overall, the meaning is pretty clear. 
                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                               Turning to the `envir` argument, it's now a little clearer what the Usage section was babbling about. The `envir` argument specifies the name of an environment (see Section \@ref(workspace) if you've forgotten what environments are) into which R should place the variables when it loads the file. Almost always, this is a no-brainer: you want R to load the data into the same damn environment in which you're invoking the `load()` command. That is, if you're typing `load()` at the R prompt, then you want the data to be loaded into your workspace (i.e., the global environment). But if you're writing your own function that needs to load some data, you want the data to be loaded inside that function's private workspace. And in fact, that's exactly what the `parent.frame()` thing is all about. It's telling the `load()` function to send the data to the same place that the `load()` command itself was coming from. As it turns out, if we'd just ignored the `envir` bit we would have been totally safe.  Which is nice to know. 
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                Moving on, next up we get a detailed description of what the function actually does: 
                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                  ```
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                **Details**
                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                  @helpcode{load} can load R objects saved in the current or any earlier format. It can read a
                                                                                                                                                                                                                                                                                                                                                                                                                                                compressed file (see @helpcode{save}) directly from a file or from a suitable connection (including
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          a call to @helpcode{url}).
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                A not-open connection will be opened in mode @helpcode{"rb"} and closed after use. Any connection
                                                                                                                                                                                                                                                                                                                                                                                                                                                other than a @helpcode{gzfile} or @helpcode{gzcon} connection will be wrapped in @helpcode{gzcon} to allow compressed 
                                                                                                                                                                                                                                                                                                                                                                                                                                                saves to be handled: note that this leaves the connection in an altered state (in 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               particular, binary-only).
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                Only R objects saved in the current format (used since R 1.4.0) can be read from a 
                                                                                                                                                                                                                                                                                                                                                                                                                                                connection. If no input is available on a connection a warning will be given, but any input 
                                                                                                                                                                                                                                                                                                                                                                                                                                                not in the current format will result in a error.
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                Loading from an earlier version will give a warning about the "magic number": magic 
                                                                                                                                                                                                                                                                                                                                                                                                                                                numbers @helpcode{1971:1977} are from R @texttt{<} 0.99.0, and @helpcode{RD[ABX]1} from R 0.99.0 to R 1.3.1. These 
                                                                                                                                                                                                                                                                                                                                                                                                                                                are all obsolete, and you are strongly recommended to re-save such files in a current 
                                                                                                                                                                                                                                                                                                                                                                                                                                                format.
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                ```
                                                                                                                                                                                                                                                                                                                                                                                                                                                Then it tells you what the output value of the function is:
                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                  ```
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                **Value**
                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                  A character vector of the names of objects created, invisibly.
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                ```
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                This is usually a bit more interesting, but since the `load()` function is mainly used to load variables into the workspace rather than to return a value, it's no surprise that this doesn't do much or say much. Moving on, we sometimes see a few additional sections in the help file, which can be different depending on what the function is:
                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                  ```
                                                                                                                                                                                                                                                                                                                                                                                                                                                **Warning**
                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                  Saved R objects are binary files, even those saved with @helpcode{ascii = TRUE}, so ensure that 
                                                                                                                                                                                                                                                                                                                                                                                                                                                they are transferred without conversion of end of line markers. @helpcode{load} tries to detect such 
                                                                                                                                                                                                                                                                                                                                                                                                                                                a conversion and gives an informative error message.
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                ```
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                Yeah, yeah. Warning, warning, blah blah blah. Towards the bottom of the help file, we see something like this, which suggests a bunch of related topics that you might want to look at. These can be quite helpful:
                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                  ```
                                                                                                                                                                                                                                                                                                                                                                                                                                                **See Also**
                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                  @helpcode{save}, @helpcode{download.file}.
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                For other interfaces to the underlying serialization format, see @helpcode{unserialize} and @helpcode{readRDS}.
                                                                                                                                                                                                                                                                                                                                                                                                                                                ```
                                                                                                                                                                                                                                                                                                                                                                                                                                                ```{r}
                                                                                                                                                                                                                                                                                                                                                                                                                                                help("load")
                                                                                                                                                                                                                                                                                                                                                                                                                                                ```
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                Finally, it gives you some examples of how to use the function(s) that the help file describes. These are supposed to be proper R commands, meaning that you should be able to type them into the console yourself and they'll actually work. Sometimes it can be quite helpful to try the examples yourself. Anyway, here they are for the `"load"` help file:
                                                                                                                                                                                                                                                                                                                                                                                                                                                \begin{rhelp1} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                **Examples** 
                                                                                                                                                                                                                                                                                                                                                                                                                                                \end{rhelp1}
                                                                                                                                                                                                                                                                                                                                                                                                                                                \vspace*{-24pt}
                                                                                                                                                                                                                                                                                                                                                                                                                                                ```
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                ## save all data
                                                                                                                                                                                                                                                                                                                                                                                                                                                xx <- pi # to ensure there is some data
                                                                                                                                                                                                                                                                                                                                                                                                                                                save(list = ls(all=TRUE), file= "all.RData")
                                                                                                                                                                                                                                                                                                                                                                                                                                                rm(xx)
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                ## restore the saved values to the current environment
                                                                                                                                                                                                                                                                                                                                                                                                                                                local({
                                                                                                                                                                                                                                                                                                                                                                                                                                                load("all.RData")
                                                                                                                                                                                                                                                                                                                                                                                                                                                ls()
                                                                                                                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                                                                                                                                                ## restore the saved values to the user's workspace
                                                                                                                                                                                                                                                                                                                                                                                                                                                load("all.RData", .GlobalEnv)
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                unlink("all.RData")
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                ## Not run: 
                                                                                                                                                                                                                                                                                                                                                                                                                                                con <- url("http://some.where.net/R/data/example.rda")
                                                                                                                                                                                                                                                                                                                                                                                                                                                ## print the value to see what objects were created.
                                                                                                                                                                                                                                                                                                                                                                                                                                                print(load(con))
                                                                                                                                                                                                                                                                                                                                                                                                                                                close(con) # url() always opens the connection
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                ## End(Not run)
                                                                                                                                                                                                                                                                                                                                                                                                                                                ```
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                As you can see, they're pretty dense, and not at all obvious to the novice user. However, they do provide good examples of the various different things that you can do with the `load()` function, so it's not a bad idea to have a look at them, and to try not to find them too intimidating. 