<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.52">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10&nbsp; Estimating unknown quantities from a sample – Learning Statistics with R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./11-hypothesistesting.html" rel="next">
<link href="./09-probability.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="10&nbsp; Estimating unknown quantities from a sample – Learning Statistics with R">
<meta property="og:description" content="">
<meta property="og:image" content="https://learningstatisticswithr.com/cover/cover-social.jpg">
<meta property="og:site_name" content="Learning Statistics with R">
<meta name="twitter:title" content="10&nbsp; Estimating unknown quantities from a sample – Learning Statistics with R">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://learningstatisticswithr.com/cover/cover-social.jpg">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./theory-preamble.html">Statistical theory</a></li><li class="breadcrumb-item"><a href="./10-estimation.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Estimating unknown quantities from a sample</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Learning Statistics with R</a> 
        <div class="sidebar-tools-main">
    <a href="./Learning-Statistics-with-R.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Background</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./background-preamble.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">A word on statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-whystats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why do we learn statistics?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-studydesign.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">A brief introduction to research design</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">An introduction to R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-introR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Getting started with R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-mechanics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">R mechanics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Working with data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-descriptives.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Descriptive statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-graphics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Drawing graphs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-datahandling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Pragmatic matters</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-scripting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Basic programming</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical theory</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./theory-preamble.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">A chat about inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Introduction to probability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-estimation.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Estimating unknown quantities from a sample</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-hypothesistesting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical tools</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-chisquare.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Categorical data analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-ttest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">The <span class="math inline">\(t\)</span>-test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Comparing several means (one-way ANOVA)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Linear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-anova2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Endings, alternatives and prospects</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Bayesian statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./epilogue.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Epilogue</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./changelog.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Changelog</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-srs" id="toc-sec-srs" class="nav-link active" data-scroll-target="#sec-srs"><span class="header-section-number">10.1</span> Samples, populations and sampling</a>
  <ul class="collapse">
  <li><a href="#sec-pop" id="toc-sec-pop" class="nav-link" data-scroll-target="#sec-pop"><span class="header-section-number">10.1.1</span> Defining a population</a></li>
  <li><a href="#simple-random-samples" id="toc-simple-random-samples" class="nav-link" data-scroll-target="#simple-random-samples"><span class="header-section-number">10.1.2</span> Simple random samples</a></li>
  <li><a href="#most-samples-are-not-simple-random-samples" id="toc-most-samples-are-not-simple-random-samples" class="nav-link" data-scroll-target="#most-samples-are-not-simple-random-samples"><span class="header-section-number">10.1.3</span> Most samples are not simple random samples</a></li>
  <li><a href="#how-much-does-it-matter-if-you-dont-have-a-simple-random-sample" id="toc-how-much-does-it-matter-if-you-dont-have-a-simple-random-sample" class="nav-link" data-scroll-target="#how-much-does-it-matter-if-you-dont-have-a-simple-random-sample"><span class="header-section-number">10.1.4</span> How much does it matter if you don’t have a simple random sample?</a></li>
  <li><a href="#population-parameters-and-sample-statistics" id="toc-population-parameters-and-sample-statistics" class="nav-link" data-scroll-target="#population-parameters-and-sample-statistics"><span class="header-section-number">10.1.5</span> Population parameters and sample statistics</a></li>
  </ul></li>
  <li><a href="#sec-lawlargenumbers" id="toc-sec-lawlargenumbers" class="nav-link" data-scroll-target="#sec-lawlargenumbers"><span class="header-section-number">10.2</span> The law of large numbers</a></li>
  <li><a href="#sec-samplesandclt" id="toc-sec-samplesandclt" class="nav-link" data-scroll-target="#sec-samplesandclt"><span class="header-section-number">10.3</span> Sampling distributions and the central limit theorem</a>
  <ul class="collapse">
  <li><a href="#sec-samplingdists" id="toc-sec-samplingdists" class="nav-link" data-scroll-target="#sec-samplingdists"><span class="header-section-number">10.3.1</span> Sampling distribution of the mean</a></li>
  <li><a href="#sampling-distributions-exist-for-any-sample-statistic" id="toc-sampling-distributions-exist-for-any-sample-statistic" class="nav-link" data-scroll-target="#sampling-distributions-exist-for-any-sample-statistic"><span class="header-section-number">10.3.2</span> Sampling distributions exist for any sample statistic!</a></li>
  <li><a href="#sec-clt" id="toc-sec-clt" class="nav-link" data-scroll-target="#sec-clt"><span class="header-section-number">10.3.3</span> The central limit theorem</a></li>
  </ul></li>
  <li><a href="#sec-pointestimates" id="toc-sec-pointestimates" class="nav-link" data-scroll-target="#sec-pointestimates"><span class="header-section-number">10.4</span> Estimating population parameters</a>
  <ul class="collapse">
  <li><a href="#estimating-the-population-mean" id="toc-estimating-the-population-mean" class="nav-link" data-scroll-target="#estimating-the-population-mean"><span class="header-section-number">10.4.1</span> Estimating the population mean</a></li>
  <li><a href="#estimating-the-population-standard-deviation" id="toc-estimating-the-population-standard-deviation" class="nav-link" data-scroll-target="#estimating-the-population-standard-deviation"><span class="header-section-number">10.4.2</span> Estimating the population standard deviation</a></li>
  </ul></li>
  <li><a href="#sec-ci" id="toc-sec-ci" class="nav-link" data-scroll-target="#sec-ci"><span class="header-section-number">10.5</span> Estimating a confidence interval</a>
  <ul class="collapse">
  <li><a href="#a-slight-mistake-in-the-formula" id="toc-a-slight-mistake-in-the-formula" class="nav-link" data-scroll-target="#a-slight-mistake-in-the-formula"><span class="header-section-number">10.5.1</span> A slight mistake in the formula</a></li>
  <li><a href="#interpreting-a-confidence-interval" id="toc-interpreting-a-confidence-interval" class="nav-link" data-scroll-target="#interpreting-a-confidence-interval"><span class="header-section-number">10.5.2</span> Interpreting a confidence interval</a></li>
  <li><a href="#calculating-confidence-intervals-in-r" id="toc-calculating-confidence-intervals-in-r" class="nav-link" data-scroll-target="#calculating-confidence-intervals-in-r"><span class="header-section-number">10.5.3</span> Calculating confidence intervals in R</a></li>
  <li><a href="#sec-ciplots" id="toc-sec-ciplots" class="nav-link" data-scroll-target="#sec-ciplots"><span class="header-section-number">10.5.4</span> Plotting confidence intervals in R</a></li>
  </ul></li>
  <li><a href="#sec-estimationvstesting" id="toc-sec-estimationvstesting" class="nav-link" data-scroll-target="#sec-estimationvstesting"><span class="header-section-number">10.6</span> Epilogue: estimation over testing?</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">10.7</span> Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./theory-preamble.html">Statistical theory</a></li><li class="breadcrumb-item"><a href="./10-estimation.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Estimating unknown quantities from a sample</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-estimation" class="quarto-section-identifier"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Estimating unknown quantities from a sample</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>At the start of the last chapter I highlighted the critical distinction between <em>descriptive statistics</em> and <em>inferential statistics</em>. As discussed in <a href="05-descriptives.html" class="quarto-xref"><span>Chapter 5</span></a>, the role of descriptive statistics is to concisely summarise what we <em>do</em> know. In contrast, the purpose of inferential statistics is to “learn what we do not know from what we do”. Now that we have a foundation in probability theory, we are in a good position to think about the problem of statistical inference. What kinds of things would we like to learn about? And how do we learn them? These are the questions that lie at the heart of inferential statistics, and they are traditionally divided into two “big ideas”: estimation and hypothesis testing. The goal in this chapter is to introduce the first of these big ideas, estimation theory, but I’m going to witter on about sampling theory first because estimation theory doesn’t make sense until you understand sampling. As a consequence, this chapter divides naturally into two parts: <a href="#sec-srs" class="quarto-xref"><span>Section 10.1</span></a> through <a href="#sec-samplesandclt" class="quarto-xref"><span>Section 10.3</span></a> are focused on sampling theory, and <a href="#sec-pointestimates" class="quarto-xref"><span>Section 10.4</span></a> and <a href="#sec-ci" class="quarto-xref"><span>Section 10.5</span></a> make use of sampling theory to discuss how statisticians think about estimation.</p>
<section id="sec-srs" class="level2 page-columns page-full" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="sec-srs"><span class="header-section-number">10.1</span> Samples, populations and sampling</h2>
<p>In the <a href="./theory-preamble.html">prelude to Part IV</a> I discussed the riddle of induction, and highlighted the fact that <em>all</em> learning requires you to make assumptions. Accepting that this is true, our first task is to come up with some fairly general assumptions about data that make sense. This is where <strong><em>sampling theory</em></strong> comes in. If probability theory is the foundations upon which all statistical theory builds, sampling theory is the frame around which you can build the rest of the house. Sampling theory plays a huge role in specifying the assumptions upon which your statistical inferences rely. And in order to talk about “making inferences” the way statisticians think about it, we need to be a bit more explicit about what it is that we’re drawing inferences <em>from</em> (the sample) and what it is that we’re drawing inferences <em>about</em> (the population).</p>
<p>In almost every situation of interest, what we have available to us as researchers is a <strong><em>sample</em></strong> of data. We might have run an experiment with some number of participants; a polling company might have phoned some number of people to ask questions about voting intentions; etc. Regardless: the data set available to us is finite, and incomplete. We can’t possibly get every person in the world to do our experiment; a polling company doesn’t have the time or the money to ring up every voter in the country etc. In our earlier discussion of descriptive statistics (<a href="05-descriptives.html" class="quarto-xref"><span>Chapter 5</span></a>), this sample was the only thing we were interested in. Our only goal was to find ways of describing, summarising and graphing that sample. This is about to change.</p>
<section id="sec-pop" class="level3" data-number="10.1.1">
<h3 data-number="10.1.1" class="anchored" data-anchor-id="sec-pop"><span class="header-section-number">10.1.1</span> Defining a population</h3>
<p>A sample is a concrete thing. You can open up a data file, and there’s the data from your sample. A <strong><em>population</em></strong>, on the other hand, is a more abstract idea. It refers to the set of all possible people, or all possible observations, that you want to draw conclusions about, and is generally <em>much</em> bigger than the sample. In an ideal world, the researcher would begin the study with a clear idea of what the population of interest is, since the process of designing a study and testing hypotheses about the data that it produces does depend on the population about which you want to make statements. However, that doesn’t always happen in practice: usually the researcher has a fairly vague idea of what the population is and designs the study as best he/she can on that basis.</p>
<p>Sometimes it’s easy to state the population of interest. For instance, in the “polling company” example that opened the chapter, the population consisted of all voters enrolled at the time of the study – millions of people. The sample was a set of 1000 people who all belong to that population. In most situations the situation is much less simple. In a typical psychological experiment, determining the population of interest is a bit more complicated. Suppose I run an experiment using 100 undergraduate students as my participants. My goal, as a cognitive scientist, is to try to learn something about how the mind works. So, which of the following would count as “the population”:</p>
<ul>
<li>All of the undergraduate psychology students at the University of Adelaide?</li>
<li>Undergraduate psychology students in general, anywhere in the world?</li>
<li>Australians currently living?</li>
<li>Australians of similar ages to my sample?</li>
<li>Anyone currently alive?</li>
<li>Any human being, past, present or future?</li>
<li>Any biological organism with a sufficient degree of intelligence operating in a terrestrial environment?</li>
<li>Any intelligent being?</li>
</ul>
<p>Each of these defines a real group of mind-possessing entities, all of which might be of interest to me as a cognitive scientist, and it’s not at all clear which one ought to be the true population of interest. As another example, consider the Wellesley-Croker game that we discussed in the prelude. The sample here is a specific sequence of 12 wins and 0 losses for Wellesley. What is the population?</p>
<ul>
<li>All outcomes until Wellesley and Croker arrived at their destination?</li>
<li>All outcomes if Wellesley and Croker had played the game for the rest of their lives?</li>
<li>All outcomes if Wellesley and Croker lived forever and played the game until the world ran out of hills?</li>
<li>All outcomes if we created an infinite set of parallel universes and the Wellesley/Croker pair made guesses about the same 12 hills in each universe?</li>
</ul>
<p>Again, it’s not obvious what the population is.</p>
</section>
<section id="simple-random-samples" class="level3 page-columns page-full" data-number="10.1.2">
<h3 data-number="10.1.2" class="anchored" data-anchor-id="simple-random-samples"><span class="header-section-number">10.1.2</span> Simple random samples</h3>
<div class="cell" data-scratch="start">
<div class="cell-output-display">
<div id="fig-srs1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-srs1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-srs1-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-srs1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.1: Simple random sampling without replacement from a finite population.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Irrespective of how I define the population, the critical point is that the sample is a subset of the population, and our goal is to use our knowledge of the sample to draw inferences about the properties of the population. The relationship between the two depends on the <em>procedure</em> by which the sample was selected. This procedure is referred to as a <strong><em>sampling method</em></strong>, and it is important to understand why it matters.</p>
<p>To keep things simple, let’s imagine that we have a bag containing 10 chips. Each chip has a unique letter printed on it, so we can distinguish between the 10 chips. The chips come in two colours, black and white. This set of chips is the population of interest, and it is depicted graphically on the left of <a href="#fig-srs1" class="quarto-xref">Figure&nbsp;<span>10.1</span></a>. As you can see from looking at the picture, there are 4 black chips and 6 white chips, but of course in real life we wouldn’t know that unless we looked in the bag. Now imagine you run the following “experiment”: you shake up the bag, close your eyes, and pull out 4 chips without putting any of them back into the bag. First out comes the <span class="math inline">\(a\)</span> chip (black), then the <span class="math inline">\(c\)</span> chip (white), then <span class="math inline">\(j\)</span> (white) and then finally <span class="math inline">\(b\)</span> (black). If you wanted, you could then put all the chips back in the bag and repeat the experiment, as depicted on the right hand side of <a href="#fig-srs1" class="quarto-xref">Figure&nbsp;<span>10.1</span></a>. Each time you get different results, but the procedure is identical in each case. We refer to the fact that the same procedure can lead to different results each time as a <em>random</em> process.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> However, because we shook the bag before pulling any chips out, it seems reasonable to think that every chip has the same chance of being selected. A procedure in which every member of the population has the same chance of being selected is called a <strong><em>simple random sample</em></strong>. The fact that we did <em>not</em> put the chips back in the bag after pulling them out means that you can’t observe the same thing twice, and in such cases the observations are said to have been sampled <strong><em>without replacement</em></strong>.</p>
<div class="no-row-height column-margin column-container"><div id="fn1"><p><sup>1</sup>&nbsp;The proper mathematical definition of randomness is extraordinarily technical, and way beyond the scope of this book. We’ll be non-technical here and say that a process has an element of randomness to it whenever it is possible to repeat the process and get different answers each time.</p></div></div><p>To help make sure you understand the importance of the sampling procedure, consider an alternative way in which the experiment could have been run. Suppose that my 5-year old son had opened the bag, and decided to pull out four black chips without putting any of them back in the bag. This <em>biased</em> sampling scheme is depicted in <a href="#fig-brs" class="quarto-xref">Figure&nbsp;<span>10.2</span></a>. Now consider the evidentiary value of seeing 4 black chips and 0 white chips. Clearly, it depends on the sampling scheme, does it not? If you know that the sampling scheme is biased to select only black chips, then a sample that consists of only black chips doesn’t tell you very much about the population! For this reason, statisticians really like it when a data set can be considered a simple random sample, because it makes the data analysis <em>much</em> easier.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-brs" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-brs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-brs-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.2: Biased sampling without replacement from a finite population.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-scratch="end">
<div class="cell-output-display">
<div id="fig-srs2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-srs2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-srs2-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-srs2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.3: Simple random sampling <em>with</em> replacement from a finite population.
</figcaption>
</figure>
</div>
</div>
</div>
<p>A third procedure is worth mentioning. This time around we close our eyes, shake the bag, and pull out a chip. This time, however, we record the observation and then put the chip back in the bag. Again we close our eyes, shake the bag, and pull out a chip. We then repeat this procedure until we have 4 chips. Data sets generated in this way are still simple random samples, but because we put the chips back in the bag immediately after drawing them it is referred to as a sample <strong><em>with replacement</em></strong>. The difference between this situation and the first one is that it is possible to observe the same population member multiple times, as illustrated in <a href="#fig-srs2" class="quarto-xref">Figure&nbsp;<span>10.3</span></a>.</p>
<p>In my experience, most psychology experiments tend to be sampling without replacement, because the same person is not allowed to participate in the experiment twice. However, most statistical theory is based on the assumption that the data arise from a simple random sample <em>with</em> replacement. In real life, this very rarely matters. If the population of interest is large (e.g., has more than 10 entities!) the difference between sampling with- and without-replacement is too small to be concerned with. The difference between simple random samples and biased samples, on the other hand, is not such an easy thing to dismiss.</p>
</section>
<section id="most-samples-are-not-simple-random-samples" class="level3 page-columns page-full" data-number="10.1.3">
<h3 data-number="10.1.3" class="anchored" data-anchor-id="most-samples-are-not-simple-random-samples"><span class="header-section-number">10.1.3</span> Most samples are not simple random samples</h3>
<p>As you can see from looking at the list of possible populations that I showed above, it is almost impossible to obtain a simple random sample from most populations of interest. When I run experiments, I’d consider it a minor miracle if my participants turned out to be a random sampling of the undergraduate psychology students at Adelaide university, even though this is by far the narrowest population that I might want to generalise to. A thorough discussion of other types of sampling schemes is beyond the scope of this book, but to give you a sense of what’s out there I’ll list a few of the more important ones:</p>
<ul>
<li><em>Stratified sampling</em>. Suppose your population is (or can be) divided into several different subpopulations, or <em>strata</em>. Perhaps you’re running a study at several different sites, for example. Instead of trying to sample randomly from the population as a whole, you instead try to collect a separate random sample from each of the strata. Stratified sampling is sometimes easier to do than simple random sampling, especially when the population is already divided into the distinct strata. It can also be more efficient than simple random sampling, especially when some of the subpopulations are rare. For instance, when studying schizophrenia it would be much better to divide the population into two<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> strata (schizophrenic and not-schizophrenic), and then sample an equal number of people from each group. If you selected people randomly, you would get so few schizophrenic people in the sample that your study would be useless. This specific kind of stratified sampling is referred to as <em>oversampling</em> because it makes a deliberate attempt to over-represent rare groups.</li>
<li><em>Snowball sampling</em> is a technique that is especially useful when sampling from a “hidden” or hard to access population, and is especially common in social sciences. For instance, suppose the researchers want to conduct an opinion poll among transgender people. The research team might only have contact details for a few trans folks, so the survey starts by asking them to participate (stage 1). At the end of the survey, the participants are asked to provide contact details for other people who might want to participate. In stage 2, those new contacts are surveyed. The process continues until the researchers have sufficient data. The big advantage to snowball sampling is that it gets you data in situations that might otherwise be impossible to get any. On the statistical side, the main disadvantage is that the sample is highly non-random, and non-random in ways that are difficult to address. On the real life side, the disadvantage is that the procedure can be unethical if not handled well, because hidden populations are often hidden for a reason. I chose transgender people as an example here to highlight this: if you weren’t careful you might end up outing people who don’t want to be outed (very, very bad form), and even if you don’t make that mistake it can still be intrusive to use people’s social networks to study them. It’s certainly very hard to get people’s informed consent <em>before</em> contacting them, yet in many cases the simple act of contacting them and saying “hey we want to study you” can be hurtful. Social networks are complex things, and just because you can use them to get data doesn’t always mean you should.</li>
<li><em>Convenience sampling</em> is more or less what it sounds like. The samples are chosen in a way that is convenient to the researcher, and not selected at random from the population of interest. Snowball sampling is one type of convenience sampling, but there are many others. A common example in psychology is studies that rely on undergraduate psychology students. These samples are generally non-random in two respects: firstly, reliance on undergraduate psychology students automatically means that your data are restricted to a single subpopulation. Secondly, the students usually get to pick which studies they participate in, so the sample is a self selected subset of psychology students not a randomly selected subset. In real life, most studies are convenience samples of one form or another. This is sometimes a severe limitation, but not always.</li>
</ul>
<div class="no-row-height column-margin column-container"><div id="fn2"><p><sup>2</sup>&nbsp;Nothing in life is that simple: there’s not an obvious division of people into binary categories like “schizophrenic” and “not schizophrenic”. But this isn’t a clinical psychology text, so please forgive me a few simplifications here and there.</p></div></div></section>
<section id="how-much-does-it-matter-if-you-dont-have-a-simple-random-sample" class="level3" data-number="10.1.4">
<h3 data-number="10.1.4" class="anchored" data-anchor-id="how-much-does-it-matter-if-you-dont-have-a-simple-random-sample"><span class="header-section-number">10.1.4</span> How much does it matter if you don’t have a simple random sample?</h3>
<p>Okay, so real world data collection tends not to involve nice simple random samples. Does that matter? A little thought should make it clear to you that it <em>can</em> matter if your data are not a simple random sample: just think about the difference between <a href="#fig-srs1" class="quarto-xref">Figure&nbsp;<span>10.1</span></a> and <a href="#fig-brs" class="quarto-xref">Figure&nbsp;<span>10.2</span></a>. However, it’s not quite as bad as it sounds. Some types of biased samples are entirely unproblematic. For instance, when using a stratified sampling technique you actually <em>know</em> what the bias is because you created it deliberately, often to <em>increase</em> the effectiveness of your study, and there are statistical techniques that you can use to adjust for the biases you’ve introduced (not covered in this book!). So in those situations it’s not a problem.</p>
<p>More generally though, it’s important to remember that random sampling is a means to an end, not the end in itself. Let’s assume you’ve relied on a convenience sample, and as such you can assume it’s biased. A bias in your sampling method is only a problem if it causes you to draw the wrong conclusions. When viewed from that perspective, I’d argue that we don’t need the sample to be randomly generated in <em>every</em> respect: we only need it to be random with respect to the psychologically-relevant phenomenon of interest. Suppose I’m doing a study looking at working memory capacity. In study 1, I actually have the ability to sample randomly from all human beings currently alive, with one exception: I can only sample people born on a Monday. In study 2, I am able to sample randomly from the Australian population. I want to generalise my results to the population of all living humans. Which study is better? The answer, obviously, is study 1. Why? Because we have no reason to think that being “born on a Monday” has any interesting relationship to working memory capacity. In contrast, I can think of several reasons why “being Australian” might matter. Australia is a wealthy, industrialised country with a very well-developed education system. People growing up in that system will have had life experiences much more similar to the experiences of the people who designed the tests for working memory capacity. This shared experience might easily translate into similar beliefs about how to “take a test”, a shared assumption about how psychological experimentation works, and so on. These things might actually matter. For instance, “test taking” style might have taught the Australian participants how to direct their attention exclusively on fairly abstract test materials relative to people that haven’t grown up in a similar environment; leading to a misleading picture of what working memory capacity is.</p>
<p>There are two points hidden in this discussion. Firstly, when designing your own studies, it’s important to think about what population you care about, and try hard to sample in a way that is appropriate to that population. In practice, you’re usually forced to put up with a “sample of convenience” (e.g., psychology lecturers sample psychology students because that’s the least expensive way to collect data, and our coffers aren’t exactly overflowing with gold), but if so you should at least spend some time thinking about what the dangers of this practice might be.</p>
<p>Secondly, if you’re going to criticise someone else’s study because they’ve used a sample of convenience rather than laboriously sampling randomly from the entire human population, at least have the courtesy to offer a specific theory as to <em>how</em> this might have distorted the results. Remember, everyone in science is aware of this issue, and does what they can to alleviate it. Merely pointing out that “the study only included people from group BLAH” is entirely unhelpful, and borders on being insulting to the researchers, who are <em>of course</em> aware of the issue. They just don’t happen to be in possession of the infinite supply of time and money required to construct the perfect sample. In short, if you want to offer a responsible critique of the sampling process, then be <em>helpful</em>. Rehashing the blindingly obvious truisms that I’ve been rambling on about in this section isn’t helpful.</p>
</section>
<section id="population-parameters-and-sample-statistics" class="level3" data-number="10.1.5">
<h3 data-number="10.1.5" class="anchored" data-anchor-id="population-parameters-and-sample-statistics"><span class="header-section-number">10.1.5</span> Population parameters and sample statistics</h3>
<p>Okay. Setting aside the thorny methodological issues associated with obtaining a random sample and my rather unfortunate tendency to rant about lazy methodological criticism, let’s consider a slightly different issue. Up to this point we have been talking about populations the way a scientist might. To a psychologist, a population might be a group of people. To an ecologist, a population might be a group of bears. In most cases the populations that scientists care about are concrete things that actually exist in the real world. Statisticians, however, are a funny lot. On the one hand, they <em>are</em> interested in real world data and real science in the same way that scientists are. On the other hand, they also operate in the realm of pure abstraction in the way that mathematicians do. As a consequence, statistical theory tends to be a bit abstract in how a population is defined. In much the same way that psychological researchers operationalise our abstract theoretical ideas in terms of concrete measurements (<a href="02-studydesign.html#sec-measurement" class="quarto-xref"><span>Section 2.1</span></a>), statisticians operationalise the concept of a “population” in terms of mathematical objects that they know how to work with. You’ve already come across these objects in <a href="09-probability.html" class="quarto-xref"><span>Chapter 9</span></a>: they’re called probability distributions.</p>
<p>The idea is quite simple. Let’s say we’re talking about IQ scores. To a psychologist, the population of interest is a group of actual humans who have IQ scores. A statistician “simplifies” this by operationally defining the population as a probability distribution. IQ tests are designed so that the average IQ is 100, the standard deviation of IQ scores is 15, and the distribution of IQ scores is normal. These values are referred to as the <strong><em>population parameters</em></strong> because they are characteristics of the entire population. That is, we say that the population mean <span class="math inline">\(\mu\)</span> is 100, and the population standard deviation <span class="math inline">\(\sigma\)</span> is 15.</p>
<p>Now suppose I run an experiment. I select 100 people at random and administer an IQ test, giving me a simple random sample from the population. If I plot a histogram of the sample, I get something that – while roughly the right shape – is a fairly crude approximation to the population distribution. If I instead select 10,000 people, the approximation gets much better. <a href="#fig-IQdist" class="quarto-xref">Figure&nbsp;<span>10.4</span></a> shows all three: the population distribution, a sample of 100, and a sample of 10,000.</p>
<div id="fig-IQdist" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-IQdist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-IQdist" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-IQdist-1" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-IQdist-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-IQdist-1.png" id="fig-IQdist-1" class="img-fluid figure-img" data-ref-parent="fig-IQdist" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-IQdist-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-IQdist" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-IQdist-2" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-IQdist-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-IQdist-2.png" id="fig-IQdist-2" class="img-fluid figure-img" data-ref-parent="fig-IQdist" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-IQdist-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-IQdist" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-IQdist-3" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-IQdist-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-IQdist-3.png" id="fig-IQdist-3" class="img-fluid figure-img" data-ref-parent="fig-IQdist" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-IQdist-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-IQdist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.4: The population distribution of IQ scores (panel a) and two samples drawn randomly from it. In panel b we have a sample of 100 observations, and panel c we have a sample of 10,000 observations.
</figcaption>
</figure>
</div>
<p>When I calculate the mean of my sample of 100, I get a number that is fairly close to the population mean 100 but not identical: in this particular sample, the mean IQ is 101.1 and the standard deviation is 15.7. These <strong><em>sample statistics</em></strong> are properties of my data set, and although they are fairly similar to the true population values, they are not the same. In general, sample statistics are the things you can calculate from your data set, and the population parameters are the things you want to learn about. Later on in this chapter I’ll talk about how you can estimate population parameters using your sample statistics (<a href="#sec-pointestimates" class="quarto-xref"><span>Section 10.4</span></a>) and how to work out how confident you are in your estimates (<a href="#sec-ci" class="quarto-xref"><span>Section 10.5</span></a>) but before we get to that there’s a few more ideas in sampling theory that you need to know about.</p>
</section>
</section>
<section id="sec-lawlargenumbers" class="level2 page-columns page-full" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="sec-lawlargenumbers"><span class="header-section-number">10.2</span> The law of large numbers</h2>
<p>In the previous section I showed you the results of one fictitious IQ experiment with a sample size of <span class="math inline">\(N=100\)</span>. The results were somewhat encouraging: the true population mean is 100, and the sample mean we obtained is a pretty reasonable approximation to it. In many scientific studies that level of precision is perfectly acceptable, but in other situations you need to be a lot more precise. If we want our sample statistics to be much closer to the population parameters, what can we do about it?</p>
<p>The obvious answer is to collect more data. Suppose that we ran a much larger experiment, this time measuring the IQs of 10,000 people. We can simulate the results of this experiment using R. In <a href="09-probability.html#sec-normal" class="quarto-xref"><span>Section 9.5</span></a> I introduced the <code>rnorm()</code> function, which generates random numbers sampled from a normal distribution. For an experiment with a sample size of <code>n = 10000</code>, and a population with <code>mean = 100</code> and <code>sd = 15</code>, R produces our fake IQ data using these commands:</p>
<div class="cell" data-trunc-head="4" data-trunc-tail="3">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>IQ <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">10000</span>, <span class="at">mean =</span> <span class="dv">100</span>, <span class="at">sd =</span> <span class="dv">15</span>) <span class="co"># generate IQ scores</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>IQ <span class="ot">&lt;-</span> <span class="fu">round</span>(IQ) <span class="co"># IQs are whole numbers!</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(IQ)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    [1]  97 112  76 110  87 101 120  93 115 105  84 116 113  84  93 105  91 100
   [19]  98 109  94 114 108 106  89  96 112  64 126 117 121  99 101 114  92 102
   [37]  87 103  87 103  98 106  98 110  85 111  94 102 106  78  73 109 110  99
   [55] 107  94 130  93  89 123  90  89  79 102 111 111 115 119  97  86  90 122

BLAH BLAH BLAH

 [9955]  55 106 114 126  81  92  85  80 104 111  96 102  76  83  98  98 100 103
 [9973]  95  90 100 114 113 105  80 110  90  89 121 129 124 111 122  95 119  93
 [9991] 111 117 110  80 103  92 118 111 108 119</code></pre>
</div>
</div>
<p>I can compute the mean IQ using the command <code>mean(IQ)</code> and the standard deviation using the command <code>sd(IQ)</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(IQ)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 100.2329</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(IQ)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15.00699</code></pre>
</div>
</div>
<p>and I can draw a histogram using <code>hist()</code> – this is exactly what produced panel c of <a href="#fig-IQdist" class="quarto-xref">Figure&nbsp;<span>10.4</span></a> above. Even a moment’s inspection makes clear that the larger sample is a much better approximation to the true population distribution than the smaller one, and the sample statistics bear this out: both the mean and standard deviation are now very close to the true population values.</p>
<p>I feel a bit silly saying this, but the thing I want you to take away from this is that large samples generally give you better information. I feel silly saying it because it’s so bloody obvious that it shouldn’t need to be said. In fact, it’s such an obvious point that when Jacob Bernoulli – one of the founders of probability theory – formalised this idea back in 1713, he was kind of a jerk about it. Here’s how he described the fact that we all share this intuition:</p>
<div class="pullquote">
<p><em>For even the most stupid of men, by some instinct of nature, by himself and without any instruction (which is a remarkable thing), is convinced that the more observations have been made, the less danger there is of wandering from one’s goal.</em></p>
<p>— Jacob Bernoulli <span class="citation" data-cites="Stigler1986">(see <a href="references.html#ref-Stigler1986" role="doc-biblioref">Stigler, 1986, p. 65</a>)</span></p>
</div>
<p>Okay, so the passage comes across as a bit condescending (not to mention sexist), but his main point is correct: it really does feel obvious that more data will give you better answers. The question is, why is this so? Not surprisingly, this intuition that we all share turns out to be correct, and statisticians refer to it as the <strong><em>law of large numbers</em></strong>. The law of large numbers is a mathematical law that applies to many different sample statistics, but the simplest way to think about it is as a law about averages. The sample mean is the most obvious example of a statistic that relies on averaging (because that’s what the mean is… an average), so let’s look at that. When applied to the sample mean, what the law of large numbers states is that as the sample gets larger, the sample mean tends to get closer to the true population mean. Or, to say it a little bit more precisely, as the sample size “approaches” infinity (written as <span class="math inline">\(N \rightarrow \infty\)</span>) the sample mean approaches the population mean (<span class="math inline">\(\bar{X} \rightarrow \mu\)</span>).<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn3"><p><sup>3</sup>&nbsp;Technically, the law of large numbers pertains to any sample statistic that can be described as an average of independent quantities. That’s certainly true for the sample mean. However, it’s also possible to write many other sample statistics as averages of one form or another. The variance of a sample, for instance, can be rewritten as a kind of average and so is subject to the law of large numbers. The minimum value of a sample, however, cannot be written as an average of anything and is therefore not governed by the law of large numbers.</p></div></div><p>I don’t intend to subject you to a proof that the law of large numbers is true, but it’s one of the most important tools for statistical theory. The law of large numbers is the thing we can use to justify our belief that collecting more and more data will eventually lead us to the truth. For any particular data set, the sample statistics that we calculate from it will be wrong, but the law of large numbers tells us that if we keep collecting more data those sample statistics will tend to get closer and closer to the true population parameters.</p>
</section>
<section id="sec-samplesandclt" class="level2 page-columns page-full" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="sec-samplesandclt"><span class="header-section-number">10.3</span> Sampling distributions and the central limit theorem</h2>
<p>The law of large numbers is a very powerful tool, but it’s not going to be good enough to answer all our questions. Among other things, all it gives us is a “long run guarantee”. In the long run, if we were somehow able to collect an infinite amount of data, then the law of large numbers guarantees that our sample statistics will be correct. But as John Maynard Keynes famously argued in economics, a long run guarantee is of little use in real life:</p>
<div class="pullquote">
<p><em>[The] long run is a misleading guide to current affairs. In the long run we are all dead. Economists set themselves too easy, too useless a task, if in tempestuous seasons they can only tell us, that when the storm is long past, the ocean is flat again.</em></p>
<p>— John Maynard Keynes <span class="citation" data-cites="Keynes1923">(<a href="references.html#ref-Keynes1923" role="doc-biblioref">Keynes, 1923, p. 80</a>)</span></p>
</div>
<p>As in economics, so too in psychology and statistics. It is not enough to know that we will <em>eventually</em> arrive at the right answer when calculating the sample mean. Knowing that an infinitely large data set will tell me the exact value of the population mean is cold comfort when my <em>actual</em> data set has a sample size of <span class="math inline">\(N=100\)</span>. In real life, then, we must know something about the behaviour of the sample mean when it is calculated from a more modest data set!</p>
<section id="sec-samplingdists" class="level3" data-number="10.3.1">
<h3 data-number="10.3.1" class="anchored" data-anchor-id="sec-samplingdists"><span class="header-section-number">10.3.1</span> Sampling distribution of the mean</h3>
<p>With this in mind, let’s abandon the idea that our studies will have sample sizes of 10000, and consider a very modest experiment indeed. This time around we’ll sample <span class="math inline">\(N=5\)</span> people and measure their IQ scores. As before, I can simulate this experiment in R using the <code>rnorm()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>iq_1 <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">5</span>, <span class="at">mean =</span> <span class="dv">100</span>, <span class="at">sd =</span> <span class="dv">15</span>))</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>iq_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 100 107  85  99  92</code></pre>
</div>
</div>
<p>The mean IQ in this sample turns out to be 96.6. Not surprisingly, this is much less accurate than the previous experiment. Now imagine that I decided to <strong><em>replicate</em></strong> the experiment. That is, I repeat the procedure as closely as possible: I randomly sample 5 new people and measure their IQ. Again, R allows me to simulate the results of this procedure:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>iq_2 <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">5</span>, <span class="at">mean =</span> <span class="dv">100</span>, <span class="at">sd =</span> <span class="dv">15</span>))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>iq_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  78  89 108 106 102</code></pre>
</div>
</div>
<p>This time around, the mean IQ in my sample is 96.6. If I repeat the experiment 10 times I obtain the results shown in <a href="#tbl-replications" class="quarto-xref">Table&nbsp;<span>10.1</span></a>, and as you can see the sample mean varies from one replication to the next.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>replications <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">replicate</span>(<span class="dv">10</span>, <span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="dv">5</span>, <span class="dv">100</span>, <span class="dv">15</span>))))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>sample_means <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rowMeans</span>(replications), <span class="dv">1</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>replication_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(replications, <span class="st">"Sample Mean"</span> <span class="ot">=</span> sample_means, <span class="at">check.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(replication_table) <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">"Replication"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(replication_table, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="fu">paste</span>(<span class="st">"Person"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>), <span class="st">"Sample Mean"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-replications" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-replications-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.1: Ten replications of the IQ experiment, each with a sample size of <span class="math inline">\(N=5\)</span>.
</figcaption>
<div aria-describedby="tbl-replications-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 20%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Person 1</th>
<th style="text-align: right;">Person 2</th>
<th style="text-align: right;">Person 3</th>
<th style="text-align: right;">Person 4</th>
<th style="text-align: right;">Person 5</th>
<th style="text-align: right;">Sample Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Replication 1</td>
<td style="text-align: right;">93</td>
<td style="text-align: right;">109</td>
<td style="text-align: right;">119</td>
<td style="text-align: right;">104</td>
<td style="text-align: right;">111</td>
<td style="text-align: right;">107.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Replication 2</td>
<td style="text-align: right;">114</td>
<td style="text-align: right;">91</td>
<td style="text-align: right;">111</td>
<td style="text-align: right;">87</td>
<td style="text-align: right;">87</td>
<td style="text-align: right;">98.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Replication 3</td>
<td style="text-align: right;">135</td>
<td style="text-align: right;">93</td>
<td style="text-align: right;">129</td>
<td style="text-align: right;">94</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">110.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Replication 4</td>
<td style="text-align: right;">92</td>
<td style="text-align: right;">87</td>
<td style="text-align: right;">87</td>
<td style="text-align: right;">107</td>
<td style="text-align: right;">99</td>
<td style="text-align: right;">94.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Replication 5</td>
<td style="text-align: right;">112</td>
<td style="text-align: right;">106</td>
<td style="text-align: right;">119</td>
<td style="text-align: right;">125</td>
<td style="text-align: right;">110</td>
<td style="text-align: right;">114.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Replication 6</td>
<td style="text-align: right;">83</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">117</td>
<td style="text-align: right;">97</td>
<td style="text-align: right;">88</td>
<td style="text-align: right;">92.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Replication 7</td>
<td style="text-align: right;">98</td>
<td style="text-align: right;">101</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">113</td>
<td style="text-align: right;">127</td>
<td style="text-align: right;">107.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Replication 8</td>
<td style="text-align: right;">67</td>
<td style="text-align: right;">109</td>
<td style="text-align: right;">124</td>
<td style="text-align: right;">111</td>
<td style="text-align: right;">95</td>
<td style="text-align: right;">101.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Replication 9</td>
<td style="text-align: right;">88</td>
<td style="text-align: right;">111</td>
<td style="text-align: right;">111</td>
<td style="text-align: right;">118</td>
<td style="text-align: right;">99</td>
<td style="text-align: right;">105.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Replication 10</td>
<td style="text-align: right;">101</td>
<td style="text-align: right;">122</td>
<td style="text-align: right;">97</td>
<td style="text-align: right;">125</td>
<td style="text-align: right;">98</td>
<td style="text-align: right;">108.6</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Now suppose that I decided to keep going in this fashion, replicating this “five IQ scores” experiment over and over again. Every time I replicate the experiment I write down the sample mean. Over time, I’d be amassing a new data set, in which every experiment generates a single data point – the first ten of which are the “Sample Mean” column of <a href="#tbl-replications" class="quarto-xref">Table&nbsp;<span>10.1</span></a>. What if I continued like this for 10,000 replications, and then drew a histogram? Using the magical powers of R that’s exactly what I did, and you can see the results in <a href="#fig-sampdistmean" class="quarto-xref">Figure&nbsp;<span>10.5</span></a>. As this picture illustrates, the average of 5 IQ scores is usually between 80 and 120. But more importantly, what it highlights is that if we replicate an experiment over and over again, what we end up with is a <em>distribution</em> of sample means! This distribution has a special name in statistics: it’s called the <strong><em>sampling distribution of the mean</em></strong>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-sampdistmean" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sampdistmean-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-sampdistmean-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sampdistmean-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.5: The sampling distribution of the mean for the “five IQ scores experiment”. If you sample 5 people at random and calculate their <em>average</em> IQ, you’ll almost certainly get a number between 80 and 120, even though there are quite a lot of individuals who have IQs above 120 or below 80. For comparison, the black line plots the population distribution of IQ scores.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Sampling distributions are another important theoretical idea in statistics, and they’re crucial for understanding the behaviour of small samples. For instance, when I ran the very first “five IQ scores” experiment above, the sample mean turned out to be 96.6. What the sampling distribution in <a href="#fig-sampdistmean" class="quarto-xref">Figure&nbsp;<span>10.5</span></a> tells us, though, is that the “five IQ scores” experiment is not very accurate. If I repeat the experiment, the sampling distribution tells me that I can expect to see a sample mean anywhere between 80 and 120.</p>
</section>
<section id="sampling-distributions-exist-for-any-sample-statistic" class="level3" data-number="10.3.2">
<h3 data-number="10.3.2" class="anchored" data-anchor-id="sampling-distributions-exist-for-any-sample-statistic"><span class="header-section-number">10.3.2</span> Sampling distributions exist for any sample statistic!</h3>
<p>One thing to keep in mind when thinking about sampling distributions is that <em>any</em> sample statistic you might care to calculate has a sampling distribution. For example, suppose that each time I replicated the “five IQ scores” experiment I wrote down the largest IQ score in the experiment. Doing this over and over again would give me a very different sampling distribution, namely the <em>sampling distribution of the maximum</em>. The sampling distribution of the maximum of 5 IQ scores is shown in <a href="#fig-sampdistmax" class="quarto-xref">Figure&nbsp;<span>10.6</span></a>. Not surprisingly, if you pick 5 people at random and then find the person with the highest IQ score, they’re going to have an above average IQ. Most of the time you’ll end up with someone whose IQ is measured in the 100 to 140 range.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-sampdistmax" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sampdistmax-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-sampdistmax-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sampdistmax-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.6: The sampling distribution of the <em>maximum</em> for the “five IQ scores experiment”. If you sample 5 people at random and select the one with the highest IQ score, you’ll probably see someone with an IQ between 100 and 140.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="sec-clt" class="level3 page-columns page-full" data-number="10.3.3">
<h3 data-number="10.3.3" class="anchored" data-anchor-id="sec-clt"><span class="header-section-number">10.3.3</span> The central limit theorem</h3>
<p>At this point I hope you have a pretty good sense of what sampling distributions are, and in particular what the sampling distribution of the mean is. In this section I want to talk about how the sampling distribution of the mean changes as a function of sample size. Intuitively, you already know part of the answer: if you only have a few observations, the sample mean is likely to be quite inaccurate: if you replicate a small experiment and recalculate the mean you’ll get a very different answer. In other words, the sampling distribution is quite wide. If you replicate a large experiment and recalculate the sample mean you’ll probably get the same answer you got last time, so the sampling distribution will be very narrow. You can see this visually in <a href="#fig-IQsamp" class="quarto-xref">Figure&nbsp;<span>10.7</span></a>: the bigger the sample size, the narrower the sampling distribution gets.</p>
<div id="fig-IQsamp" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-IQsamp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-IQsamp" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-IQsamp-1" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-IQsamp-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-IQsamp-1.png" id="fig-IQsamp-1" class="img-fluid figure-img" data-ref-parent="fig-IQsamp" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-IQsamp-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-IQsamp" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-IQsamp-2" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-IQsamp-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-IQsamp-2.png" id="fig-IQsamp-2" class="img-fluid figure-img" data-ref-parent="fig-IQsamp" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-IQsamp-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-IQsamp" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-IQsamp-3" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-IQsamp-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-IQsamp-3.png" id="fig-IQsamp-3" class="img-fluid figure-img" data-ref-parent="fig-IQsamp" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-IQsamp-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-IQsamp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.7: An illustration of how the sampling distribution of the mean depends on sample size. In each panel, 10,000 samples of IQ data were generated, and the mean IQ observed within each of these data sets was calculated. The histograms in these plots show the distribution of these means (i.e., the sampling distribution of the mean). Each individual IQ score was drawn from a normal distribution with mean 100 and standard deviation 15, shown as the solid black line. In panel a, each data set contained only a single observation, so the mean of each sample is just one person’s IQ score, and the sampling distribution of the mean is identical to the population distribution. When we raise the sample size to 2 (panel b), the mean of any one sample tends to be closer to the population mean than one person’s IQ score, so the sampling distribution is a bit narrower. By the time we raise the sample size to 10 (panel c), the distribution of sample means is fairly tightly clustered around the true population mean.
</figcaption>
</figure>
</div>
<p>We can quantify this narrowing effect by calculating the standard deviation of the sampling distribution, which is referred to as the <strong><em>standard error</em></strong>. The standard error of a statistic is often denoted SE, and since we’re usually interested in the standard error of the sample <em>mean</em>, we often use the acronym SEM. As you can see just by looking at <a href="#fig-IQsamp" class="quarto-xref">Figure&nbsp;<span>10.7</span></a>, as the sample size <span class="math inline">\(N\)</span> increases, the SEM decreases.</p>
<p>Okay, so that’s one part of the story. However, there’s something I’ve been glossing over so far. All my examples up to this point have been based on the “IQ scores” experiments, and because IQ scores are roughly normally distributed, I’ve assumed that the population distribution is normal. What if it isn’t normal? What happens to the sampling distribution of the mean? The remarkable thing is this: no matter what shape your population distribution is, as <span class="math inline">\(N\)</span> increases the sampling distribution of the mean starts to look more like a normal distribution. To give you a sense of this, I ran some simulations using R. To do this, I started with a “ramped” population distribution – specifically a beta distribution that looks nothing like a normal distribution at all. Next, I used R to simulate the results of a large number of experiments, taking <span class="math inline">\(N=2\)</span> samples from this distribution each time and calculating the sample mean. <a href="#fig-cltdemo" class="quarto-xref">Figure&nbsp;<span>10.8</span></a> (b) plots the histogram of these sample means (i.e., the sampling distribution of the mean for <span class="math inline">\(N=2\)</span>). This time, the histogram produces a <span class="math inline">\(\cap\)</span>-shaped distribution: it’s still not normal, but it’s a lot closer to the black line than the population distribution in <a href="#fig-cltdemo" class="quarto-xref">Figure&nbsp;<span>10.8</span></a> (a). When I increase the sample size to <span class="math inline">\(N=4\)</span>, the sampling distribution of the mean is very close to normal (<a href="#fig-cltdemo" class="quarto-xref">Figure&nbsp;<span>10.8</span></a> c), and by the time we reach a sample size of <span class="math inline">\(N=8\)</span> it’s almost perfectly normal. In other words, as long as your sample size isn’t tiny, the sampling distribution of the mean will be approximately normal no matter what your population distribution looks like!</p>
<div id="fig-cltdemo" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cltdemo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cltdemo" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-cltdemo-1" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-cltdemo-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-cltdemo-1.png" id="fig-cltdemo-1" class="img-fluid figure-img" data-ref-parent="fig-cltdemo" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-cltdemo-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cltdemo" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-cltdemo-2" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-cltdemo-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-cltdemo-2.png" id="fig-cltdemo-2" class="img-fluid figure-img" data-ref-parent="fig-cltdemo" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-cltdemo-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cltdemo" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-cltdemo-3" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-cltdemo-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-cltdemo-3.png" id="fig-cltdemo-3" class="img-fluid figure-img" data-ref-parent="fig-cltdemo" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-cltdemo-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cltdemo" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-cltdemo-4" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-cltdemo-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-cltdemo-4.png" id="fig-cltdemo-4" class="img-fluid figure-img" data-ref-parent="fig-cltdemo" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-cltdemo-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cltdemo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.8: A demonstration of the central limit theorem. In panel a, we have a non-normal population distribution (a beta distribution); and panels b-d show the sampling distribution of the mean for samples of size 2, 4 and 8, for data drawn from the distribution in panel a. As you can see, even though the original population distribution is non-normal, the sampling distribution of the mean becomes pretty close to normal by the time you have a sample of even 4 observations.
</figcaption>
</figure>
</div>
<p>On the basis of these figures, it seems like we have evidence for all of the following claims about the sampling distribution of the mean:</p>
<ul>
<li>The mean of the sampling distribution is the same as the mean of the population</li>
<li>The standard deviation of the sampling distribution (i.e., the standard error) gets smaller as the sample size increases</li>
<li>The shape of the sampling distribution becomes normal as the sample size increases</li>
</ul>
<p>As it happens, not only are all of these statements true, there is a very famous theorem in statistics that proves all three of them, known as the <strong><em>central limit theorem</em></strong>. Among other things, the central limit theorem tells us that if the population distribution has mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span>, then the sampling distribution of the mean also has mean <span class="math inline">\(\mu\)</span>, and the standard error of the mean is</p>
<p><span class="math display">\[
\mbox{SEM} = \frac{\sigma}{ \sqrt{N} }
\]</span></p>
<p>Because we divide the population standard deviation <span class="math inline">\(\sigma\)</span> by the square root of the sample size <span class="math inline">\(N\)</span>, the SEM gets smaller as the sample size increases. It also tells us that the shape of the sampling distribution becomes normal.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn4"><p><sup>4</sup>&nbsp;As usual, I’m being a bit sloppy here. The central limit theorem is a bit more general than this section implies. Like most introductory stats texts, I’ve discussed one situation where the central limit theorem holds: when you’re taking an average across lots of independent events drawn from the same distribution. However, the central limit theorem is much broader than this. There’s a whole class of things called “<span class="math inline">\(U\)</span>-statistics” for instance, all of which satisfy the central limit theorem and therefore become normally distributed for large sample sizes. The mean is one such statistic, but it’s not the only one.</p></div></div><p>This result is useful for all sorts of things. It tells us why large experiments are more reliable than small ones, and because it gives us an explicit formula for the standard error it tells us <em>how much</em> more reliable a large experiment is. It tells us why the normal distribution is, well, <em>normal</em>. In real experiments, many of the things that we want to measure are actually averages of lots of different quantities (e.g., arguably, “general” intelligence as measured by IQ is an average of a large number of “specific” skills and abilities), and when that happens, the averaged quantity should follow a normal distribution. Because of this mathematical law, the normal distribution pops up over and over again in real data.</p>
</section>
</section>
<section id="sec-pointestimates" class="level2 page-columns page-full" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="sec-pointestimates"><span class="header-section-number">10.4</span> Estimating population parameters</h2>
<p>In all the IQ examples in the previous sections, we actually knew the population parameters ahead of time. As every undergraduate gets taught in their very first lecture on the measurement of intelligence, IQ scores are <em>defined</em> to have mean 100 and standard deviation 15. However, this is a bit of a lie. How do we know that IQ scores have a true population mean of 100? Well, we know this because the people who designed the tests have administered them to very large samples, and have then “rigged” the scoring rules so that their sample has mean 100. That’s not a bad thing of course: it’s an important part of designing a psychological measurement. However, it’s important to keep in mind that this theoretical mean of 100 only attaches to the population that the test designers used to design the tests. Good test designers will actually go to some lengths to provide “test norms” that can apply to lots of different populations (e.g., different age groups, nationalities etc).</p>
<p>This is very handy, but of course almost every research project of interest involves looking at a different population of people to those used in the test norms. For instance, suppose you wanted to measure the effect of low level lead poisoning on cognitive functioning in Port Pirie, a South Australian industrial town with a lead smelter. Perhaps you decide that you want to compare IQ scores among people in Port Pirie to a comparable sample in Whyalla, a South Australian industrial town with a steel refinery.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> Regardless of which town you’re thinking about, it doesn’t make a lot of sense simply to <em>assume</em> that the true population mean IQ is 100. No-one has, to my knowledge, produced sensible norming data that can automatically be applied to South Australian industrial towns. We’re going to have to <strong><em>estimate</em></strong> the population parameters from a sample of data. So how do we do this?</p>
<div class="no-row-height column-margin column-container"><div id="fn5"><p><sup>5</sup>&nbsp;Please note that if you were <em>actually</em> interested in this question, you would need to be a <em>lot</em> more careful than I’m being here. You <em>can’t</em> just compare IQ scores in Whyalla to Port Pirie and assume that any differences are due to lead poisoning. Even if it were true that the only differences between the two towns corresponded to the different refineries (and it isn’t, not by a long shot), you need to account for the fact that people already <em>believe</em> that lead pollution causes cognitive deficits: if you recall back to <a href="02-studydesign.html" class="quarto-xref"><span>Chapter 2</span></a>, this means that there are different demand effects for the Port Pirie sample than for the Whyalla sample. In other words, you might end up with an illusory group difference in your data, caused by the fact that people <em>think</em> that there is a real difference. I find it pretty implausible to think that the locals wouldn’t be well aware of what you were trying to do if a bunch of researchers turned up in Port Pirie with lab coats and IQ tests, and even less plausible to think that a lot of people would be pretty resentful of you for doing it. Those people won’t be as co-operative in the tests. Other people in Port Pirie might be <em>more</em> motivated to do well because they don’t want their home town to look bad. The motivational effects that would apply in Whyalla are likely to be weaker, because people don’t have any concept of “iron ore poisoning” in the same way that they have a concept for “lead poisoning”. Psychology is <em>hard</em>.</p></div></div><section id="estimating-the-population-mean" class="level3" data-number="10.4.1">
<h3 data-number="10.4.1" class="anchored" data-anchor-id="estimating-the-population-mean"><span class="header-section-number">10.4.1</span> Estimating the population mean</h3>
<p>Suppose we go to Port Pirie and 100 of the locals are kind enough to sit through an IQ test. The average IQ score among these people turns out to be <span class="math inline">\(\bar{X}=98.5\)</span>. So what is the true mean IQ for the entire population of Port Pirie? Obviously, we don’t know the answer to that question. It could be <span class="math inline">\(97.2\)</span>, but it could also be <span class="math inline">\(103.5\)</span>. Our sampling isn’t exhaustive so we cannot give a definitive answer. Nevertheless if I was forced at gunpoint to give a “best guess” I’d have to say <span class="math inline">\(98.5\)</span>. That’s the essence of statistical estimation: giving a best guess.</p>
<p>In this example, estimating the unknown population parameter is straightforward. I calculate the sample mean, and I use that as my <strong><em>estimate of the population mean</em></strong>. It’s pretty simple, and in the next section I’ll explain the statistical justification for this intuitive answer. However, for the moment what I want to do is make sure you recognise that the sample statistic and the estimate of the population parameter are conceptually different things. A sample statistic is a description of your data, whereas the estimate is a guess about the population. With that in mind, statisticians often use different notation to refer to them. For instance, if the true population mean is denoted <span class="math inline">\(\mu\)</span>, then we would use <span class="math inline">\(\hat\mu\)</span> to refer to our estimate of the population mean. In contrast, the sample mean is denoted <span class="math inline">\(\bar{X}\)</span> or sometimes <span class="math inline">\(m\)</span>. However, in simple random samples, the estimate of the population mean is identical to the sample mean: if I observe a sample mean of <span class="math inline">\(\bar{X} = 98.5\)</span>, then my estimate of the population mean is also <span class="math inline">\(\hat\mu = 98.5\)</span>. To help keep the notation clear, here’s a handy table:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Symbol</th>
<th>What is it?</th>
<th>Do we know what it is?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\bar{X}\)</span></td>
<td>Sample mean</td>
<td>Yes, calculated from the raw data</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mu\)</span></td>
<td>True population mean</td>
<td>Almost never known for sure</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\hat{\mu}\)</span></td>
<td>Estimate of the population mean</td>
<td>Yes, identical to the sample mean</td>
</tr>
</tbody>
</table>
</section>
<section id="estimating-the-population-standard-deviation" class="level3 page-columns page-full" data-number="10.4.2">
<h3 data-number="10.4.2" class="anchored" data-anchor-id="estimating-the-population-standard-deviation"><span class="header-section-number">10.4.2</span> Estimating the population standard deviation</h3>
<p>So far, estimation seems pretty simple, and you might be wondering why I forced you to read through all that stuff about sampling theory. In the case of the mean, our estimate of the population parameter (i.e.&nbsp;<span class="math inline">\(\hat\mu\)</span>) turned out to be identical to the corresponding sample statistic (i.e.&nbsp;<span class="math inline">\(\bar{X}\)</span>). However, that’s not always true. To see this, let’s have a think about how to construct an <strong><em>estimate of the population standard deviation</em></strong>, which we’ll denote <span class="math inline">\(\hat\sigma\)</span>. What shall we use as our estimate in this case? Your first thought might be that we could do the same thing we did when estimating the mean, and just use the sample statistic as our estimate. That’s almost the right thing to do, but not quite.</p>
<p>Here’s why. Suppose I have a sample that contains a single observation. For this example, it helps to consider a sample where you have no intuitions at all about what the true population values might be, so let’s use something completely fictitious. Suppose the observation in question measures the <em>cromulence</em> of my shoes. It turns out that my shoes have a cromulence of 20. So here’s my sample:</p>
<pre><code>20</code></pre>
<p>This is a perfectly legitimate sample, even if it does have a sample size of <span class="math inline">\(N=1\)</span>. It has a sample mean of 20, and because every observation in this sample is equal to the sample mean (obviously!) it has a sample standard deviation of 0. As a description of the <em>sample</em> this seems quite right: the sample contains a single observation and therefore there is no variation observed within the sample. A sample standard deviation of <span class="math inline">\(s = 0\)</span> is the right answer here. But as an estimate of the <em>population</em> standard deviation, it feels completely insane, right? Admittedly, you and I don’t know anything at all about what “cromulence” is, but we know something about data: the only reason that we don’t see any variability in the <em>sample</em> is that the sample is too small to display any variation! So, if you have a sample size of <span class="math inline">\(N=1\)</span>, it <em>feels</em> like the right answer is just to say “no idea at all”.</p>
<p>Notice that you <em>don’t</em> have the same intuition when it comes to the sample mean and the population mean. If forced to make a best guess about the population mean, it doesn’t feel completely insane to guess that the population mean is 20. Sure, you probably wouldn’t feel very confident in that guess, because you have only the one observation to work with, but it’s still the best guess you can make.</p>
<p>Let’s extend this example a little. Suppose I now make a second observation. My data set now has <span class="math inline">\(N=2\)</span> observations of the cromulence of shoes, and the complete sample now looks like this:</p>
<pre><code>20, 22</code></pre>
<p>This time around, our sample is <em>just</em> large enough for us to be able to observe some variability: two observations is the bare minimum number needed for any variability to be observed! For our new data set, the sample mean is <span class="math inline">\(\bar{X}=21\)</span>, and the sample standard deviation is <span class="math inline">\(s=1\)</span>. What intuitions do we have about the population? Again, as far as the population mean goes, the best guess we can possibly make is the sample mean: if forced to guess, we’d probably guess that the population mean cromulence is 21. What about the standard deviation? This is a little more complicated. The sample standard deviation is only based on two observations, and if you’re at all like me you probably have the intuition that, with only two observations, we haven’t given the population “enough of a chance” to reveal its true variability to us. It’s not just that we suspect that the estimate is <em>wrong</em>: after all, with only two observations we expect it to be wrong to some degree. The worry is that the error is <em>systematic</em>. Specifically, we suspect that the sample standard deviation is likely to be smaller than the population standard deviation.</p>
<p>This intuition feels right, but it would be nice to demonstrate this somehow. There are in fact mathematical proofs that confirm this intuition, but unless you have the right mathematical background they don’t help very much. Instead, what I’ll do is use R to simulate the results of some experiments. With that in mind, let’s return to our IQ studies. Suppose the true population mean IQ is 100 and the standard deviation is 15. I can use the <code>rnorm()</code> function to generate the results of an experiment in which I measure <span class="math inline">\(N=2\)</span> IQ scores, and calculate the sample standard deviation (using the <span class="math inline">\(s\)</span> formula, dividing by <span class="math inline">\(N\)</span> rather than <span class="math inline">\(N-1\)</span>). If I do this over and over again, and plot a histogram of these sample standard deviations, what I have is the <em>sampling distribution of the standard deviation</em>. I’ve plotted this distribution in <a href="#fig-sampdistsd" class="quarto-xref">Figure&nbsp;<span>10.9</span></a>.</p>
<div class="cell" data-scratch="start">
<div class="cell-output-display">
<div id="fig-sampdistsd" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sampdistsd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-sampdistsd-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sampdistsd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.9: The sampling distribution of the sample standard deviation for a “two IQ scores” experiment. The true population standard deviation is 15 (dashed line), but as you can see from the histogram, the vast majority of experiments will produce a much smaller sample standard deviation than this. In other words, the sample standard deviation is a <em>biased</em> estimate of the population standard deviation.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Even though the true population standard deviation is 15, the average of the <em>sample</em> standard deviations across these 100,000 replications is only 8.4. Notice that this is a very different result to what we found when we plotted the sampling distribution of the mean in <a href="#fig-IQsamp" class="quarto-xref">Figure&nbsp;<span>10.7</span></a>: there, the population mean is 100, and the average of the sample means is also 100.</p>
<p>Now let’s extend the simulation. Instead of restricting ourselves to the situation where we have a sample size of <span class="math inline">\(N=2\)</span>, let’s repeat the exercise for sample sizes from 1 to 10. If we plot the average sample mean and average sample standard deviation as a function of sample size, we get the results shown in <a href="#fig-estimatorbias" class="quarto-xref">Figure&nbsp;<span>10.10</span></a>. On the left hand side (panel a), I’ve plotted the average sample mean and on the right hand side (panel b), I’ve plotted the average standard deviation. The two plots are quite different: <em>on average</em>, the average sample mean is equal to the population mean. It is an <strong><em>unbiased estimator</em></strong>, which is essentially the reason why your best estimate for the population mean is the sample mean.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> The plot on the right is quite different: on average, the sample standard deviation <span class="math inline">\(s\)</span> is <em>smaller</em> than the population standard deviation <span class="math inline">\(\sigma\)</span>. It is a <strong><em>biased estimator</em></strong>. In other words, if we want to make a “best guess” <span class="math inline">\(\hat\sigma\)</span> about the value of the population standard deviation <span class="math inline">\(\sigma\)</span>, we should make sure our guess is a little bit larger than the sample standard deviation <span class="math inline">\(s\)</span>.</p>
<div class="no-row-height column-margin column-container"><div id="fn6"><p><sup>6</sup>&nbsp;I should note that I’m hiding something here. Unbiasedness is a desirable characteristic for an estimator, but there are other things that matter besides bias. However, it’s beyond the scope of this book to discuss this in any detail. I just want to draw your attention to the fact that there’s some hidden complexity here.</p></div></div><div id="fig-estimatorbias" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-estimatorbias-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-estimatorbias" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-estimatorbias-1" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-estimatorbias-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-estimatorbias-1.png" id="fig-estimatorbias-1" class="img-fluid figure-img" data-ref-parent="fig-estimatorbias" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-estimatorbias-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-estimatorbias" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-estimatorbias-2" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-estimatorbias-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-estimatorbias-2.png" id="fig-estimatorbias-2" class="img-fluid figure-img" data-ref-parent="fig-estimatorbias" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-estimatorbias-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-estimatorbias-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.10: An illustration of the fact that the sample mean is an unbiased estimator of the population mean (panel a), but the sample standard deviation is a biased estimator of the population standard deviation (panel b). To generate the figure, 10,000 simulated data sets were generated with 1 observation each, 10,000 more with 2 observations, and so on up to a sample size of 10. Each data set consisted of fake IQ data: that is, the data were normally distributed with a true population mean of 100 and standard deviation 15. <em>On average</em>, the sample means turn out to be 100, regardless of sample size (panel a). However, the sample standard deviations turn out to be systematically too small (panel b), especially for small sample sizes.
</figcaption>
</figure>
</div>
<p>The fix to this systematic bias turns out to be very simple. Here’s how it works. Before tackling the standard deviation, let’s look at the variance. If you recall from <a href="05-descriptives.html#sec-var" class="quarto-xref"><span>Section 5.2</span></a>, the sample variance is defined to be the average of the squared deviations from the sample mean. That is:</p>
<p><span class="math display">\[
s^2 = \frac{1}{N} \sum_{i=1}^N (X_i - \bar{X})^2
\]</span></p>
<p>The sample variance <span class="math inline">\(s^2\)</span> is a biased estimator of the population variance <span class="math inline">\(\sigma^2\)</span>. But as it turns out, we only need to make a tiny tweak to transform this into an unbiased estimator. All we have to do is divide by <span class="math inline">\(N-1\)</span> rather than by <span class="math inline">\(N\)</span>. If we do that, we obtain the following formula:</p>
<p><span class="math display">\[
\hat\sigma^2 = \frac{1}{N-1} \sum_{i=1}^N (X_i - \bar{X})^2
\]</span></p>
<p>This is an unbiased estimator of the population variance <span class="math inline">\(\sigma^2\)</span>. Moreover, this finally answers the question we raised in <a href="05-descriptives.html#sec-var" class="quarto-xref"><span>Section 5.2</span></a>. Why did R give us slightly different answers when we used the <code>var()</code> function? Because the <code>var()</code> function calculates <span class="math inline">\(\hat\sigma^2\)</span> not <span class="math inline">\(s^2\)</span>, that’s why. A similar story applies for the standard deviation. If we divide by <span class="math inline">\(N-1\)</span> rather than <span class="math inline">\(N\)</span>, our estimate of the population standard deviation becomes:</p>
<p><span class="math display">\[
\hat\sigma = \sqrt{\frac{1}{N-1} \sum_{i=1}^N (X_i - \bar{X})^2}
\]</span></p>
<p>and when we use R’s built in standard deviation function <code>sd()</code>, what it’s doing is calculating <span class="math inline">\(\hat\sigma\)</span>, not <span class="math inline">\(s\)</span>.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn7"><p><sup>7</sup>&nbsp;Okay, I’m hiding something else here. In a bizarre and counterintuitive twist, since <span class="math inline">\(\hat\sigma^2\)</span> is an unbiased estimator of <span class="math inline">\(\sigma^2\)</span>, you’d assume that taking the square root would be fine, and <span class="math inline">\(\hat\sigma\)</span> would be an unbiased estimator of <span class="math inline">\(\sigma\)</span>. Right? Weirdly, it’s not. There’s actually a subtle, tiny bias in <span class="math inline">\(\hat\sigma\)</span>. This is just bizarre: <span class="math inline">\(\hat\sigma^2\)</span> is an unbiased estimate of the population variance <span class="math inline">\(\sigma^2\)</span>, but when you take the square root, it turns out that <span class="math inline">\(\hat\sigma\)</span> is a biased estimator of the population standard deviation <span class="math inline">\(\sigma\)</span>. Weird, weird, weird, right? So, why is <span class="math inline">\(\hat\sigma\)</span> biased? The technical answer is “because non-linear transformations (e.g., the square root) don’t commute with expectation”, but that just sounds like gibberish to everyone who hasn’t taken a course in mathematical statistics. Fortunately, it doesn’t matter for practical purposes. The bias is small, and in real life everyone uses <span class="math inline">\(\hat\sigma\)</span> and it works just fine. Sometimes mathematics is just annoying.</p></div></div><p>One final point: in practice, a lot of people tend to refer to <span class="math inline">\(\hat{\sigma}\)</span> (i.e., the formula where we divide by <span class="math inline">\(N-1\)</span>) as the <em>sample</em> standard deviation. Technically, this is incorrect: the <em>sample</em> standard deviation should be equal to <span class="math inline">\(s\)</span> (i.e., the formula where we divide by <span class="math inline">\(N\)</span>). These aren’t the same thing, either conceptually or numerically. One is a property of the sample, the other is an estimated characteristic of the population. However, in almost every real life application, what we actually care about is the estimate of the population parameter, and so people always report <span class="math inline">\(\hat\sigma\)</span> rather than <span class="math inline">\(s\)</span>. This is the right number to report, of course; it’s just that people tend to get a little bit imprecise about terminology when they write it up, because “sample standard deviation” is shorter than “estimated population standard deviation”. It’s no big deal, and in practice I do the same thing everyone else does. Nevertheless, I think it’s important to keep the two <em>concepts</em> separate: it’s never a good idea to confuse “known properties of your sample” with “guesses about the population from which it came”. The moment you start thinking that <span class="math inline">\(s\)</span> and <span class="math inline">\(\hat\sigma\)</span> are the same thing, you start doing exactly that.</p>
<p>To finish this section off, here’s another couple of tables to help keep things clear:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Symbol</th>
<th>What is it?</th>
<th>Do we know what it is?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(s\)</span></td>
<td>Sample standard deviation</td>
<td>Yes, calculated from the raw data</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\sigma\)</span></td>
<td>Population standard deviation</td>
<td>Almost never known for sure</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\hat{\sigma}\)</span></td>
<td>Estimate of the population standard deviation</td>
<td>Yes, but not the same as the sample standard deviation</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Symbol</th>
<th>What is it?</th>
<th>Do we know what it is?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(s^2\)</span></td>
<td>Sample variance</td>
<td>Yes, calculated from the raw data</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\sigma^2\)</span></td>
<td>Population variance</td>
<td>Almost never known for sure</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\hat{\sigma}^2\)</span></td>
<td>Estimate of the population variance</td>
<td>Yes, but not the same as the sample variance</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="sec-ci" class="level2 page-columns page-full" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="sec-ci"><span class="header-section-number">10.5</span> Estimating a confidence interval</h2>
<div class="pullquote">
<p><em>Statistics means never having to say you’re certain</em></p>
<p>— Unknown origin</p>
</div>
<p>Up to this point in this chapter, I’ve outlined the basics of sampling theory which statisticians rely on to make guesses about population parameters on the basis of a sample of data. As this discussion illustrates, one of the reasons we need all this sampling theory is that every data set leaves us with some uncertainty, so our estimates are never going to be perfectly accurate. The thing that has been missing from this discussion is an attempt to <em>quantify</em> the amount of uncertainty that attaches to our estimate. It’s not enough to be able to guess that, say, the mean IQ of undergraduate psychology students is 115 (yes, I just made that number up). We also want to be able to say something that expresses the degree of certainty that we have in our guess. For example, it would be nice to be able to say that there is a 95% chance that the true mean lies between 109 and 121. The name for this is a <strong><em>confidence interval</em></strong> for the mean.</p>
<p>Armed with an understanding of sampling distributions, constructing a confidence interval for the mean is actually pretty easy. Here’s how it works. Suppose the true population mean is <span class="math inline">\(\mu\)</span> and the standard deviation is <span class="math inline">\(\sigma\)</span>. I’ve just finished running my study that has <span class="math inline">\(N\)</span> participants, and the mean IQ among those participants is <span class="math inline">\(\bar{X}\)</span>. We know from our discussion of the central limit theorem (<a href="#sec-clt" class="quarto-xref"><span>Section 10.3.3</span></a>) that the sampling distribution of the mean is approximately normal. We also know from our discussion of the normal distribution (<a href="09-probability.html#sec-normal" class="quarto-xref"><span>Section 9.5</span></a>) that there is a 95% chance that a normally-distributed quantity will fall within two standard deviations of the true mean. To be more precise, we can use the <code>qnorm()</code> function to compute the 2.5th and 97.5th percentiles of the normal distribution:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="at">p =</span> <span class="fu">c</span>(.<span class="dv">025</span>, .<span class="dv">975</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.959964  1.959964</code></pre>
</div>
</div>
<p>Okay, so I lied earlier on. The more correct answer is that there is a 95% chance that a normally-distributed quantity will fall within 1.96 standard deviations of the true mean. Next, recall that the standard deviation of the sampling distribution is referred to as the standard error, and the standard error of the mean is written as SEM. When we put all these pieces together, we learn that there is a 95% probability that the sample mean <span class="math inline">\(\bar{X}\)</span> that we have actually observed lies within 1.96 standard errors of the population mean. Mathematically, we write this as:</p>
<p><span class="math display">\[
\mu - \left( 1.96 \times \mbox{SEM} \right) \ \leq \  \bar{X}\  \leq \  \mu + \left( 1.96 \times \mbox{SEM} \right)
\]</span></p>
<p>where the SEM is equal to <span class="math inline">\(\sigma / \sqrt{N}\)</span>, and we can be 95% confident that this is true. However, that’s not answering the question that we’re actually interested in. The equation above tells us what we should expect about the sample mean, given that we know what the population parameters are. What we <em>want</em> is to have this work the other way around: we want to know what we should believe about the population parameters, given that we have observed a particular sample. However, it’s not too difficult to do this. Using a little high school algebra, a sneaky way to rewrite our equation is like this:</p>
<p><span class="math display">\[
\bar{X} -  \left( 1.96 \times \mbox{SEM} \right) \ \leq \ \mu  \ \leq  \ \bar{X} +  \left( 1.96 \times \mbox{SEM}\right)
\]</span></p>
<p>What this is telling us is that the range of values has a 95% probability of containing the population mean <span class="math inline">\(\mu\)</span>. We refer to this range as a <strong><em>95% confidence interval</em></strong>, denoted <span class="math inline">\(\mbox{CI}_{95}\)</span>. In short, as long as <span class="math inline">\(N\)</span> is sufficiently large – large enough for us to believe that the sampling distribution of the mean is normal – then we can write this as our formula for the 95% confidence interval:</p>
<p><span class="math display">\[
\mbox{CI}_{95} = \bar{X} \pm \left( 1.96 \times \frac{\sigma}{\sqrt{N}} \right)
\]</span></p>
<p>Of course, there’s nothing special about the number 1.96: it just happens to be the multiplier you need to use if you want a 95% confidence interval. If I’d wanted a 70% confidence interval, I could have used the <code>qnorm()</code> function to calculate the 15th and 85th quantiles:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="at">p =</span> <span class="fu">c</span>(.<span class="dv">15</span>, .<span class="dv">85</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.036433  1.036433</code></pre>
</div>
</div>
<p>and so the formula for <span class="math inline">\(\mbox{CI}_{70}\)</span> would be the same as the formula for <span class="math inline">\(\mbox{CI}_{95}\)</span> except that we’d use 1.04 as our magic number rather than 1.96.</p>
<section id="a-slight-mistake-in-the-formula" class="level3" data-number="10.5.1">
<h3 data-number="10.5.1" class="anchored" data-anchor-id="a-slight-mistake-in-the-formula"><span class="header-section-number">10.5.1</span> A slight mistake in the formula</h3>
<p>As usual, I lied. The formula that I’ve given above for the 95% confidence interval is approximately correct, but I glossed over an important detail in the discussion. Notice my formula requires you to use the standard error of the mean, SEM, which in turn requires you to use the true population standard deviation <span class="math inline">\(\sigma\)</span>. Yet, in <a href="#sec-pointestimates" class="quarto-xref"><span>Section 10.4</span></a> I stressed the fact that we don’t actually <em>know</em> the true population parameters. Because we don’t know the true value of <span class="math inline">\(\sigma\)</span>, we have to use an estimate of the population standard deviation <span class="math inline">\(\hat{\sigma}\)</span> instead. This is pretty straightforward to do, but this has the consequence that we need to use the quantiles of the <span class="math inline">\(t\)</span>-distribution rather than the normal distribution to calculate our magic number; and the answer depends on the sample size. When <span class="math inline">\(N\)</span> is very large, we get pretty much the same value using <code>qt()</code> that we would if we used <code>qnorm()</code>…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10000</span> <span class="co"># suppose our sample size is 10,000</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="at">p =</span> .<span class="dv">975</span>, <span class="at">df =</span> N <span class="sc">-</span> <span class="dv">1</span>) <span class="co"># calculate the 97.5th quantile of the t-dist</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.960201</code></pre>
</div>
</div>
<p>But when <span class="math inline">\(N\)</span> is small, we get a much bigger number when we use the <span class="math inline">\(t\)</span> distribution:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10</span> <span class="co"># suppose our sample size is 10</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="at">p =</span> .<span class="dv">975</span>, <span class="at">df =</span> N <span class="sc">-</span> <span class="dv">1</span>) <span class="co"># calculate the 97.5th quantile of the t-dist</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.262157</code></pre>
</div>
</div>
<p>There’s nothing too mysterious about what’s happening here. Bigger values mean that the confidence interval is wider, indicating that we’re more uncertain about what the true value of <span class="math inline">\(\mu\)</span> actually is. When we use the <span class="math inline">\(t\)</span> distribution instead of the normal distribution, we get bigger numbers, indicating that we have more uncertainty. And why do we have that extra uncertainty? Well, because our estimate of the population standard deviation <span class="math inline">\(\hat\sigma\)</span> might be wrong! If it’s wrong, it implies that we’re a bit less sure about what our sampling distribution of the mean actually looks like… and this uncertainty ends up getting reflected in a wider confidence interval.</p>
</section>
<section id="interpreting-a-confidence-interval" class="level3" data-number="10.5.2">
<h3 data-number="10.5.2" class="anchored" data-anchor-id="interpreting-a-confidence-interval"><span class="header-section-number">10.5.2</span> Interpreting a confidence interval</h3>
<p>The hardest thing about confidence intervals is understanding what they <em>mean</em>. Whenever people first encounter confidence intervals, the first instinct is almost always to say that “there is a 95% probability that the true mean lies inside the confidence interval”. It’s simple, and it seems to capture the common sense idea of what it means to say that I am “95% confident”. Unfortunately, it’s not quite right. The intuitive definition relies very heavily on your own personal <em>beliefs</em> about the value of the population mean. I say that I am 95% confident because those are my beliefs. In everyday life that’s perfectly okay, but if you remember back to <a href="09-probability.html#sec-probmeaning" class="quarto-xref"><span>Section 9.2</span></a>, you’ll notice that talking about personal belief and confidence is a Bayesian idea. Personally (speaking as a Bayesian) I have no problem with the idea that the phrase “95% probability” is allowed to refer to a personal belief. However, confidence intervals are <em>not</em> Bayesian tools. Like everything else in this chapter, confidence intervals are <em>frequentist</em> tools, and if you are going to use frequentist methods then it’s not appropriate to attach a Bayesian interpretation to them. If you use frequentist methods, you must adopt frequentist interpretations!</p>
<p>Okay, so if that’s not the right answer, what is? Remember what we said about frequentist probability: the only way we are allowed to make “probability statements” is to talk about a sequence of events, and to count up the frequencies of different kinds of events. From that perspective, the interpretation of a 95% confidence interval must have something to do with replication. Specifically: if we replicated the experiment over and over again and computed a 95% confidence interval for each replication, then 95% of those <em>intervals</em> would contain the true mean. More generally, 95% of all confidence intervals constructed using this procedure should contain the true population mean. This idea is illustrated in <a href="#fig-cirep" class="quarto-xref">Figure&nbsp;<span>10.11</span></a>, which shows 50 confidence intervals constructed for a “measure 10 IQ scores” experiment (top panel) and another 50 confidence intervals for a “measure 25 IQ scores” experiment (bottom panel).</p>
<div id="fig-cirep" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cirep-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cirep" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-cirep-1" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-cirep-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-cirep-1.png" id="fig-cirep-1" class="img-fluid figure-img" data-ref-parent="fig-cirep" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-cirep-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cirep" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-cirep-2" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-cirep-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-cirep-2.png" id="fig-cirep-2" class="img-fluid figure-img" data-ref-parent="fig-cirep" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-cirep-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cirep-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.11: 95% confidence intervals. The top panel (a) shows 50 simulated replications of an experiment in which we measure the IQs of 10 people. The dot marks the location of the sample mean, and the line shows the 95% confidence interval. The lower panel (b) shows a similar simulation, but this time simulating replications of an experiment that measures the IQs of 25 people. Intervals that do not contain the true mean (i.e., 100) are marked in blue, with an asterisk below.
</figcaption>
</figure>
</div>
<p>In this particular run of the simulation, 1 of the 100 confidence intervals shown in <a href="#fig-cirep" class="quarto-xref">Figure&nbsp;<span>10.11</span></a> failed to contain the true mean – close to, but not necessarily exactly, the 5 we’d expect on average in the long run.</p>
<p>The critical difference here is that the Bayesian claim makes a probability statement about the population mean (i.e., it refers to our uncertainty about the population mean), which is not allowed under the frequentist interpretation of probability because you can’t “replicate” a population! In the frequentist claim, the population mean is fixed and no probabilistic claims can be made about it. Confidence intervals, however, are repeatable so we can replicate experiments. Therefore a frequentist is allowed to talk about the probability that the <em>confidence interval</em> (a random variable) contains the true mean; but is not allowed to talk about the probability that the <em>true population mean</em> (not a repeatable event) falls within the confidence interval.</p>
<p>I know that this seems a little pedantic, but it does matter. It matters because the difference in interpretation leads to a difference in the mathematics. There is a Bayesian alternative to confidence intervals, known as <em>credible intervals</em>. In most situations credible intervals are quite similar to confidence intervals, but in other cases they are drastically different. As promised, though, I’ll talk more about the Bayesian perspective in <a href="17-bayes.html" class="quarto-xref"><span>Chapter 17</span></a>.</p>
</section>
<section id="calculating-confidence-intervals-in-r" class="level3 page-columns page-full" data-number="10.5.3">
<h3 data-number="10.5.3" class="anchored" data-anchor-id="calculating-confidence-intervals-in-r"><span class="header-section-number">10.5.3</span> Calculating confidence intervals in R</h3>
<p>As far as I can tell, the core packages in R don’t include a simple function for calculating confidence intervals for the mean. They <em>do</em> include a lot of complicated, extremely powerful functions that can be used to calculate confidence intervals associated with lots of different things, such as the <code>confint()</code> function that we’ll use in <a href="./15-regression.html">Linear regression</a>. But I figure that when you’re first learning statistics, it might be useful to start with something simpler. As a consequence, the <code>lsr</code> package includes a function called <code>ciMean()</code> which you can use to calculate your confidence intervals. There are two arguments that you might want to specify:<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn8"><p><sup>8</sup>&nbsp;These are the only arguments to the function, and <code>ciMean()</code> is deliberately kept simple – it’s meant as a stepping stone before you move on to more general tools like <code>confint()</code>.</p></div></div><ul>
<li><code>x</code>. This should be a numeric vector containing the data.</li>
<li><code>conf</code>. This should be a number, specifying the confidence level. By default, <code>conf = .95</code>, since 95% confidence intervals are the de facto standard in psychology.</li>
</ul>
<p>So, for example, if I load the <code>afl24.Rdata</code> file, I can calculate the confidence interval associated with the mean attendance:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/afl24.Rdata"</span>) <span class="co"># contains the "afl" data frame</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ciMean</span>(<span class="at">x =</span> afl<span class="sc">$</span>attendance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         2.5%    97.5%
[1,] 31597.32 32593.12</code></pre>
</div>
</div>
<p>Hopefully that’s fairly clear.</p>
</section>
<section id="sec-ciplots" class="level3" data-number="10.5.4">
<h3 data-number="10.5.4" class="anchored" data-anchor-id="sec-ciplots"><span class="header-section-number">10.5.4</span> Plotting confidence intervals in R</h3>
<p>There’s several different ways you can draw graphs that show confidence intervals as error bars. I’ll show three versions here, but this certainly doesn’t exhaust the possibilities. In doing so, what I’m assuming is that you want to draw a plot showing the means and confidence intervals for one variable, broken down by different levels of a second variable. For instance, in our <code>afl</code> data that we discussed earlier, we might be interested in plotting the average <code>attendance</code> by <code>year</code>. I’ll do this using three different functions, <code>bargraph.CI()</code> and <code>lineplot.CI()</code> (both of which are in the <code>sciplot</code> package), and <code>plotmeans()</code> (which is in the <code>gplots</code> package). Assuming that you’ve installed these packages on your system (see <a href="04-mechanics.html#sec-packageinstall" class="quarto-xref"><span>Section 4.2</span></a> if you’ve forgotten how to do this), you’ll need to load them. You’ll also need to load the <code>lsr</code> package, because we’ll make use of the <code>ciMean()</code> function to actually calculate the confidence intervals:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sciplot) <span class="co"># bargraph.CI() and lineplot.CI() functions</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gplots) <span class="co"># plotmeans() function</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lsr) <span class="co"># ciMean() function</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here’s how to plot the means and confidence intervals drawn using <code>bargraph.CI()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bargraph.CI</span>(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x.factor =</span> year, <span class="co"># grouping variable</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">response =</span> attendance, <span class="co"># outcome variable</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> afl, <span class="co"># data frame with the variables</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ci.fun =</span> ciMean, <span class="co"># name of the function to calculate CIs</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Year"</span>, <span class="co"># x-axis label</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Average Attendance"</span> <span class="co"># y-axis label</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-bargraphCI" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bargraphCI-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-bargraphCI-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bargraphCI-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.12: Means and 95% confidence intervals for AFL <code>attendance</code>, plotted separately for each <code>year</code> from 1987 to 2010. This graph was drawn using the <code>bargraph.CI()</code> function.
</figcaption>
</figure>
</div>
</div>
</div>
<p>This produces the output shown in <a href="#fig-bargraphCI" class="quarto-xref">Figure&nbsp;<span>10.12</span></a>. We can use the same arguments when calling the <code>lineplot.CI()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lineplot.CI</span>(</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x.factor =</span> year, <span class="co"># grouping variable</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">response =</span> attendance, <span class="co"># outcome variable</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> afl, <span class="co"># data frame with the variables</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ci.fun =</span> ciMean, <span class="co"># name of the function to calculate CIs</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Year"</span>, <span class="co"># x-axis label</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Average Attendance"</span> <span class="co"># y-axis label</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-lineplotCI" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lineplotCI-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-lineplotCI-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lineplotCI-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.13: Means and 95% confidence intervals for AFL <code>attendance</code>, plotted separately for each <code>year</code> from 1987 to 2010. This graph was drawn using the <code>lineplot.CI()</code> function.
</figcaption>
</figure>
</div>
</div>
</div>
<p>And the output for this command is shown in <a href="#fig-lineplotCI" class="quarto-xref">Figure&nbsp;<span>10.13</span></a>. Finally, here’s how you would do it using <code>plotmeans()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotmeans</span>(</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> attendance <span class="sc">~</span> year, <span class="co"># outcome ~ group</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> afl, <span class="co"># data frame with the variables</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">n.label =</span> <span class="cn">FALSE</span> <span class="co"># don't show the sample sizes</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-plotmeans" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plotmeans-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-estimation_files/figure-html/fig-plotmeans-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plotmeans-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.14: Means and 95% confidence intervals for AFL <code>attendance</code>, plotted separately for each <code>year</code> from 1987 to 2010. This graph was drawn using the <code>plotmeans()</code> function.
</figcaption>
</figure>
</div>
</div>
</div>
<p>This is shown in <a href="#fig-plotmeans" class="quarto-xref">Figure&nbsp;<span>10.14</span></a>.</p>
</section>
</section>
<section id="sec-estimationvstesting" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="sec-estimationvstesting"><span class="header-section-number">10.6</span> Epilogue: estimation over testing?</h2>
<p>The confidence interval this chapter builds towards is not just a historical curiosity: it’s the centrepiece of an argument, still very much alive, about how psychologists should report their results at all. In an influential 2014 paper unambiguously titled “The New Statistics: Why and How,” <span class="citation" data-cites="Cumming2014">Cumming (<a href="references.html#ref-Cumming2014" role="doc-biblioref">2014</a>)</span> argued that psychology should shift away from null hypothesis significance testing and towards routinely reporting effect sizes, confidence intervals, and meta-analytic thinking instead – treating estimation, not testing, as the primary goal of data analysis. It’s a proposal that dovetails neatly with <a href="11-hypothesistesting.html" class="quarto-xref"><span>Chapter 11</span></a>’s own epilogue: if <span class="math inline">\(p &lt; .05\)</span> dichotomies are the problem, reporting “how big, and how uncertain” instead of “significant or not” looks like an obvious fix.</p>
<p>The trouble is that confidence intervals don’t automatically deliver on what “the new statistics” wants them to do. <span class="citation" data-cites="Hoekstra2014">Hoekstra et al. (<a href="references.html#ref-Hoekstra2014" role="doc-biblioref">2014</a>)</span> found that a large majority of researchers and students – and even some methods instructors – misread confidence intervals in exactly the way <a href="#sec-ci" class="quarto-xref"><span>Section 10.5</span></a> warned you not to, treating them as a statement about the probability that the population parameter lies in the interval, which is the Bayesian reading, not the frequentist one this chapter actually derives. More pointedly, <span class="citation" data-cites="Morey2016">Morey et al. (<a href="references.html#ref-Morey2016" role="doc-biblioref">2016</a>)</span> argued that this isn’t merely a widespread misunderstanding to be fixed with better teaching: several of the properties casually claimed for confidence intervals – that a narrower CI means a more precise estimate, that values inside the interval are somehow “more plausible” than values outside it – don’t actually follow from the frequentist theory of confidence intervals at all, and can be shown to fail in perfectly ordinary examples. On their reading, getting a confidence interval to behave the way researchers <em>want</em> it to behave requires quietly importing the same kind of Bayesian assumptions that confidence intervals were invented to avoid in the first place.</p>
<p>None of this means confidence intervals are useless, and it doesn’t retract anything said earlier in this chapter about how to construct or correctly interpret one. But it’s a useful corrective to the idea that switching from <span class="math inline">\(p\)</span>-values to confidence intervals is a free lunch: the “estimation, not testing” recommendation trades one well-known set of interpretive traps for a different, less widely appreciated one, and a good deal of the applied literature still writes about confidence intervals as though the traps aren’t there.</p>
</section>
<section id="summary" class="level2" data-number="10.7">
<h2 data-number="10.7" class="anchored" data-anchor-id="summary"><span class="header-section-number">10.7</span> Summary</h2>
<p>In this chapter I’ve covered two main topics. The first half of the chapter talks about sampling theory, and the second half talks about how we can use sampling theory to construct estimates of the population parameters. The section breakdown looks like this:</p>
<ul>
<li>Basic ideas about samples, sampling and populations (<a href="#sec-srs" class="quarto-xref"><span>Section 10.1</span></a>)</li>
<li>Statistical theory of sampling: the law of large numbers (<a href="#sec-lawlargenumbers" class="quarto-xref"><span>Section 10.2</span></a>), sampling distributions and the central limit theorem (<a href="#sec-samplesandclt" class="quarto-xref"><span>Section 10.3</span></a>)</li>
<li>Estimating means and standard deviations (<a href="#sec-pointestimates" class="quarto-xref"><span>Section 10.4</span></a>)</li>
<li>Estimating a confidence interval (<a href="#sec-ci" class="quarto-xref"><span>Section 10.5</span></a>)</li>
</ul>
<p>As always, there’s a lot of topics related to sampling and estimation that aren’t covered in this chapter, but for an introductory psychology class this is fairly comprehensive I think. For most applied researchers you won’t need much more theory than this. One big question that I haven’t touched on in this chapter is what you do when you don’t have a simple random sample. There is a lot of statistical theory you can draw on to handle this situation, but it’s well beyond the scope of this book.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-Cumming2014" class="csl-entry" role="listitem">
Cumming, G. (2014). The new statistics: Why and how. <em>Psychological Science</em>, <em>25</em>(1), 7–29. <a href="https://doi.org/10.1177/0956797613504966">https://doi.org/10.1177/0956797613504966</a>
</div>
<div id="ref-Hoekstra2014" class="csl-entry" role="listitem">
Hoekstra, R., Morey, R. D., Rouder, J. N., &amp; Wagenmakers, E.-J. (2014). Robust misinterpretation of confidence intervals. <em>Psychonomic Bulletin &amp; Review</em>, <em>21</em>(5), 1157–1164. <a href="https://doi.org/10.3758/s13423-013-0572-3">https://doi.org/10.3758/s13423-013-0572-3</a>
</div>
<div id="ref-Keynes1923" class="csl-entry" role="listitem">
Keynes, J. M. (1923). <em>A tract on monetary reform</em>. Macmillan; Company.
</div>
<div id="ref-Morey2016" class="csl-entry" role="listitem">
Morey, R. D., Hoekstra, R., Rouder, J. N., Lee, M. D., &amp; Wagenmakers, E.-J. (2016). The fallacy of placing confidence in confidence intervals. <em>Psychonomic Bulletin &amp; Review</em>, <em>23</em>(1), 103–123. <a href="https://doi.org/10.3758/s13423-015-0947-8">https://doi.org/10.3758/s13423-015-0947-8</a>
</div>
<div id="ref-Stigler1986" class="csl-entry" role="listitem">
Stigler, S. M. (1986). <em>The history of statistics</em>. Harvard University Press.
</div>
</div>
</section>


</main> <!-- /main -->
<!-- plausible -->
<script async="" defer="" data-domain="learningstatisticswithr.com" src="https://plausible.io/js/plausible.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/learningstatisticswithr\.com");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./09-probability.html" class="pagination-link" aria-label="Introduction to probability">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Introduction to probability</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./11-hypothesistesting.html" class="pagination-link" aria-label="Hypothesis testing">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>