<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>12&nbsp; Categorical data analysis – Learning Statistics with R</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./13-ttest.html" rel="next">
<link href="./11-hypothesistesting.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-7245ae1d8f5b1c8e9ac8f6417b8d2b04.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="12&nbsp; Categorical data analysis – Learning Statistics with R">
<meta property="og:description" content="">
<meta property="og:image" content="https://learningstatisticswithr.com/cover/cover-social.jpg">
<meta property="og:site_name" content="Learning Statistics with R">
<meta name="twitter:title" content="12&nbsp; Categorical data analysis – Learning Statistics with R">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://learningstatisticswithr.com/cover/cover-social.jpg">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating slimcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./12-chisquare.html">Statistical tools</a></li><li class="breadcrumb-item"><a href="./12-chisquare.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Categorical data analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Learning Statistics with R</a> 
        <div class="sidebar-tools-main">
    <a href="./Learning-Statistics-with-R.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data sets</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Background</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./background-preamble.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">A word on statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-whystats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why do we learn statistics?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-studydesign.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">A brief introduction to research design</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">An introduction to R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-introR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Getting started with R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-mechanics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">R mechanics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Working with data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-descriptives.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Descriptive statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-graphics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Drawing graphs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-datahandling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Pragmatic matters</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-scripting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Basic programming</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical theory</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./theory-preamble.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">A chat about inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Introduction to probability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Estimating unknown quantities from a sample</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-hypothesistesting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical tools</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-chisquare.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Categorical data analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-ttest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">The <span class="math inline">\(t\)</span>-test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Comparing several means (one-way ANOVA)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Linear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-anova2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Endings, alternatives and prospects</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Bayesian statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./epilogue.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Epilogue</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./changelog.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Changelog</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-goftest" id="toc-sec-goftest" class="nav-link active" data-scroll-target="#sec-goftest"><span class="header-section-number">12.1</span> The <span class="math inline">\(\chi^2\)</span> goodness-of-fit test</a>
  <ul class="collapse">
  <li><a href="#the-cards-data" id="toc-the-cards-data" class="nav-link" data-scroll-target="#the-cards-data"><span class="header-section-number">12.1.1</span> The cards data</a></li>
  <li><a href="#the-null-hypothesis-and-the-alternative-hypothesis" id="toc-the-null-hypothesis-and-the-alternative-hypothesis" class="nav-link" data-scroll-target="#the-null-hypothesis-and-the-alternative-hypothesis"><span class="header-section-number">12.1.2</span> The null hypothesis and the alternative hypothesis</a></li>
  <li><a href="#the-goodness-of-fit-test-statistic" id="toc-the-goodness-of-fit-test-statistic" class="nav-link" data-scroll-target="#the-goodness-of-fit-test-statistic"><span class="header-section-number">12.1.3</span> The “goodness of fit” test statistic</a></li>
  <li><a href="#the-sampling-distribution-of-the-gof-statistic" id="toc-the-sampling-distribution-of-the-gof-statistic" class="nav-link" data-scroll-target="#the-sampling-distribution-of-the-gof-statistic"><span class="header-section-number">12.1.4</span> The sampling distribution of the GOF statistic</a></li>
  <li><a href="#degrees-of-freedom" id="toc-degrees-of-freedom" class="nav-link" data-scroll-target="#degrees-of-freedom"><span class="header-section-number">12.1.5</span> Degrees of freedom</a></li>
  <li><a href="#testing-the-null-hypothesis" id="toc-testing-the-null-hypothesis" class="nav-link" data-scroll-target="#testing-the-null-hypothesis"><span class="header-section-number">12.1.6</span> Testing the null hypothesis</a></li>
  <li><a href="#sec-goftestinr" id="toc-sec-goftestinr" class="nav-link" data-scroll-target="#sec-goftestinr"><span class="header-section-number">12.1.7</span> Doing the test in R</a></li>
  <li><a href="#specifying-a-different-null-hypothesis" id="toc-specifying-a-different-null-hypothesis" class="nav-link" data-scroll-target="#specifying-a-different-null-hypothesis"><span class="header-section-number">12.1.8</span> Specifying a different null hypothesis</a></li>
  <li><a href="#sec-chisqreport" id="toc-sec-chisqreport" class="nav-link" data-scroll-target="#sec-chisqreport"><span class="header-section-number">12.1.9</span> How to report the results of the test</a></li>
  <li><a href="#a-comment-on-statistical-notation" id="toc-a-comment-on-statistical-notation" class="nav-link" data-scroll-target="#a-comment-on-statistical-notation"><span class="header-section-number">12.1.10</span> A comment on statistical notation</a></li>
  </ul></li>
  <li><a href="#sec-chisqindependence" id="toc-sec-chisqindependence" class="nav-link" data-scroll-target="#sec-chisqindependence"><span class="header-section-number">12.2</span> The <span class="math inline">\(\chi^2\)</span> test of independence (or association)</a>
  <ul class="collapse">
  <li><a href="#constructing-our-hypothesis-test" id="toc-constructing-our-hypothesis-test" class="nav-link" data-scroll-target="#constructing-our-hypothesis-test"><span class="header-section-number">12.2.1</span> Constructing our hypothesis test</a></li>
  <li><a href="#sec-assoctestinr" id="toc-sec-assoctestinr" class="nav-link" data-scroll-target="#sec-assoctestinr"><span class="header-section-number">12.2.2</span> Doing the test in R</a></li>
  <li><a href="#postscript" id="toc-postscript" class="nav-link" data-scroll-target="#postscript"><span class="header-section-number">12.2.3</span> Postscript</a></li>
  </ul></li>
  <li><a href="#sec-yates" id="toc-sec-yates" class="nav-link" data-scroll-target="#sec-yates"><span class="header-section-number">12.3</span> The continuity correction</a></li>
  <li><a href="#sec-chisqeffectsize" id="toc-sec-chisqeffectsize" class="nav-link" data-scroll-target="#sec-chisqeffectsize"><span class="header-section-number">12.4</span> Effect size</a></li>
  <li><a href="#sec-chisqassumptions" id="toc-sec-chisqassumptions" class="nav-link" data-scroll-target="#sec-chisqassumptions"><span class="header-section-number">12.5</span> Assumptions of the test(s)</a></li>
  <li><a href="#sec-chisqtest" id="toc-sec-chisqtest" class="nav-link" data-scroll-target="#sec-chisqtest"><span class="header-section-number">12.6</span> The most typical way to do chi-square tests in R</a></li>
  <li><a href="#sec-fisherexacttest" id="toc-sec-fisherexacttest" class="nav-link" data-scroll-target="#sec-fisherexacttest"><span class="header-section-number">12.7</span> The Fisher exact test</a></li>
  <li><a href="#sec-mcnemar" id="toc-sec-mcnemar" class="nav-link" data-scroll-target="#sec-mcnemar"><span class="header-section-number">12.8</span> The McNemar test</a>
  <ul class="collapse">
  <li><a href="#doing-the-mcnemar-test-in-r" id="toc-doing-the-mcnemar-test-in-r" class="nav-link" data-scroll-target="#doing-the-mcnemar-test-in-r"><span class="header-section-number">12.8.1</span> Doing the McNemar test in R</a></li>
  </ul></li>
  <li><a href="#whats-the-difference-between-mcnemar-and-independence" id="toc-whats-the-difference-between-mcnemar-and-independence" class="nav-link" data-scroll-target="#whats-the-difference-between-mcnemar-and-independence"><span class="header-section-number">12.9</span> What’s the difference between McNemar and independence?</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">12.10</span> Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./12-chisquare.html">Statistical tools</a></li><li class="breadcrumb-item"><a href="./12-chisquare.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Categorical data analysis</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-chisquare" class="quarto-section-identifier"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Categorical data analysis</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Now that we’ve got the basic theory behind hypothesis testing, it’s time to start looking at specific tests that are commonly used in psychology. So where should we start? Not every textbook agrees on where to start, but I’m going to start with “<span class="math inline">\(\chi^2\)</span> tests” (this chapter) and “<span class="math inline">\(t\)</span>-tests” (<a href="13-ttest.html" class="quarto-xref"><span>Chapter 13</span></a>). Both of these tools are very frequently used in scientific practice, and while they’re not as powerful as “analysis of variance” (<a href="./14-anova.html">Comparing several means (one-way ANOVA)</a>) and “regression” (<a href="./15-regression.html">Linear regression</a>) they’re much easier to understand.</p>
<p>The term “categorical data” is just another name for “nominal scale data”. It’s nothing that we haven’t already discussed, it’s just that in the context of data analysis people tend to use the term “categorical data” rather than “nominal scale data”. I don’t know why. In any case, <strong><em>categorical data analysis</em></strong> refers to a collection of tools that you can use when your data are nominal scale. However, there are a lot of different tools that can be used for categorical data analysis, and this chapter only covers a few of the more common ones.</p>
<section id="sec-goftest" class="level2 page-columns page-full" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="sec-goftest"><span class="header-section-number">12.1</span> The <span class="math inline">\(\chi^2\)</span> goodness-of-fit test</h2>
<p>The <span class="math inline">\(\chi^2\)</span> goodness-of-fit test is one of the oldest hypothesis tests around: it was invented by Karl Pearson around the turn of the century <span class="citation" data-cites="Pearson1900">(<a href="references.html#ref-Pearson1900" role="doc-biblioref">Pearson, 1900</a>)</span>, with some corrections made later by Sir Ronald Fisher <span class="citation" data-cites="Fisher1922">(<a href="references.html#ref-Fisher1922" role="doc-biblioref">Fisher, 1922</a>)</span>. To introduce the statistical problem that it addresses, let’s start with some psychology…</p>
<section id="the-cards-data" class="level3" data-number="12.1.1">
<h3 data-number="12.1.1" class="anchored" data-anchor-id="the-cards-data"><span class="header-section-number">12.1.1</span> The cards data</h3>
<p>Over the years, there have been a lot of studies showing that humans have a lot of difficulties in simulating randomness. Try as we might to “act” random, we <em>think</em> in terms of patterns and structure, and so when asked to “do something at random”, what people actually do is anything but random. As a consequence, the study of human randomness (or non-randomness, as the case may be) opens up a lot of deep psychological questions about how we think about the world. With this in mind, let’s consider a very simple study. Suppose I asked people to imagine a shuffled deck of cards, and mentally pick one card from this imaginary deck “at random”. After they’ve chosen one card, I ask them to mentally select a second one. For both choices, what we’re going to look at is the suit (hearts, clubs, spades or diamonds) that people chose. After asking, say, <span class="math inline">\(N=200\)</span> people to do this, I’d like to look at the data and figure out whether or not the cards that people pretended to select were really random. The data are contained in the <code>randomness.Rdata</code> file, which contains a single data frame called <code>cards</code>. Let’s take a look:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lsr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/randomness.Rdata"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">who</span>(<span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   -- Name --   -- Class --   -- Size --
   cards        data.frame    200 x 3   
    $id         factor        200       
    $choice_1   factor        200       
    $choice_2   factor        200       </code></pre>
</div>
</div>
<p>As you can see, the <code>cards</code> data frame contains three variables, an <code>id</code> variable that assigns a unique identifier to each participant, and the two variables <code>choice_1</code> and <code>choice_2</code> that indicate the card suits that people chose. Here’s the first few entries in the data frame:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(cards)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     id choice_1 choice_2
1 subj1   spades    clubs
2 subj2 diamonds    clubs
3 subj3   hearts    clubs
4 subj4   spades    clubs
5 subj5   hearts   spades
6 subj6    clubs   hearts</code></pre>
</div>
</div>
<p>For the moment, let’s just focus on the first choice that people made. We’ll use the <code>table()</code> function to count the number of times that we observed people choosing each suit. I’ll save the table to a variable called <code>observed</code>, for reasons that will become clear very soon:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>observed <span class="ot">&lt;-</span> <span class="fu">table</span>(cards<span class="sc">$</span>choice_1)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>observed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   clubs diamonds   hearts   spades 
      35       51       64       50 </code></pre>
</div>
</div>
<p>That little frequency table is quite helpful. Looking at it, there’s a bit of a hint that people <em>might</em> be more likely to select hearts than clubs, but it’s not completely obvious just from looking at it whether that’s really true, or if this is just due to chance. So we’ll probably have to do some kind of statistical analysis to find out, which is what I’m going to talk about in the next section.</p>
<p>Excellent. From this point on, we’ll treat this table as the data that we’re looking to analyse. However, since I’m going to have to talk about this data in mathematical terms (sorry!) it might be a good idea to be clear about what the notation is. In R, if I wanted to pull out the number of people that selected diamonds, I could do it by name by typing <code>observed["diamonds"]</code> but, since <code>"diamonds"</code> is the second element of the <code>observed</code> vector, it’s equally effective to refer to it as <code>observed[2]</code>. The mathematical notation for this is pretty similar, except that we shorten the human-readable word “observed” to the letter <span class="math inline">\(O\)</span>, and we use subscripts rather than brackets: so the second observation in our table is written as <code>observed[2]</code> in R, and is written as <span class="math inline">\(O_2\)</span> in maths. The relationship between the English descriptions, the R commands, and the mathematical symbols are illustrated below:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>label</th>
<th>index, <span class="math inline">\(i\)</span></th>
<th>math. symbol</th>
<th>R command</th>
<th>the value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>clubs, <span class="math inline">\(\clubsuit\)</span></td>
<td>1</td>
<td><span class="math inline">\(O_1\)</span></td>
<td><code>observed[1]</code></td>
<td>35</td>
</tr>
<tr class="even">
<td>diamonds, <span class="math inline">\(\diamondsuit\)</span></td>
<td>2</td>
<td><span class="math inline">\(O_2\)</span></td>
<td><code>observed[2]</code></td>
<td>51</td>
</tr>
<tr class="odd">
<td>hearts, <span class="math inline">\(\heartsuit\)</span></td>
<td>3</td>
<td><span class="math inline">\(O_3\)</span></td>
<td><code>observed[3]</code></td>
<td>64</td>
</tr>
<tr class="even">
<td>spades, <span class="math inline">\(\spadesuit\)</span></td>
<td>4</td>
<td><span class="math inline">\(O_4\)</span></td>
<td><code>observed[4]</code></td>
<td>50</td>
</tr>
</tbody>
</table>
<p>Hopefully that’s pretty clear. It’s also worth noting that mathematicians prefer to talk about things in general rather than specific things, so you’ll also see the notation <span class="math inline">\(O_i\)</span>, which refers to the number of observations that fall within the <span class="math inline">\(i\)</span>-th category (where <span class="math inline">\(i\)</span> could be 1, 2, 3 or 4). Finally, if we want to refer to the set of all observed frequencies, statisticians group all of the observed values into a vector, which I’ll refer to as <span class="math inline">\(\mathbf{O}\)</span>. <span class="math display">\[
\mathbf{O} = (O_1, O_2, O_3, O_4)
\]</span> Again, there’s nothing new or interesting here: it’s just notation. If I say that <span class="math inline">\(\mathbf{O} = (35, 51, 64, 50)\)</span> all I’m doing is describing the table of observed frequencies (i.e., <code>observed</code>), but I’m referring to it using mathematical notation, rather than by referring to an R variable.</p>
</section>
<section id="the-null-hypothesis-and-the-alternative-hypothesis" class="level3" data-number="12.1.2">
<h3 data-number="12.1.2" class="anchored" data-anchor-id="the-null-hypothesis-and-the-alternative-hypothesis"><span class="header-section-number">12.1.2</span> The null hypothesis and the alternative hypothesis</h3>
<p>As the last section indicated, our research hypothesis is that “people don’t choose cards randomly”. What we’re going to want to do now is translate this into some statistical hypotheses, and construct a statistical test of those hypotheses. The test that I’m going to describe to you is <strong><em>Pearson’s <span class="math inline">\(\chi^2\)</span> goodness of fit test</em></strong>, and as is so often the case, we have to begin by carefully constructing our null hypothesis. In this case, it’s pretty easy. First, let’s state the null hypothesis in words:</p>
<blockquote class="blockquote">
<p><span class="math inline">\(H_0\)</span>: All four suits are chosen with equal probability</p>
</blockquote>
<p>Now, because this is statistics, we have to be able to say the same thing in a mathematical way. To do this, let’s use the notation <span class="math inline">\(P_j\)</span> to refer to the true probability that the <span class="math inline">\(j\)</span>-th suit is chosen. If the null hypothesis is true, then each of the four suits has a 25% chance of being selected: in other words, our null hypothesis claims that <span class="math inline">\(P_1 = .25\)</span>, <span class="math inline">\(P_2 = .25\)</span>, <span class="math inline">\(P_3 = .25\)</span> and finally that <span class="math inline">\(P_4 = .25\)</span>. However, in the same way that we can group our observed frequencies into a vector <span class="math inline">\(\mathbf{O}\)</span> that summarises the entire data set, we can use <span class="math inline">\(\mathbf{P}\)</span> to refer to the probabilities that correspond to our null hypothesis. So if I let the vector <span class="math inline">\(\mathbf{P} = (P_1, P_2, P_3, P_4)\)</span> refer to the collection of probabilities that describe our null hypothesis, then we have</p>
<blockquote class="blockquote">
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mathbf{P} = (.25, .25, .25, .25)\)</span></p>
</blockquote>
<p>In this particular instance, our null hypothesis corresponds to a vector of probabilities <span class="math inline">\(\mathbf{P}\)</span> in which all of the probabilities are equal to one another. But this doesn’t have to be the case. For instance, if the experimental task was for people to imagine they were drawing from a deck that had twice as many clubs as any other suit, then the null hypothesis would correspond to something like <span class="math inline">\(\mathbf{P} = (.4, .2, .2, .2)\)</span>. As long as the probabilities are all positive numbers, and they all sum to 1, then it’s a perfectly legitimate choice for the null hypothesis. However, the most common use of the goodness of fit test is to test a null hypothesis that all of the categories are equally likely, so we’ll stick to that for our example.</p>
<p>What about our alternative hypothesis, <span class="math inline">\(H_1\)</span>? All we’re really interested in is demonstrating that the probabilities involved aren’t all identical (that is, people’s choices weren’t completely random). As a consequence, the “human friendly” versions of our hypotheses look like this:</p>
<blockquote class="blockquote">
<p><span class="math inline">\(H_0\)</span>: All four suits are chosen with equal probability</p>
<p><span class="math inline">\(H_1\)</span>: At least one of the suit-choice probabilities <em>isn’t</em> .25</p>
</blockquote>
<p>and the “mathematician friendly” version is</p>
<blockquote class="blockquote">
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mathbf{P} = (.25, .25, .25, .25)\)</span></p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mathbf{P} \neq (.25,.25,.25,.25)\)</span></p>
</blockquote>
<p>Conveniently, the mathematical version of the hypotheses looks quite similar to an R command defining a vector. So maybe what I should do is store the <span class="math inline">\(\mathbf{P}\)</span> vector in R as well, since we’re almost certainly going to need it later. And because I’m Mister Imaginative, I’ll call this R vector <code>probabilities</code>,</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>probabilities <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">clubs =</span> .<span class="dv">25</span>, <span class="at">diamonds =</span> .<span class="dv">25</span>, <span class="at">hearts =</span> .<span class="dv">25</span>, <span class="at">spades =</span> .<span class="dv">25</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>probabilities</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   clubs diamonds   hearts   spades 
    0.25     0.25     0.25     0.25 </code></pre>
</div>
</div>
</section>
<section id="the-goodness-of-fit-test-statistic" class="level3" data-number="12.1.3">
<h3 data-number="12.1.3" class="anchored" data-anchor-id="the-goodness-of-fit-test-statistic"><span class="header-section-number">12.1.3</span> The “goodness of fit” test statistic</h3>
<p>At this point, we have our observed frequencies <span class="math inline">\(\mathbf{O}\)</span> and a collection of probabilities <span class="math inline">\(\mathbf{P}\)</span> corresponding to the null hypothesis that we want to test. We’ve stored these in R as the corresponding variables <code>observed</code> and <code>probabilities</code>. What we now want to do is construct a test of the null hypothesis. As always, if we want to test <span class="math inline">\(H_0\)</span> against <span class="math inline">\(H_1\)</span>, we’re going to need a test statistic. The basic trick that a goodness of fit test uses is to construct a test statistic that measures how “close” the data are to the null hypothesis. If the data don’t resemble what you’d “expect” to see if the null hypothesis were true, then it probably isn’t true. Okay, if the null hypothesis were true, what would we expect to see? Or, to use the correct terminology, what are the <strong><em>expected frequencies</em></strong>. There are <span class="math inline">\(N=200\)</span> observations, and (if the null is true) the probability of any one of them choosing a heart is <span class="math inline">\(P_3 = .25\)</span>, so I guess we’re expecting <span class="math inline">\(200 \times .25 = 50\)</span> hearts, right? Or, more specifically, if we let <span class="math inline">\(E_i\)</span> refer to “the number of category <span class="math inline">\(i\)</span> responses that we’re expecting if the null is true”, then <span class="math display">\[
E_i = N \times P_i
\]</span> This is pretty easy to calculate in R:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">200</span>  <span class="co"># sample size</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>expected <span class="ot">&lt;-</span> N <span class="sc">*</span> probabilities <span class="co"># expected frequencies</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>expected</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   clubs diamonds   hearts   spades 
      50       50       50       50 </code></pre>
</div>
</div>
<p>None of which is very surprising: if there are 200 observations that can fall into four categories, and we think that all four categories are equally likely, then on average we’d expect to see 50 observations in each category, right?</p>
<p>Now, how do we translate this into a test statistic? Clearly, what we want to do is compare the <em>expected</em> number of observations in each category (<span class="math inline">\(E_i\)</span>) with the <em>observed</em> number of observations in that category (<span class="math inline">\(O_i\)</span>). And on the basis of this comparison, we ought to be able to come up with a good test statistic. To start with, let’s calculate the difference between what the null hypothesis expected us to find and what we actually did find. That is, we calculate the “observed minus expected” difference score, <span class="math inline">\(O_i - E_i\)</span>. This is illustrated in the following table.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th></th>
<th><span class="math inline">\(\clubsuit\)</span></th>
<th><span class="math inline">\(\diamondsuit\)</span></th>
<th><span class="math inline">\(\heartsuit\)</span></th>
<th><span class="math inline">\(\spadesuit\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>expected frequency</td>
<td><span class="math inline">\(E_i\)</span></td>
<td>50</td>
<td>50</td>
<td>50</td>
<td>50</td>
</tr>
<tr class="even">
<td>observed frequency</td>
<td><span class="math inline">\(O_i\)</span></td>
<td>35</td>
<td>51</td>
<td>64</td>
<td>50</td>
</tr>
<tr class="odd">
<td>difference score</td>
<td><span class="math inline">\(O_i - E_i\)</span></td>
<td>-15</td>
<td>1</td>
<td>14</td>
<td>0</td>
</tr>
</tbody>
</table>
<p>The same calculations can be done in R, using our <code>expected</code> and <code>observed</code> variables:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>observed <span class="sc">-</span> expected</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   clubs diamonds   hearts   spades 
     -15        1       14        0 </code></pre>
</div>
</div>
<p>Regardless of whether we do the calculations by hand or whether we do them in R, it’s clear that people chose more hearts and fewer clubs than the null hypothesis predicted. However, a moment’s thought suggests that these raw differences aren’t quite what we’re looking for. Intuitively, it feels like it’s just as bad when the null hypothesis predicts too few observations (which is what happened with hearts) as it is when it predicts too many (which is what happened with clubs). So it’s a bit weird that we have a negative number for clubs and a positive number for hearts. One easy way to fix this is to square everything, so that we now calculate the squared differences, <span class="math inline">\((E_i - O_i)^2\)</span>. As before, we could do this by hand, but it’s easier to do it in R…</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>(observed <span class="sc">-</span> expected)<span class="sc">^</span><span class="dv">2</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   clubs diamonds   hearts   spades 
     225        1      196        0 </code></pre>
</div>
</div>
<p>Now we’re making progress. What we’ve got now is a collection of numbers that are big whenever the null hypothesis makes a bad prediction (clubs and hearts), but are small whenever it makes a good one (diamonds and spades). Next, for some technical reasons that I’ll explain in a moment, let’s also divide all these numbers by the expected frequency <span class="math inline">\(E_i\)</span>, so we’re actually calculating <span class="math inline">\(\frac{(E_i-O_i)^2}{E_i}\)</span>. Since <span class="math inline">\(E_i = 50\)</span> for all categories in our example, it’s not a very interesting calculation, but let’s do it anyway. The R command becomes:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>(observed <span class="sc">-</span> expected)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> expected</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   clubs diamonds   hearts   spades 
    4.50     0.02     3.92     0.00 </code></pre>
</div>
</div>
<p>In effect, what we’ve got here are four different “error” scores, each one telling us how big a “mistake” the null hypothesis made when we tried to use it to predict our observed frequencies. So, in order to convert this into a useful test statistic, one thing we could do is just add these numbers up. The result is called the <strong><em>goodness of fit</em></strong> statistic, conventionally referred to either as <span class="math inline">\(X^2\)</span> or GOF. We can calculate it using this command in R</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>((observed <span class="sc">-</span> expected)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> expected)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.44</code></pre>
</div>
</div>
<p>The formula for this statistic looks remarkably similar to the R command. If we let <span class="math inline">\(k\)</span> refer to the total number of categories (i.e., <span class="math inline">\(k=4\)</span> for our cards data), then the <span class="math inline">\(X^2\)</span> statistic is given by: <span class="math display">\[
X^2 = \sum_{i=1}^k \frac{(O_i - E_i)^2}{E_i}
\]</span> Intuitively, it’s clear that if <span class="math inline">\(X^2\)</span> is small, then the observed data <span class="math inline">\(O_i\)</span> are very close to what the null hypothesis predicted <span class="math inline">\(E_i\)</span>, so we’re going to need a large <span class="math inline">\(X^2\)</span> statistic in order to reject the null. As we’ve seen from our calculations, in our cards data set we’ve got a value of <span class="math inline">\(X^2 = 8.44\)</span>. So now the question becomes, is this a big enough value to reject the null?</p>
</section>
<section id="the-sampling-distribution-of-the-gof-statistic" class="level3 page-columns page-full" data-number="12.1.4">
<h3 data-number="12.1.4" class="anchored" data-anchor-id="the-sampling-distribution-of-the-gof-statistic"><span class="header-section-number">12.1.4</span> The sampling distribution of the GOF statistic</h3>
<p>To determine whether or not a particular value of <span class="math inline">\(X^2\)</span> is large enough to justify rejecting the null hypothesis, we’re going to need to figure out what the sampling distribution for <span class="math inline">\(X^2\)</span> would be if the null hypothesis were true. So that’s what I’m going to do in this section. I’ll show you in a fair amount of detail how this sampling distribution is constructed, and then – in the next section – use it to build up a hypothesis test. If you want to cut to the chase and are willing to take it on faith that the sampling distribution is a <strong><em>chi-squared (<span class="math inline">\(\chi^2\)</span>) distribution</em></strong> with <span class="math inline">\(k-1\)</span> degrees of freedom, you can skip the rest of this section. However, if you want to understand <em>why</em> the goodness of fit test works the way it does, read on…</p>
<p>Okay, let’s suppose that the null hypothesis is actually true. If so, then the true probability that an observation falls in the <span class="math inline">\(i\)</span>-th category is <span class="math inline">\(P_i\)</span> – after all, that’s pretty much the definition of our null hypothesis. Let’s think about what this actually means. If you think about it, this is kind of like saying that “nature” makes the decision about whether or not the observation ends up in category <span class="math inline">\(i\)</span> by flipping a weighted coin (i.e., one where the probability of getting a head is <span class="math inline">\(P_j\)</span>). And therefore, we can think of our observed frequency <span class="math inline">\(O_i\)</span> by imagining that nature flipped <span class="math inline">\(N\)</span> of these coins (one for each observation in the data set)… and exactly <span class="math inline">\(O_i\)</span> of them came up heads. Obviously, this is a pretty weird way to think about the experiment. But what it does (I hope) is remind you that we’ve actually seen this scenario before. It’s exactly the same set up that gave rise to the binomial distribution in <a href="09-probability.html#sec-binomial" class="quarto-xref"><span>Section 9.4</span></a>. In other words, if the null hypothesis is true, then it follows that our observed frequencies were generated by sampling from a binomial distribution: <span class="math display">\[
O_i \sim \mbox{Binomial}(P_i, N)
\]</span> Now, if you remember from our discussion of the central limit theorem (<a href="10-estimation.html#sec-clt" class="quarto-xref"><span>Section 10.3.3</span></a>), the binomial distribution starts to look pretty much identical to the normal distribution, especially when <span class="math inline">\(N\)</span> is large and when <span class="math inline">\(P_i\)</span> isn’t <em>too</em> close to 0 or 1. In other words as long as <span class="math inline">\(N \times P_i\)</span> is large enough – or, to put it another way, when the expected frequency <span class="math inline">\(E_i\)</span> is large enough – the theoretical distribution of <span class="math inline">\(O_i\)</span> is approximately normal. Better yet, if <span class="math inline">\(O_i\)</span> is normally distributed, then so is <span class="math inline">\((O_i - E_i)/\sqrt{E_i}\)</span> … since <span class="math inline">\(E_i\)</span> is a fixed value, subtracting off <span class="math inline">\(E_i\)</span> and dividing by <span class="math inline">\(\sqrt{E_i}\)</span> changes the mean and standard deviation of the normal distribution; but that’s all it does. Okay, so now let’s have a look at what our goodness of fit statistic actually <em>is</em>. What we’re doing is taking a bunch of things that are normally-distributed, squaring them, and adding them up. Wait. We’ve seen that before too! As we discussed in <a href="09-probability.html#sec-otherdists" class="quarto-xref"><span>Section 9.6</span></a>, when you take a bunch of things that have a standard normal distribution (i.e., mean 0 and standard deviation 1), square them, then add them up, then the resulting quantity has a chi-square distribution. So now we know that the null hypothesis predicts that the sampling distribution of the goodness of fit statistic is a chi-square distribution. Cool.</p>
<p>There’s one last detail to talk about, namely the degrees of freedom. If you remember back to <a href="09-probability.html#sec-otherdists" class="quarto-xref"><span>Section 9.6</span></a>, I said that if the number of things you’re adding up is <span class="math inline">\(k\)</span>, then the degrees of freedom for the resulting chi-square distribution is <span class="math inline">\(k\)</span>. Yet, what I said at the start of this section is that the actual degrees of freedom for the chi-square goodness of fit test is <span class="math inline">\(k-1\)</span>. What’s up with that? The answer here is that what we’re supposed to be looking at is the number of genuinely <em>independent</em> things that are getting added together. And, as I’ll go on to talk about in the next section, even though there’s <span class="math inline">\(k\)</span> things that we’re adding, only <span class="math inline">\(k-1\)</span> of them are truly independent; and so the degrees of freedom is actually only <span class="math inline">\(k-1\)</span>. That’s the topic of the next section.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn1"><p><sup>1</sup>&nbsp;I should point out that this issue does complicate the story somewhat: I’m not going to cover it in this book, but there’s a sneaky trick that you can do to rewrite the equation for the goodness of fit statistic as a sum over <span class="math inline">\(k-1\)</span> independent things. When we do so we get the “proper” sampling distribution, which is chi-square with <span class="math inline">\(k-1\)</span> degrees of freedom. In fact, in order to get the maths to work out properly, you actually have to rewrite things that way. But it’s beyond the scope of an introductory book to show the maths in that much detail: all I wanted to do is give you a sense of why the goodness of fit statistic is associated with the chi-squared distribution.</p></div></div></section>
<section id="degrees-of-freedom" class="level3 page-columns page-full" data-number="12.1.5">
<h3 data-number="12.1.5" class="anchored" data-anchor-id="degrees-of-freedom"><span class="header-section-number">12.1.5</span> Degrees of freedom</h3>
<div class="cell" data-scratch="true">
<div class="cell-output-display">
<div id="fig-manychi" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-manychi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="12-chisquare_files/figure-html/fig-manychi-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-manychi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.1: Chi-square distributions with different values for the “degrees of freedom”.
</figcaption>
</figure>
</div>
</div>
</div>
<p>When I introduced the chi-square distribution in <a href="09-probability.html#sec-otherdists" class="quarto-xref"><span>Section 9.6</span></a>, I was a bit vague about what “<strong><em>degrees of freedom</em></strong>” actually <em>means</em>. Obviously, it matters: looking at <a href="#fig-manychi" class="quarto-xref">Figure&nbsp;<span>12.1</span></a> you can see that if we change the degrees of freedom, then the chi-square distribution changes shape quite substantially. But what exactly <em>is</em> it? Again, when I introduced the distribution and explained its relationship to the normal distribution, I did offer an answer… it’s the number of “normally distributed variables” that I’m squaring and adding together. But, for most people, that’s kind of abstract, and not entirely helpful. What we really need to do is try to understand degrees of freedom in terms of our data. So here goes.</p>
<p>The basic idea behind degrees of freedom is quite simple: you calculate it by counting up the number of distinct “quantities” that are used to describe your data; and then subtracting off all of the “constraints” that those data must satisfy.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> This is a bit vague, so let’s use our cards data as a concrete example. We describe our data using four numbers, <span class="math inline">\(O_1\)</span>, <span class="math inline">\(O_2\)</span>, <span class="math inline">\(O_3\)</span> and <span class="math inline">\(O_4\)</span> corresponding to the observed frequencies of the four different categories (hearts, clubs, diamonds, spades). These four numbers are the <em>random outcomes</em> of our experiment. But, my experiment actually has a fixed constraint built into it: the sample size <span class="math inline">\(N\)</span>.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> That is, if we know how many people chose hearts, how many chose diamonds and how many chose clubs; then we’d be able to figure out exactly how many chose spades. In other words, although our data are described using four numbers, they only actually correspond to <span class="math inline">\(4-1 = 3\)</span> degrees of freedom. A slightly different way of thinking about it is to notice that there are four <em>observed</em> frequencies, but they have to sum to our fixed sample size <span class="math inline">\(N\)</span>, so there’s only three genuinely free numbers. In general, then, the degrees of freedom associated with a goodness of fit test is <span class="math inline">\(k-1\)</span>, where <span class="math inline">\(k\)</span> is the number of categories.</p>
<div class="no-row-height column-margin column-container"><div id="fn2"><p><sup>2</sup>&nbsp;I feel obliged to point out that this is an over-simplification. It works nicely for quite a few situations; but every now and then we’ll come across degrees of freedom values that aren’t whole numbers. Don’t let this worry you too much – when you come across this, just remind yourself that “degrees of freedom” is actually a bit of a messy concept, and that the nice simple story that I’m telling you here isn’t the whole story. For an introductory class, it’s usually best to stick to the simple story: but I figure it’s best to warn you to expect this simple story to fall apart. If I didn’t give you this warning, you might start getting confused when you see <span class="math inline">\(df = 3.4\)</span> or something; and (incorrectly) thinking that you had misunderstood something that I’ve taught you, rather than (correctly) realising that there’s something that I haven’t told you.</p></div><div id="fn3"><p><sup>3</sup>&nbsp;In practice, the sample size isn’t always fixed… e.g., we might run the experiment over a fixed period of time, and the number of people participating depends on how many people show up. That doesn’t matter for the current purposes.</p></div></div></section>
<section id="testing-the-null-hypothesis" class="level3" data-number="12.1.6">
<h3 data-number="12.1.6" class="anchored" data-anchor-id="testing-the-null-hypothesis"><span class="header-section-number">12.1.6</span> Testing the null hypothesis</h3>
<div class="cell" data-scratch="true">
<div class="cell-output-display">
<div id="fig-goftest" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-goftest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="12-chisquare_files/figure-html/fig-goftest-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-goftest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.2: Illustration of how the hypothesis testing works for the chi-square goodness of fit test.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The final step in the process of constructing our hypothesis test is to figure out what the rejection region is. That is, what values of <span class="math inline">\(X^2\)</span> would lead us to reject the null hypothesis. As we saw earlier, large values of <span class="math inline">\(X^2\)</span> imply that the null hypothesis has done a poor job of predicting the data from our experiment, whereas small values of <span class="math inline">\(X^2\)</span> imply that it’s actually done pretty well. Therefore, a pretty sensible strategy would be to say there is some critical value, such that if <span class="math inline">\(X^2\)</span> is bigger than the critical value we reject the null; but if <span class="math inline">\(X^2\)</span> is smaller than this value we retain the null. In other words, to use the language we introduced in <a href="./11-hypothesistesting.html">Hypothesis testing</a> the chi-squared goodness of fit test is always a <strong><em>one-sided test</em></strong>. Right, so all we have to do is figure out what this critical value is. And it’s pretty straightforward. If we want our test to have significance level of <span class="math inline">\(\alpha = .05\)</span> (that is, we are willing to tolerate a Type I error rate of 5%), then we have to choose our critical value so that there is only a 5% chance that <span class="math inline">\(X^2\)</span> could get to be that big if the null hypothesis is true. That is to say, we want the 95th percentile of the sampling distribution. This is illustrated in <a href="#fig-goftest" class="quarto-xref">Figure&nbsp;<span>12.2</span></a>.</p>
<p>Ah, but – I hear you ask – how do I calculate the 95th percentile of a chi-squared distribution with <span class="math inline">\(k-1\)</span> degrees of freedom? If only R had some function, called… oh, I don’t know, <code>qchisq()</code> … that would let you calculate this percentile (see <a href="./09-probability.html">Introduction to probability</a> if you’ve forgotten). Like this…</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qchisq</span>(<span class="at">p =</span> .<span class="dv">95</span>, <span class="at">df =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.814728</code></pre>
</div>
</div>
<p>So if our <span class="math inline">\(X^2\)</span> statistic is bigger than 7.81 or so, then we can reject the null hypothesis. Since we actually calculated that before (i.e., <span class="math inline">\(X^2 = 8.44\)</span>) we can reject the null. If we want an exact <span class="math inline">\(p\)</span>-value, we can calculate it using the <code>pchisq()</code> function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="at">q =</span> <span class="fl">8.44</span>, <span class="at">df =</span> <span class="dv">3</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03774185</code></pre>
</div>
</div>
<p>This is hopefully pretty straightforward, as long as you recall that the “<code>p</code>” form of the probability distribution functions in R always calculates the probability of getting a value of <em>less</em> than the value you entered (in this case 8.44). We want the opposite: the probability of getting a value of 8.44 or <em>more</em>. That’s why I told R to use the upper tail, not the lower tail. That said, it’s usually easier to calculate the <span class="math inline">\(p\)</span>-value this way:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(<span class="at">q =</span> <span class="fl">8.44</span>, <span class="at">df =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03774185</code></pre>
</div>
</div>
<p>So, in this case we would reject the null hypothesis, since <span class="math inline">\(p &lt; .05\)</span>. And that’s it, basically. You now know “Pearson’s <span class="math inline">\(\chi^2\)</span> test for the goodness of fit”. Lucky you.</p>
</section>
<section id="sec-goftestinr" class="level3" data-number="12.1.7">
<h3 data-number="12.1.7" class="anchored" data-anchor-id="sec-goftestinr"><span class="header-section-number">12.1.7</span> Doing the test in R</h3>
<p>Gosh darn it. Although we did manage to do everything in R as we were going through that little example, it does rather feel as if we’re typing too many things into the magic computing box. And I <em>hate</em> typing. Not surprisingly, R provides a function that will do all of these calculations for you. In fact, there are several different ways of doing it. The one that most people use is the <code>chisq.test()</code> function, which comes with every installation of R. I’ll show you how to use the <code>chisq.test()</code> function later on (in <a href="#sec-chisqtest" class="quarto-xref"><span>Section 12.6</span></a>), but to start out with I’m going to show you the <code>goodnessOfFitTest()</code> function in the <code>lsr</code> package, because it produces output that I think is easier for beginners to understand. It’s pretty straightforward: our raw data are stored in the variable <code>cards$choice_1</code>, right? If you want to test the null hypothesis that all four suits are equally likely, then (assuming you have the <code>lsr</code> package loaded) all you have to do is type this:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">goodnessOfFitTest</span>(cards<span class="sc">$</span>choice_1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Chi-square test against specified probabilities

Data variable:   cards$choice_1 

Hypotheses: 
   null:        true probabilities are as specified
   alternative: true probabilities differ from those specified

Descriptives: 
         observed freq. expected freq. specified prob.
clubs                35             50            0.25
diamonds             51             50            0.25
hearts               64             50            0.25
spades               50             50            0.25

Test results: 
   X-squared statistic:  8.44 
   degrees of freedom:  3 
   p-value:  0.038 </code></pre>
</div>
</div>
<p>R then runs the test, and prints several lines of text. I’ll go through the output line by line, so that you can make sure that you understand what you’re looking at. The first two lines are just telling you things you already know: they tell us what kind of hypothesis test we ran, and the name of the variable that we ran it on. After that comes a statement of what the null and alternative hypotheses are. For a beginner, it’s kind of handy to have this as part of the output: it’s a nice reminder of what your null and alternative hypotheses are. Don’t get used to seeing this though. The vast majority of hypothesis tests in R aren’t so kind to novices. Most R functions are written on the assumption that you already understand the statistical tool that you’re using, so they don’t bother to include an explicit statement of the null and alternative hypothesis. The only reason that <code>goodnessOfFitTest()</code> actually does give you this is that I wrote it with novices in mind.</p>
<p>The next part of the output shows you the comparison between the observed frequencies and the expected frequencies. The first column shows what the observed frequencies were, the second column shows the expected frequencies according to the null hypothesis, and the third column shows you what the probabilities actually were according to the null. For novice users, I think this is helpful: you can look at this part of the output and check that it makes sense: if it doesn’t you might have typed something incorrectly.</p>
<p>The last part of the output is the “important” stuff: it’s the result of the hypothesis test itself. There are three key numbers that need to be reported: the value of the <span class="math inline">\(X^2\)</span> statistic, the degrees of freedom, and the <span class="math inline">\(p\)</span>-value. Notice that these are the same numbers that we came up with when doing the calculations the long way.</p>
</section>
<section id="specifying-a-different-null-hypothesis" class="level3" data-number="12.1.8">
<h3 data-number="12.1.8" class="anchored" data-anchor-id="specifying-a-different-null-hypothesis"><span class="header-section-number">12.1.8</span> Specifying a different null hypothesis</h3>
<p>At this point you might be wondering what to do if you want to run a goodness of fit test, but your null hypothesis is <em>not</em> that all categories are equally likely. For instance, let’s suppose that someone had made the theoretical prediction that people should choose red cards 60% of the time, and black cards 40% of the time (I’ve no idea why you’d predict that), but had no other preferences. If that were the case, the null hypothesis would be to expect 30% of the choices to be hearts, 30% to be diamonds, 20% to be spades and 20% to be clubs. This seems like a silly theory to me, and it’s pretty easy to test it using our data. All we need to do is specify the probabilities associated with the null hypothesis. We create a vector like this:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>null_probs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">clubs =</span> .<span class="dv">2</span>, <span class="at">diamonds =</span> .<span class="dv">3</span>, <span class="at">hearts =</span> .<span class="dv">3</span>, <span class="at">spades =</span> .<span class="dv">2</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>null_probs</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   clubs diamonds   hearts   spades 
     0.2      0.3      0.3      0.2 </code></pre>
</div>
</div>
<p>Now that we have an explicitly specified null hypothesis, we include it in our command. This time round I’ll use the argument names properly. The data variable corresponds to the argument <code>x</code>, and the probabilities according to the null hypothesis correspond to the argument <code>p</code>. So our command is:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">goodnessOfFitTest</span>(<span class="at">x =</span> cards<span class="sc">$</span>choice_1, <span class="at">p =</span> null_probs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Chi-square test against specified probabilities

Data variable:   cards$choice_1 

Hypotheses: 
   null:        true probabilities are as specified
   alternative: true probabilities differ from those specified

Descriptives: 
         observed freq. expected freq. specified prob.
clubs                35             40             0.2
diamonds             51             60             0.3
hearts               64             60             0.3
spades               50             40             0.2

Test results: 
   X-squared statistic:  4.742 
   degrees of freedom:  3 
   p-value:  0.192 </code></pre>
</div>
</div>
<p>As you can see the null hypothesis and the expected frequencies are different to what they were last time. As a consequence our <span class="math inline">\(X^2\)</span> test statistic is different, and our <span class="math inline">\(p\)</span>-value is different too. Annoyingly, the <span class="math inline">\(p\)</span>-value is .192, so we can’t reject the null hypothesis. Sadly, despite the fact that the null hypothesis corresponds to a very silly theory, these data don’t provide enough evidence against it.</p>
</section>
<section id="sec-chisqreport" class="level3 page-columns page-full" data-number="12.1.9">
<h3 data-number="12.1.9" class="anchored" data-anchor-id="sec-chisqreport"><span class="header-section-number">12.1.9</span> How to report the results of the test</h3>
<p>So now you know how the test works, and you know how to do the test using a wonderful magic computing box. The next thing you need to know is how to write up the results. After all, there’s no point in designing and running an experiment and then analysing the data if you don’t tell anyone about it! So let’s now talk about what you need to do when reporting your analysis. Let’s stick with our card-suits example. If I wanted to write this result up for a paper or something, the conventional way to report this would be to write something like this:</p>
<blockquote class="blockquote">
<p>Of the 200 participants in the experiment, 64 selected hearts for their first choice, 51 selected diamonds, 50 selected spades, and 35 selected clubs. A chi-square goodness of fit test was conducted to test whether the choice probabilities were identical for all four suits. The results were significant (<span class="math inline">\(\chi^2(3) = 8.44, p&lt;.05\)</span>), suggesting that people did not select suits purely at random.</p>
</blockquote>
<p>This is pretty straightforward, and hopefully it seems pretty unremarkable. That said, there’s a few things that you should note about this description:</p>
<ul>
<li><em>The statistical test is preceded by the descriptive statistics</em>. That is, I told the reader something about what the data look like before going on to do the test. In general, this is good practice: always remember that your reader doesn’t know your data anywhere near as well as you do. So unless you describe it to them properly, the statistical tests won’t make any sense to them, and they’ll get frustrated and cry.</li>
<li><em>The description tells you what the null hypothesis being tested is</em>. To be honest, writers don’t always do this, but it’s often a good idea in those situations where some ambiguity exists; or when you can’t rely on your readership being intimately familiar with the statistical tools that you’re using. Quite often the reader might not know (or remember) all the details of the test that you’re using, so it’s a kind of politeness to “remind” them! As far as the goodness of fit test goes, you can usually rely on a scientific audience knowing how it works (since it’s covered in most intro stats classes). However, it’s still a good idea to be explicit about stating the null hypothesis (briefly!) because the null hypothesis can be different depending on what you’re using the test for. For instance, in the cards example my null hypothesis was that all the four suit probabilities were identical (i.e., <span class="math inline">\(P_1 = P_2 = P_3 = P_4 = 0.25\)</span>), but there’s nothing special about that hypothesis. I could just as easily have tested the null hypothesis that <span class="math inline">\(P_1 = 0.7\)</span> and <span class="math inline">\(P_2 = P_3 = P_4 = 0.1\)</span> using a goodness of fit test. So it’s helpful to the reader if you explain to them what your null hypothesis was. Also, notice that I described the null hypothesis in words, not in maths. That’s perfectly acceptable. You can describe it in maths if you like, but since most readers find words easier to read than symbols, most writers tend to describe the null using words if they can.</li>
<li><em>A “stat block” is included</em>. When reporting the results of the test itself, I didn’t just say that the result was significant, I included a “stat block” (i.e., the dense mathematical-looking part in the parentheses), which reports all the “raw” statistical data. For the chi-square goodness of fit test, the information that gets reported is the test statistic (that the goodness of fit statistic was 8.44), the information about the distribution used in the test (<span class="math inline">\(\chi^2\)</span> with 3 degrees of freedom, which is usually shortened to <span class="math inline">\(\chi^2(3)\)</span>), and then the information about whether the result was significant (in this case <span class="math inline">\(p&lt;.05\)</span>). The particular information that needs to go into the stat block is different for every test, and so each time I introduce a new test I’ll show you what the stat block should look like.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> However the general principle is that you should always provide enough information so that the reader could check the test results themselves if they really wanted to.</li>
<li><em>The results are interpreted</em>. In addition to indicating that the result was significant, I provided an interpretation of the result (i.e., that people didn’t choose randomly). This is also a kindness to the reader, because it tells them something about what they should believe about what’s going on in your data. If you don’t include something like this, it’s really hard for your reader to understand what’s going on.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></li>
</ul>
<div class="no-row-height column-margin column-container"><div id="fn4"><p><sup>4</sup>&nbsp;Well, sort of. The conventions for how statistics should be reported tend to differ somewhat from discipline to discipline; I’ve tended to stick with how things are done in psychology, since that’s what I do. But the general principle of providing enough information to the reader to allow them to check your results is pretty universal, I think.</p></div><div id="fn5"><p><sup>5</sup>&nbsp;To some people, this advice might sound odd, or at least in conflict with the “usual” advice on how to write a technical report. Very typically, students are told that the “results” section of a report is for describing the data and reporting statistical analysis; and the “discussion” section is for providing interpretation. That’s true as far as it goes, but I think people often interpret it way too literally. The way I usually approach it is to provide a quick and simple interpretation of the data in the results section, so that my reader understands what the data are telling us. Then, in the discussion, I try to tell a bigger story; about how my results fit with the rest of the scientific literature. In short; don’t let the “interpretation goes in the discussion” advice turn your results section into incomprehensible garbage. Being understood by your reader is <em>much</em> more important.</p></div></div><p>As with everything else, your overriding concern should be that you <em>explain</em> things to your reader. Always remember that the point of reporting your results is to communicate to another human being. I cannot tell you just how many times I’ve seen the results section of a report or a thesis or even a scientific article that is just gibberish, because the writer has focused solely on making sure they’ve included all the numbers, and forgotten to actually communicate with the human reader.</p>
</section>
<section id="a-comment-on-statistical-notation" class="level3 page-columns page-full" data-number="12.1.10">
<h3 data-number="12.1.10" class="anchored" data-anchor-id="a-comment-on-statistical-notation"><span class="header-section-number">12.1.10</span> A comment on statistical notation</h3>
<div class="pullquote">
<p><em>Satan delights equally in statistics and in quoting scripture</em></p>
<p>— H.G. Wells</p>
</div>
<p>If you’ve been reading very closely, and are as much of a mathematical pedant as I am, there is one thing about the way I wrote up the chi-square test in the last section that might be bugging you a little bit. There’s something that feels a bit wrong with writing “<span class="math inline">\(\chi^2(3) = 8.44\)</span>”, you might be thinking. After all, it’s the goodness of fit statistic that is equal to 8.44, so shouldn’t I have written <span class="math inline">\(X^2 = 8.44\)</span> or maybe GOF<span class="math inline">\(=8.44\)</span>? This seems to be conflating the <em>sampling distribution</em> (i.e., <span class="math inline">\(\chi^2\)</span> with <span class="math inline">\(df = 3\)</span>) with the <em>test statistic</em> (i.e., <span class="math inline">\(X^2\)</span>). Odds are you figured it was a typo, since <span class="math inline">\(\chi\)</span> and <span class="math inline">\(X\)</span> look pretty similar. Oddly, it’s not. Writing <span class="math inline">\(\chi^2(3) = 8.44\)</span> is essentially a highly condensed way of writing “the sampling distribution of the test statistic is <span class="math inline">\(\chi^2(3)\)</span>, and the value of the test statistic is 8.44”.</p>
<p>In one sense, this is kind of stupid. There are <em>lots</em> of different test statistics out there that turn out to have a chi-square sampling distribution: the <span class="math inline">\(X^2\)</span> statistic that we’ve used for our goodness of fit test is only one of many (albeit one of the most commonly encountered ones). In a sensible, perfectly organised world, we’d <em>always</em> have a separate name for the test statistic and the sampling distribution: that way, the stat block itself would tell you exactly what it was that the researcher had calculated. Sometimes this happens. For instance, the test statistic used in the Pearson goodness of fit test is written <span class="math inline">\(X^2\)</span>; but there’s a closely related test known as the <span class="math inline">\(G\)</span>-test<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> <span class="citation" data-cites="Sokal1994">(<a href="references.html#ref-Sokal1994" role="doc-biblioref">Sokal &amp; Rohlf, 1994</a>)</span>, in which the test statistic is written as <span class="math inline">\(G\)</span>. As it happens, the Pearson goodness of fit test and the <span class="math inline">\(G\)</span>-test both test the same null hypothesis; and the sampling distribution is exactly the same (i.e., chi-square with <span class="math inline">\(k-1\)</span> degrees of freedom). If I’d done a <span class="math inline">\(G\)</span>-test for the cards data rather than a goodness of fit test, then I’d have ended up with a test statistic of <span class="math inline">\(G = 8.65\)</span>, which is slightly different from the <span class="math inline">\(X^2 = 8.44\)</span> value that I got earlier; and produces a slightly smaller <span class="math inline">\(p\)</span>-value of <span class="math inline">\(p = .034\)</span>. Suppose that the convention was to report the test statistic, then the sampling distribution, and then the <span class="math inline">\(p\)</span>-value. If that were true, then these two situations would produce different stat blocks: my original result would be written <span class="math inline">\(X^2 = 8.44, \chi^2(3), p = .038\)</span>, whereas the new version using the <span class="math inline">\(G\)</span>-test would be written as <span class="math inline">\(G = 8.65, \chi^2(3), p = .034\)</span>. However, using the condensed reporting standard, the original result is written <span class="math inline">\(\chi^2(3) = 8.44, p = .038\)</span>, and the new one is written <span class="math inline">\(\chi^2(3) = 8.65, p = .034\)</span>, and it’s actually unclear whether these both refer to the same test or not.</p>
<div class="no-row-height column-margin column-container"><div id="fn6"><p><sup>6</sup>&nbsp;Complicating matters, the <span class="math inline">\(G\)</span>-test is a special case of a whole class of tests that are known as <em>likelihood ratio tests</em>. I don’t cover LRTs in this book, but they are quite handy things to know about.</p></div></div><p>So why don’t we live in a world in which the contents of the stat block uniquely specifies what tests were run? The deep reason is that life is messy. We (as users of statistical tools) want it to be nice and neat and organised… we want it to be <em>designed</em>, as if it were a product. But that’s not how life works: statistics is an intellectual discipline just as much as any other one, and as such it’s a massively distributed, partly-collaborative and partly-competitive project that no-one really understands completely. The things that you and I use as data analysis tools weren’t created by an Act of the Gods of Statistics; they were invented by lots of different people, published as papers in academic journals, implemented, corrected and modified by lots of other people, and then explained to students in textbooks by someone else. As a consequence, there’s a <em>lot</em> of test statistics that don’t even have names; and as a consequence they’re just given the same name as the corresponding sampling distribution. As we’ll see later, any test statistic that follows a <span class="math inline">\(\chi^2\)</span> distribution is commonly called a “chi-square statistic”; anything that follows a <span class="math inline">\(t\)</span>-distribution is called a “<span class="math inline">\(t\)</span>-statistic” and so on. But, as the <span class="math inline">\(X^2\)</span> versus <span class="math inline">\(G\)</span> example illustrates, two different things with the same sampling distribution are still, well, different.</p>
<p>As a consequence, it’s sometimes a good idea to be clear about what the actual test was that you ran, especially if you’re doing something unusual. If you just say “chi-square test”, it’s not actually clear what test you’re talking about. Although, since the two most common chi-square tests are the goodness of fit test and the independence test (<a href="#sec-chisqindependence" class="quarto-xref"><span>Section 12.2</span></a>), most readers with stats training can probably guess. Nevertheless, it’s something to be aware of.</p>
</section>
</section>
<section id="sec-chisqindependence" class="level2 page-columns page-full" data-number="12.2">
<h2 data-number="12.2" class="anchored" data-anchor-id="sec-chisqindependence"><span class="header-section-number">12.2</span> The <span class="math inline">\(\chi^2\)</span> test of independence (or association)</h2>
<div class="pullquote">
<p>GUARDBOT 1: Halt!<br>
GUARDBOT 2: Be you robot or human?<br>
LEELA (nervously): Robot… we be.<br>
FRY (nervously): Uh, yup! Just two robots out roboting it up! Eh?<br>
GUARDBOT 1 (suspiciously): Administer the test.<br>
GUARDBOT 2: Which of the following would you most prefer? A: A puppy, B: A pretty flower from your sweetie, or C: A large properly-formatted data file?<br>
GUARDBOT 1: Choose!</p>
<p>— Futurama, “Fear of a Bot Planet”</p>
</div>
<p>The other day I was watching an animated documentary examining the quaint customs of the natives of the planet <em>Chapek 9</em>. Apparently, in order to gain access to their capital city, a visitor must prove that they’re a robot, not a human. In order to determine whether or not a visitor is human, they ask whether the visitor prefers puppies, flowers or large, properly formatted data files. “Pretty clever,” I thought to myself “but what if humans and robots have the same preferences? That probably wouldn’t be a very good test then, would it?” As it happens, I got my hands on the testing data that the civil authorities of <em>Chapek 9</em> used to check this. It turns out that what they did was very simple… they found a bunch of robots and a bunch of humans and asked them what they preferred. I saved their data in a file called <code>chapek9.Rdata</code>, which I can now load and have a quick look at:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/chapek9.Rdata"</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">who</span>(<span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   -- Name --   -- Class --   -- Size --
   chapek9      data.frame    180 x 2   
    $species    factor        180       
    $choice     factor        180       </code></pre>
</div>
</div>
<p>Okay, so we have a single data frame called <code>chapek9</code>, which contains two factors, <code>species</code> and <code>choice</code>. As always, it’s nice to have a quick look at the data,</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(chapek9)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  species choice
1   robot flower
2   human   data
3   human   data
4   human   data
5   robot   data
6   human flower</code></pre>
</div>
</div>
<p>and then take a <code>summary()</code>,</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(chapek9)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  species      choice   
 robot:87   puppy : 28  
 human:93   flower: 43  
            data  :109  </code></pre>
</div>
</div>
<p>In total there are 180 entries in the data frame, one for each person (counting both robots and humans as “people”) who was asked to make a choice. Specifically, there’s 93 humans and 87 robots; and overwhelmingly the preferred choice is the data file. However, these summaries don’t address the question we’re interested in. To do that, we need a more detailed description of the data. What we want to do is look at the <code>choices</code> broken down <em>by</em> <code>species</code>. That is, we need to cross-tabulate the data (see <a href="07-datahandling.html#sec-freqtables" class="quarto-xref"><span>Section 7.1</span></a>). There’s quite a few ways to do this, as we’ve seen, but since our data are stored in a data frame, it’s convenient to use the <code>xtabs()</code> function.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>chapek_frequencies <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(<span class="sc">~</span> choice <span class="sc">+</span> species, <span class="at">data =</span> chapek9)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>chapek_frequencies</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        species
choice   robot human
  puppy     13    15
  flower    30    13
  data      44    65</code></pre>
</div>
</div>
<p>That’s more or less what we’re after. So, if we add the row and column totals (which is convenient for the purposes of explaining the statistical tests), we would have a table like this,</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Robot</th>
<th>Human</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Puppy</td>
<td>13</td>
<td>15</td>
<td>28</td>
</tr>
<tr class="even">
<td>Flower</td>
<td>30</td>
<td>13</td>
<td>43</td>
</tr>
<tr class="odd">
<td>Data file</td>
<td>44</td>
<td>65</td>
<td>109</td>
</tr>
<tr class="even">
<td>Total</td>
<td>87</td>
<td>93</td>
<td>180</td>
</tr>
</tbody>
</table>
<p>which actually would be a nice way to report the descriptive statistics for this data set. In any case, it’s quite clear that the vast majority of the humans chose the data file, whereas the robots tended to be a lot more even in their preferences. Leaving aside the question of <em>why</em> the humans might be more likely to choose the data file for the moment (which does seem quite odd, admittedly), our first order of business is to determine if the discrepancy between human choices and robot choices in the data set is statistically significant.</p>
<section id="constructing-our-hypothesis-test" class="level3 page-columns page-full" data-number="12.2.1">
<h3 data-number="12.2.1" class="anchored" data-anchor-id="constructing-our-hypothesis-test"><span class="header-section-number">12.2.1</span> Constructing our hypothesis test</h3>
<p>How do we analyse this data? Specifically, since my <em>research</em> hypothesis is that “humans and robots answer the question in different ways”, how can I construct a test of the <em>null</em> hypothesis that “humans and robots answer the question the same way”? As before, we begin by establishing some notation to describe the data:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Robot</th>
<th>Human</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Puppy</td>
<td><span class="math inline">\(O_{11}\)</span></td>
<td><span class="math inline">\(O_{12}\)</span></td>
<td><span class="math inline">\(R_{1}\)</span></td>
</tr>
<tr class="even">
<td>Flower</td>
<td><span class="math inline">\(O_{21}\)</span></td>
<td><span class="math inline">\(O_{22}\)</span></td>
<td><span class="math inline">\(R_{2}\)</span></td>
</tr>
<tr class="odd">
<td>Data file</td>
<td><span class="math inline">\(O_{31}\)</span></td>
<td><span class="math inline">\(O_{32}\)</span></td>
<td><span class="math inline">\(R_{3}\)</span></td>
</tr>
<tr class="even">
<td>Total</td>
<td><span class="math inline">\(C_{1}\)</span></td>
<td><span class="math inline">\(C_{2}\)</span></td>
<td><span class="math inline">\(N\)</span></td>
</tr>
</tbody>
</table>
<p>In this notation we say that <span class="math inline">\(O_{ij}\)</span> is a count (observed frequency) of the number of respondents that are of species <span class="math inline">\(j\)</span> (robots or human) who gave answer <span class="math inline">\(i\)</span> (puppy, flower or data) when asked to make a choice. The total number of observations is written <span class="math inline">\(N\)</span>, as usual. Finally, I’ve used <span class="math inline">\(R_i\)</span> to denote the row totals (e.g., <span class="math inline">\(R_1\)</span> is the total number of people who chose the flower), and <span class="math inline">\(C_j\)</span> to denote the column totals (e.g., <span class="math inline">\(C_1\)</span> is the total number of robots).<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn7"><p><sup>7</sup>&nbsp;A technical note. The way I’ve described the test pretends that the column totals are fixed (i.e., the researcher intended to survey 87 robots and 93 humans) and the row totals are random (i.e., it just turned out that 28 people chose the puppy). To use the terminology from my mathematical statistics textbook <span class="citation" data-cites="Hogg2005">(<a href="references.html#ref-Hogg2005" role="doc-biblioref">Hogg et al., 2005</a>)</span> I should technically refer to this situation as a chi-square test of homogeneity; and reserve the term chi-square test of independence for the situation where both the row and column totals are random outcomes of the experiment. In the initial drafts of this book that’s exactly what I did. However, it turns out that these two tests are identical; and so I’ve collapsed them together.</p></div></div><p>So now let’s think about what the null hypothesis says. If robots and humans are responding in the same way to the question, it means that the probability that “a robot says puppy” is the same as the probability that “a human says puppy”, and so on for the other two possibilities. So, if we use <span class="math inline">\(P_{ij}\)</span> to denote “the probability that a member of species <span class="math inline">\(j\)</span> gives response <span class="math inline">\(i\)</span>” then our null hypothesis is that:</p>
<blockquote class="blockquote">
<p><span class="math inline">\(H_0\)</span>: All of the following are true: <span class="math inline">\(P_{11} = P_{12}\)</span> (same probability of saying “puppy”), <span class="math inline">\(P_{21} = P_{22}\)</span> (same probability of saying “flower”), and <span class="math inline">\(P_{31} = P_{32}\)</span> (same probability of saying “data”).</p>
</blockquote>
<p>And actually, since the null hypothesis is claiming that the true choice probabilities don’t depend on the species of the person making the choice, we can let <span class="math inline">\(P_i\)</span> refer to this probability: e.g., <span class="math inline">\(P_1\)</span> is the true probability of choosing the puppy.</p>
<p>Next, in much the same way that we did with the goodness of fit test, what we need to do is calculate the expected frequencies. That is, for each of the observed counts <span class="math inline">\(O_{ij}\)</span>, we need to figure out what the null hypothesis would tell us to expect. Let’s denote this expected frequency by <span class="math inline">\(E_{ij}\)</span>. This time, it’s a little bit trickier. If there are a total of <span class="math inline">\(C_j\)</span> people that belong to species <span class="math inline">\(j\)</span>, and the true probability of anyone (regardless of species) choosing option <span class="math inline">\(i\)</span> is <span class="math inline">\(P_i\)</span>, then the expected frequency is just: <span class="math display">\[
E_{ij} = C_j \times P_i
\]</span> Now, this is all very well and good, but we have a problem. Unlike the situation we had with the goodness of fit test, the null hypothesis doesn’t actually specify a particular value for <span class="math inline">\(P_i\)</span>. It’s something we have to estimate (<a href="./10-estimation.html">Estimating unknown quantities from a sample</a>) from the data! Fortunately, this is pretty easy to do. If 28 out of 180 people selected the flowers, then a natural estimate for the probability of choosing flowers is <span class="math inline">\(28/180\)</span>, which is approximately <span class="math inline">\(.16\)</span>. If we phrase this in mathematical terms, what we’re saying is that our estimate for the probability of choosing option <span class="math inline">\(i\)</span> is just the row total divided by the total sample size: <span class="math display">\[
\hat{P}_i = \frac{R_i}{N}
\]</span> Therefore, our expected frequency can be written as the product (i.e., multiplication) of the row total and the column total, divided by the total number of observations:<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> <span class="math display">\[
E_{ij} = \frac{R_i \times C_j}{N}
\]</span> Now that we’ve figured out how to calculate the expected frequencies, it’s straightforward to define a test statistic; following the exact same strategy that we used in the goodness of fit test. In fact, it’s pretty much the <em>same</em> statistic. For a contingency table with <span class="math inline">\(r\)</span> rows and <span class="math inline">\(c\)</span> columns, the equation that defines our <span class="math inline">\(X^2\)</span> statistic is <span class="math display">\[
X^2 = \sum_{i=1}^r\sum_{j=1}^c \frac{({E}_{ij} - O_{ij})^2}{{E}_{ij}}
\]</span> The only difference is that I have to include two summation signs (i.e., <span class="math inline">\(\sum\)</span>) to indicate that we’re summing over both rows and columns. As before, large values of <span class="math inline">\(X^2\)</span> indicate that the null hypothesis provides a poor description of the data, whereas small values of <span class="math inline">\(X^2\)</span> suggest that it does a good job of accounting for the data. Therefore, just like last time, we want to reject the null hypothesis if <span class="math inline">\(X^2\)</span> is too large.</p>
<div class="no-row-height column-margin column-container"><div id="fn8"><p><sup>8</sup>&nbsp;Technically, <span class="math inline">\(E_{ij}\)</span> here is an estimate, so I should probably write it <span class="math inline">\(\hat{E}_{ij}\)</span>. But since no-one else does, I won’t either.</p></div><div id="fn9"><p><sup>9</sup>&nbsp;A problem many of us worry about in real life.</p></div></div><p>Not surprisingly, this statistic is <span class="math inline">\(\chi^2\)</span> distributed. All we need to do is figure out how many degrees of freedom are involved, which actually isn’t too hard. As I mentioned before, you can (usually) think of the degrees of freedom as being equal to the number of data points that you’re analysing, minus the number of constraints. A contingency table with <span class="math inline">\(r\)</span> rows and <span class="math inline">\(c\)</span> columns contains a total of <span class="math inline">\(r \times c\)</span> observed frequencies, so that’s the total number of observations. What about the constraints? Here, it’s slightly trickier. The answer is always the same <span class="math display">\[
df = (r-1)(c-1)
\]</span> but the explanation for <em>why</em> the degrees of freedom takes this value is different depending on the experimental design. For the sake of argument, let’s suppose that we had honestly intended to survey exactly 87 robots and 93 humans (column totals fixed by the experimenter), but left the row totals free to vary (row totals are random variables). Let’s think about the constraints that apply here. Well, since we deliberately fixed the column totals by Act of Experimenter, we have <span class="math inline">\(c\)</span> constraints right there. But, there’s actually more to it than that. Remember how our null hypothesis had some free parameters (i.e., we had to estimate the <span class="math inline">\(P_i\)</span> values)? Those matter too. I won’t explain why in this book, but every free parameter in the null hypothesis is rather like an additional constraint. So, how many of those are there? Well, since these probabilities have to sum to 1, there’s only <span class="math inline">\(r-1\)</span> of these. So our total degrees of freedom is: <span class="math display">\[
\begin{array}{rcl}
df &amp;=&amp; \mbox{(number of observations)} - \mbox{(number of constraints)} \\
&amp;=&amp; (rc) - (c + (r-1)) \\
&amp;=&amp; rc - c - r + 1 \\
&amp;=&amp; (r - 1)(c - 1)
\end{array}
\]</span> Alternatively, suppose that the only thing that the experimenter fixed was the total sample size <span class="math inline">\(N\)</span>. That is, we quizzed the first 180 people that we saw, and it just turned out that 87 were robots and 93 were humans. This time around our reasoning would be slightly different, but would still lead us to the same answer. Our null hypothesis still has <span class="math inline">\(r-1\)</span> free parameters corresponding to the choice probabilities, but it now <em>also</em> has <span class="math inline">\(c-1\)</span> free parameters corresponding to the species probabilities, because we’d also have to estimate the probability that a randomly sampled person turns out to be a robot.<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a> Finally, since we did actually fix the total number of observations <span class="math inline">\(N\)</span>, that’s one more constraint. So now we have <span class="math inline">\(rc\)</span> observations, and <span class="math inline">\((c-1) + (r-1) + 1\)</span> constraints. What does that give? <span class="math display">\[
\begin{array}{rcl}
df &amp;=&amp; \mbox{(number of observations)} - \mbox{(number of constraints)} \\
&amp;=&amp; rc - ( (c-1) + (r-1) + 1) \\
&amp;=&amp; rc - c - r + 1 \\
&amp;=&amp; (r - 1)(c - 1)
\end{array}
\]</span> Amazing.</p>
</section>
<section id="sec-assoctestinr" class="level3" data-number="12.2.2">
<h3 data-number="12.2.2" class="anchored" data-anchor-id="sec-assoctestinr"><span class="header-section-number">12.2.2</span> Doing the test in R</h3>
<p>Okay, now that we know how the test works, let’s have a look at how it’s done in R. As tempting as it is to lead you through the tedious calculations so that you’re forced to learn it the long way, I figure there’s no point. I already showed you how to do it the long way for the goodness of fit test in the last section, and since the test of independence isn’t conceptually any different, you won’t learn anything new by doing it the long way. So instead, I’ll go straight to showing you the easy way. As always, R lets you do it multiple ways. There’s the <code>chisq.test()</code> function, which I’ll talk about in <a href="#sec-chisqtest" class="quarto-xref"><span>Section 12.6</span></a>, but first I want to use the <code>associationTest()</code> function in the <code>lsr</code> package, which I think is easier on beginners. It works in the exact same way as the <code>xtabs()</code> function. Recall that, in order to produce the contingency table, we used this command:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="at">formula =</span> <span class="sc">~</span> choice <span class="sc">+</span> species, <span class="at">data =</span> chapek9)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        species
choice   robot human
  puppy     13    15
  flower    30    13
  data      44    65</code></pre>
</div>
</div>
<p>The <code>associationTest()</code> function has exactly the same structure: it needs a <code>formula</code> that specifies which variables you’re cross-tabulating, and the name of a <code>data</code> frame that contains those variables. So the command is just this:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">associationTest</span>(<span class="at">formula =</span> <span class="sc">~</span> choice <span class="sc">+</span> species, <span class="at">data =</span> chapek9)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Chi-square test of categorical association

Variables:   choice, species 

Hypotheses: 
   null:        variables are independent of one another
   alternative: some contingency exists between variables

Observed contingency table:
        species
choice   robot human
  puppy     13    15
  flower    30    13
  data      44    65

Expected contingency table under the null hypothesis:
        species
choice   robot human
  puppy   13.5  14.5
  flower  20.8  22.2
  data    52.7  56.3

Test results: 
   X-squared statistic:  10.722 
   degrees of freedom:  2 
   p-value:  0.005 

Other information: 
   estimated effect size (Cramer's v):  0.244 </code></pre>
</div>
</div>
<p>Just like we did with the goodness of fit test, I’ll go through it line by line. The first two lines are, once again, just reminding you what kind of test you ran and what variables were used. Next, it tells you what the null and alternative hypotheses are (and again, I want to remind you not to get used to seeing these hypotheses written out so explicitly). Next, it shows you the observed contingency table that is being tested, and it also shows you what the expected frequencies would be if the null hypothesis were true.</p>
<p>The next part describes the results of the hypothesis test itself, reporting the <span class="math inline">\(X^2\)</span> statistic, the degrees of freedom, and the <span class="math inline">\(p\)</span>-value. And finally, it reports a measure of effect size (Cramér’s <span class="math inline">\(V\)</span>). You can ignore this bit for now. I’ll talk about it in just a moment.</p>
<p>This output gives us enough information to write up the result:</p>
<blockquote class="blockquote">
<p>Pearson’s <span class="math inline">\(\chi^2\)</span> revealed a significant association between species and choice (<span class="math inline">\(\chi^2(2) = 10.7, p &lt; .01\)</span>): robots appeared to be more likely to say that they prefer flowers, but the humans were more likely to say they prefer data.</p>
</blockquote>
<p>Notice that, once again, I provided a little bit of interpretation to help the human reader understand what’s going on with the data. Later on in my discussion section, I’d provide a bit more context. To illustrate the difference, here’s what I’d probably say later on:</p>
<blockquote class="blockquote">
<p>The fact that humans appeared to have a stronger preference for raw data files than robots is somewhat counterintuitive. However, in context it makes some sense: the civil authority on Chapek 9 has an unfortunate tendency to kill and dissect humans when they are identified. As such it seems most likely that the human participants did not respond honestly to the question, so as to avoid potentially undesirable consequences. This should be considered to be a substantial methodological weakness.</p>
</blockquote>
<p>This could be classified as a rather extreme example of a reactivity effect, I suppose. Obviously, in this case the problem is severe enough that the study is more or less worthless as a tool for understanding the difference in preferences among humans and robots. However, I hope this illustrates the difference between getting a statistically significant result (our null hypothesis is rejected in favour of the alternative), and finding something of scientific value (the data tell us nothing of interest about our research hypothesis due to a big methodological flaw).</p>
</section>
<section id="postscript" class="level3" data-number="12.2.3">
<h3 data-number="12.2.3" class="anchored" data-anchor-id="postscript"><span class="header-section-number">12.2.3</span> Postscript</h3>
<p>I later found out the data were made up, and I’d been watching cartoons instead of doing work.</p>
</section>
</section>
<section id="sec-yates" class="level2" data-number="12.3">
<h2 data-number="12.3" class="anchored" data-anchor-id="sec-yates"><span class="header-section-number">12.3</span> The continuity correction</h2>
<p>Okay, time for a little bit of a digression. I’ve been lying to you a little bit so far. There’s a tiny change that you need to make to your calculations whenever you only have 1 degree of freedom. It’s called the “continuity correction”, or sometimes the <strong><em>Yates correction</em></strong>. Remember what I pointed out earlier: the <span class="math inline">\(\chi^2\)</span> test is based on an approximation, specifically on the assumption that the binomial distribution starts to look like a normal distribution for large <span class="math inline">\(N\)</span>. One problem with this is that it often doesn’t quite work, especially when you’ve only got 1 degree of freedom (e.g., when you’re doing a test of independence on a <span class="math inline">\(2 \times 2\)</span> contingency table). The main reason for this is that the true sampling distribution for the <span class="math inline">\(X^2\)</span> statistic is actually discrete (because you’re dealing with categorical data!) but the <span class="math inline">\(\chi^2\)</span> distribution is continuous. This can introduce systematic problems. Specifically, when <span class="math inline">\(N\)</span> is small and when <span class="math inline">\(df=1\)</span>, the goodness of fit statistic tends to be “too big”, meaning that you actually have a bigger <span class="math inline">\(\alpha\)</span> value than you think (or, equivalently, the <span class="math inline">\(p\)</span> values are a bit too small). <span class="citation" data-cites="Yates1934">Yates (<a href="references.html#ref-Yates1934" role="doc-biblioref">1934</a>)</span> suggested a simple fix, in which you redefine the goodness of fit statistic as: <span class="math display">\[
X^2 = \sum_{i} \frac{(|E_i - O_i| - 0.5)^2}{E_i}
\]</span> Basically, he just subtracts off 0.5 everywhere. As far as I can tell from reading Yates’ paper, the correction is basically a hack. It’s not derived from any principled theory: rather, it’s based on an examination of the behaviour of the test, and observing that the corrected version seems to work better. I feel obliged to explain this because you will sometimes see R (or any other software for that matter) introduce this correction, so it’s kind of useful to know what they’re about. You’ll know when it happens, because the R output will explicitly say that it has used a “continuity correction” or “Yates’ correction”.</p>
</section>
<section id="sec-chisqeffectsize" class="level2 page-columns page-full" data-number="12.4">
<h2 data-number="12.4" class="anchored" data-anchor-id="sec-chisqeffectsize"><span class="header-section-number">12.4</span> Effect size</h2>
<p>As we discussed earlier (<a href="11-hypothesistesting.html#sec-effectsize" class="quarto-xref"><span>Section 11.8</span></a>), it’s becoming commonplace to ask researchers to report some measure of effect size. So, let’s suppose that you’ve run your chi-square test, which turns out to be significant. So you now know that there is some association between your variables (independence test) or some deviation from the specified probabilities (goodness of fit test). Now you want to report a measure of effect size. That is, given that there is an association/deviation, how strong is it?</p>
<p>There are several different measures that you can choose to report, and several different tools that you can use to calculate them. I won’t discuss all of them,<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a> but will instead focus on the most commonly reported measures of effect size.</p>
<div class="no-row-height column-margin column-container"><div id="fn10"><p><sup>10</sup>&nbsp;Though I do feel that it’s worth mentioning the <code>assocstats()</code> function in the <code>vcd</code> package. If you install and load the <code>vcd</code> package, then a command like <code>assocstats(chapek_frequencies)</code> will run the <span class="math inline">\(\chi^2\)</span> test as well as the likelihood ratio test (not discussed here); and then report three different measures of effect size: <span class="math inline">\(\phi^2\)</span>, Cramér’s <span class="math inline">\(V\)</span>, and the contingency coefficient (not discussed here).</p></div></div><p>By default, the two measures that people tend to report most frequently are the <span class="math inline">\(\phi\)</span> statistic and the somewhat superior version, known as Cramér’s <span class="math inline">\(V\)</span>. Mathematically, they’re very simple. To calculate the <span class="math inline">\(\phi\)</span> statistic, you just divide your <span class="math inline">\(X^2\)</span> value by the sample size, and take the square root: <span class="math display">\[
\phi = \sqrt{\frac{X^2}{N}}
\]</span> The idea here is that the <span class="math inline">\(\phi\)</span> statistic is supposed to range between 0 (no association at all) and 1 (perfect association), but it doesn’t always do this when your contingency table is bigger than <span class="math inline">\(2 \times 2\)</span>, which is a total pain. For bigger tables it’s actually possible to obtain <span class="math inline">\(\phi&gt;1\)</span>, which is pretty unsatisfactory. So, to correct for this, people usually prefer to report the <span class="math inline">\(V\)</span> statistic proposed by <span class="citation" data-cites="Cramer1946">Cramér (<a href="references.html#ref-Cramer1946" role="doc-biblioref">1946</a>)</span>. It’s a pretty simple adjustment to <span class="math inline">\(\phi\)</span>. If you’ve got a contingency table with <span class="math inline">\(r\)</span> rows and <span class="math inline">\(c\)</span> columns, then define <span class="math inline">\(k = \min(r,c)\)</span> to be the smaller of the two values. If so, then <strong><em>Cramér’s <span class="math inline">\(V\)</span></em></strong> statistic is <span class="math display">\[
V = \sqrt{\frac{X^2}{N(k-1)}}
\]</span> And you’re done. This seems to be a fairly popular measure, presumably because it’s easy to calculate, and it gives answers that aren’t completely silly: you know that <span class="math inline">\(V\)</span> really does range from 0 (no association at all) to 1 (perfect association).</p>
<p>Calculating <span class="math inline">\(V\)</span> or <span class="math inline">\(\phi\)</span> is obviously pretty straightforward. So much so that the core packages in R don’t seem to have functions to do it, though other packages do. To save you the time and effort of finding one, I’ve included one in the <code>lsr</code> package, called <code>cramersV()</code>. It takes a contingency table as input, and prints out the measure of effect size:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cramersV</span>(chapek_frequencies)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.244058</code></pre>
</div>
</div>
<p>However, if you’re using the <code>associationTest()</code> function to do your analysis, then you won’t actually need to use this at all, because it reports the Cramér’s <span class="math inline">\(V\)</span> statistic as part of the output.</p>
</section>
<section id="sec-chisqassumptions" class="level2" data-number="12.5">
<h2 data-number="12.5" class="anchored" data-anchor-id="sec-chisqassumptions"><span class="header-section-number">12.5</span> Assumptions of the test(s)</h2>
<p>All statistical tests make assumptions, and it’s usually a good idea to check that those assumptions are met. For the chi-square tests discussed so far in this chapter, the assumptions are:</p>
<ul>
<li><em>Expected frequencies are sufficiently large</em>. Remember how in the previous section we saw that the <span class="math inline">\(\chi^2\)</span> sampling distribution emerges because the binomial distribution is pretty similar to a normal distribution? Well, like we discussed in <a href="./09-probability.html">Introduction to probability</a> this is only true when the number of observations is sufficiently large. What that means in practice is that all of the expected frequencies need to be reasonably big. How big is reasonably big? Opinions differ, but the default assumption seems to be that you generally would like to see all your expected frequencies larger than about 5, though for larger tables you would probably be okay if at least 80% of the expected frequencies are above 5 and none of them are below 1. However, from what I’ve been able to discover <span class="citation" data-cites="Cochran1954">(e.g., <a href="references.html#ref-Cochran1954" role="doc-biblioref">Cochran, 1954</a>)</span>, these seem to have been proposed as rough guidelines, not hard and fast rules; and they seem to be somewhat conservative <span class="citation" data-cites="Larntz1978">(<a href="references.html#ref-Larntz1978" role="doc-biblioref">Larntz, 1978</a>)</span>.</li>
<li><em>Data are independent of one another</em>. One somewhat hidden assumption of the chi-square test is that you have to genuinely believe that the observations are independent. Here’s what I mean. Suppose I’m interested in the proportion of babies born at a particular hospital that are boys. I walk around the maternity wards, and observe 20 girls and only 10 boys. Seems like a pretty convincing difference, right? But later on, it turns out that I’d actually walked into the same ward 10 times, and in fact I’d only seen 2 girls and 1 boy. Not as convincing, is it? My original 30 <em>observations</em> were massively non-independent… and were only in fact equivalent to 3 independent observations. Obviously this is an extreme (and extremely silly) example, but it illustrates the basic issue. Non-independence “stuffs things up”. Sometimes it causes you to falsely reject the null, as the silly hospital example illustrates, but it can go the other way too. To give a slightly less stupid example, let’s consider what would happen if I’d done the cards experiment slightly differently: instead of asking 200 people to try to imagine sampling one card at random, suppose I asked 50 people to select 4 cards. One possibility would be that <em>everyone</em> selects one heart, one club, one diamond and one spade (in keeping with the “representativeness heuristic”; Tversky &amp; Kahneman 1974). This is highly non-random behaviour from people, but in this case, I would get an observed frequency of 50 for all four suits. For this example, the fact that the observations are non-independent (because the four cards that you pick will be related to each other) actually leads to the opposite effect… falsely retaining the null.</li>
</ul>
<p>If you happen to find yourself in a situation where independence is violated, it may be possible to use the McNemar test (which we’ll discuss) or the Cochran test (which we won’t). Similarly, if your expected cell counts are too small, check out the Fisher exact test. It is to these topics that we now turn.</p>
</section>
<section id="sec-chisqtest" class="level2 page-columns page-full" data-number="12.6">
<h2 data-number="12.6" class="anchored" data-anchor-id="sec-chisqtest"><span class="header-section-number">12.6</span> The most typical way to do chi-square tests in R</h2>
<p>When discussing how to do a chi-square goodness of fit test (<a href="#sec-goftestinr" class="quarto-xref"><span>Section 12.1.7</span></a>) and the chi-square test of independence (<a href="#sec-assoctestinr" class="quarto-xref"><span>Section 12.2.2</span></a>), I introduced you to two separate functions in the <code>lsr</code> package. We ran our goodness of fit tests using the <code>goodnessOfFitTest()</code> function, and our tests of independence (or association) using the <code>associationTest()</code> function. And both of those functions produced quite detailed output, showing you the relevant descriptive statistics, printing out explicit reminders of what the hypotheses are, and so on. When you’re first starting out, it can be very handy to be given this sort of guidance. However, once you start becoming a bit more proficient in statistics and in R it can start to get very tiresome. A real statistician hardly needs to be told what the null and alternative hypotheses for a chi-square test are, and if an advanced R user wants the descriptive statistics to be printed out, they know how to produce them!</p>
<p>For this reason, the basic <code>chisq.test()</code> function in R is a lot more terse in its output, and because the mathematics that underpin the goodness of fit test and the test of independence is basically the same in each case, it can run either test depending on what kind of input it is given. First, here’s the goodness of fit test. Suppose you have the frequency table <code>observed</code> that we used earlier,</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>observed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   clubs diamonds   hearts   spades 
      35       51       64       50 </code></pre>
</div>
</div>
<p>If you want to run the goodness of fit test against the hypothesis that all four suits are equally likely to appear, then all you need to do is input this frequency table to the <code>chisq.test()</code> function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="at">x =</span> observed)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities

data:  observed
X-squared = 8.44, df = 3, p-value = 0.03774</code></pre>
</div>
</div>
<p>Notice that the output is very compressed in comparison to the <code>goodnessOfFitTest()</code> function. It doesn’t bother to give you any descriptive statistics, it doesn’t tell you what null hypothesis is being tested, and so on. And as long as you already understand the test, that’s not a problem. Once you start getting familiar with R and with statistics, you’ll probably find that you prefer this simple output rather than the rather lengthy output that <code>goodnessOfFitTest()</code> produces. Anyway, if you want to change the null hypothesis, it’s exactly the same as before, just specify the probabilities using the <code>p</code> argument. For instance:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="at">x =</span> observed, <span class="at">p =</span> <span class="fu">c</span>(.<span class="dv">2</span>, .<span class="dv">3</span>, .<span class="dv">3</span>, .<span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities

data:  observed
X-squared = 4.7417, df = 3, p-value = 0.1917</code></pre>
</div>
</div>
<p>Again, these are the same numbers that the <code>goodnessOfFitTest()</code> function reports at the end of the output. It just hasn’t included any of the other details.</p>
<p>What about a test of independence? As it turns out, the <code>chisq.test()</code> function is pretty clever.<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a> If you input a <em>cross-tabulation</em> rather than a simple frequency table, it realises that you’re asking for a test of independence and not a goodness of fit test. Recall that we already have this cross-tabulation stored as the <code>chapek_frequencies</code> variable:</p>
<div class="no-row-height column-margin column-container"><div id="fn11"><p><sup>11</sup>&nbsp;Not really.</p></div></div><div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>chapek_frequencies</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        species
choice   robot human
  puppy     13    15
  flower    30    13
  data      44    65</code></pre>
</div>
</div>
<p>To get the test of independence, all we have to do is feed this frequency table into the <code>chisq.test()</code> function like so:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(chapek_frequencies)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  chapek_frequencies
X-squared = 10.722, df = 2, p-value = 0.004697</code></pre>
</div>
</div>
<p>Again, the numbers are the same as last time, it’s just that the output is very terse and doesn’t really explain what’s going on in the rather tedious way that <code>associationTest()</code> does. As before, my intuition is that when you’re just getting started it’s easier to use something like <code>associationTest()</code> because it shows you more detail about what’s going on, but later on you’ll probably find that <code>chisq.test()</code> is more convenient.</p>
</section>
<section id="sec-fisherexacttest" class="level2 page-columns page-full" data-number="12.7">
<h2 data-number="12.7" class="anchored" data-anchor-id="sec-fisherexacttest"><span class="header-section-number">12.7</span> The Fisher exact test</h2>
<p>What should you do if your cell counts are too small, but you’d still like to test the null hypothesis that the two variables are independent? One answer would be “collect more data”, but that’s far too glib: there are a lot of situations in which it would be either infeasible or unethical to do that. If so, statisticians have a kind of moral obligation to provide scientists with better tests. In this instance, Fisher (1922) kindly provided the right answer to the question. To illustrate the basic idea, let’s suppose that we’re analysing data from a field experiment, looking at the emotional status of people who have been accused of witchcraft; some of whom are currently being burned at the stake.<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a> Unfortunately for the scientist (but rather fortunately for the general populace), it’s actually quite hard to find people in the process of being set on fire, so the cell counts are awfully small in some cases. The <code>salem.Rdata</code> file illustrates the point:</p>
<div class="no-row-height column-margin column-container"><div id="fn12"><p><sup>12</sup>&nbsp;This example is based on a joke article published in the <em>Journal of Irreproducible Results</em>.</p></div></div><div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/salem.Rdata"</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">who</span>(<span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   -- Name --   -- Class --   -- Size --
   trial        data.frame    16 x 2    
    $happy      logical       16        
    $on_fire    logical       16        </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>salem_tabs <span class="ot">&lt;-</span> <span class="fu">table</span>(trial)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(salem_tabs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       on_fire
happy   FALSE TRUE
  FALSE     3    3
  TRUE     10    0</code></pre>
</div>
</div>
<p>Looking at this data, you’d be hard pressed not to suspect that people not on fire are more likely to be happy than people on fire. However, the chi-square test makes this very hard to test because of the small sample size. If I try to do so, R gives me a warning message:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(salem_tabs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(salem_tabs): Chi-squared approximation may be incorrect</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  salem_tabs
X-squared = 3.3094, df = 1, p-value = 0.06888</code></pre>
</div>
</div>
<p>Speaking as someone who doesn’t want to be set on fire, I’d <em>really</em> like to be able to get a better answer than this. This is where <strong><em>Fisher’s exact test</em></strong> <span class="citation" data-cites="Fisher1922">(<a href="references.html#ref-Fisher1922" role="doc-biblioref">Fisher, 1922</a>)</span> comes in very handy.</p>
<p>The Fisher exact test works somewhat differently to the chi-square test (or in fact any of the other hypothesis tests that I talk about in this book) insofar as it doesn’t have a test statistic; it calculates the <span class="math inline">\(p\)</span>-value “directly”. I’ll explain the basics of how the test works for a <span class="math inline">\(2 \times 2\)</span> contingency table, though the test works fine for larger tables. As before, let’s have some notation:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Happy</th>
<th>Sad</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Set on fire</td>
<td><span class="math inline">\(O_{11}\)</span></td>
<td><span class="math inline">\(O_{12}\)</span></td>
<td><span class="math inline">\(R_{1}\)</span></td>
</tr>
<tr class="even">
<td>Not set on fire</td>
<td><span class="math inline">\(O_{21}\)</span></td>
<td><span class="math inline">\(O_{22}\)</span></td>
<td><span class="math inline">\(R_{2}\)</span></td>
</tr>
<tr class="odd">
<td>Total</td>
<td><span class="math inline">\(C_{1}\)</span></td>
<td><span class="math inline">\(C_{2}\)</span></td>
<td><span class="math inline">\(N\)</span></td>
</tr>
</tbody>
</table>
<p>In order to construct the test Fisher treats both the row and column totals (<span class="math inline">\(R_1\)</span>, <span class="math inline">\(R_2\)</span>, <span class="math inline">\(C_1\)</span> and <span class="math inline">\(C_2\)</span>) as known, fixed quantities; and then calculates the probability that we would have obtained the observed frequencies that we did (<span class="math inline">\(O_{11}\)</span>, <span class="math inline">\(O_{12}\)</span>, <span class="math inline">\(O_{21}\)</span> and <span class="math inline">\(O_{22}\)</span>) given those totals. In the notation that we developed in <a href="./09-probability.html">Introduction to probability</a> this is written: <span class="math display">\[
P(O_{11}, O_{12}, O_{21}, O_{22} \ | \ R_1, R_2, C_1, C_2)
\]</span> and as you might imagine, it’s a slightly tricky exercise to figure out what this probability is, but it turns out that this probability is described by a distribution known as the <em>hypergeometric distribution</em><a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a>. Now that we know this, what we have to do to calculate our <span class="math inline">\(p\)</span>-value is calculate the probability of observing this particular table <em>or a table that is “more extreme”</em>.<a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a> Back in the 1920s, computing this sum was daunting even in the simplest of situations, but these days it’s pretty easy as long as the tables aren’t too big and the sample size isn’t too large. The conceptually tricky issue is to figure out what it means to say that one contingency table is more “extreme” than another. The easiest solution is to say that the table with the lowest probability is the most extreme. This then gives us the <span class="math inline">\(p\)</span>-value.</p>
<div class="no-row-height column-margin column-container"><div id="fn13"><p><sup>13</sup>&nbsp;The R functions for this distribution are <code>dhyper()</code>, <code>phyper()</code>, <code>qhyper()</code> and <code>rhyper()</code>, though you don’t need them for this book, and I haven’t given you enough information to use these to perform the Fisher exact test the long way.</p></div><div id="fn14"><p><sup>14</sup>&nbsp;Not surprisingly, the Fisher exact test is motivated by Fisher’s interpretation of a <span class="math inline">\(p\)</span>-value, not Neyman’s!</p></div></div><p>The implementation of the test in R is via the <code>fisher.test()</code> function. Here’s how it is used:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(salem_tabs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  salem_tabs
p-value = 0.03571
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 0.000000 1.202913
sample estimates:
odds ratio 
         0 </code></pre>
</div>
</div>
<p>This is a bit more output than we got from some of our earlier tests. The main thing we’re interested in here is the <span class="math inline">\(p\)</span>-value, which in this case is small enough (<span class="math inline">\(p=.036\)</span>) to justify rejecting the null hypothesis that people on fire are just as happy as people not on fire.</p>
</section>
<section id="sec-mcnemar" class="level2" data-number="12.8">
<h2 data-number="12.8" class="anchored" data-anchor-id="sec-mcnemar"><span class="header-section-number">12.8</span> The McNemar test</h2>
<p>Suppose you’ve been hired to work for the <em>Australian Generic Political Party</em> (AGPP), and part of your job is to find out how effective the AGPP political advertisements are. So, what you do, is you put together a sample of <span class="math inline">\(N=100\)</span> people, and ask them to watch the AGPP ads. Before they see anything, you ask them if they intend to vote for the AGPP; and then after showing the ads, you ask them again, to see if anyone has changed their minds. Obviously, if you’re any good at your job, you’d also do a whole lot of other things too, but let’s consider just this one simple experiment. One way to describe your data is via the following contingency table:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Before</th>
<th>After</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Yes</td>
<td>30</td>
<td>10</td>
<td>40</td>
</tr>
<tr class="even">
<td>No</td>
<td>70</td>
<td>90</td>
<td>160</td>
</tr>
<tr class="odd">
<td>Total</td>
<td>100</td>
<td>100</td>
<td>200</td>
</tr>
</tbody>
</table>
<p>At first pass, you might think that this situation lends itself to the Pearson <span class="math inline">\(\chi^2\)</span> test of independence (as per <a href="#sec-chisqindependence" class="quarto-xref"><span>Section 12.2</span></a>). However, a little bit of thought reveals that we’ve got a problem: we have 100 participants, but 200 observations. This is because each person has provided us with an answer in <em>both</em> the before column and the after column. What this means is that the 200 observations aren’t independent of each other: if voter A says “yes” the first time and voter B says “no”, then you’d expect that voter A is more likely to say “yes” the second time than voter B! The consequence of this is that the usual <span class="math inline">\(\chi^2\)</span> test won’t give trustworthy answers due to the violation of the independence assumption. Now, if this were a really uncommon situation, I wouldn’t be bothering to waste your time talking about it. But it’s not uncommon at all: this is a <em>standard</em> repeated measures design, and none of the tests we’ve considered so far can handle it. Eek.</p>
<p>The solution to the problem was published by <span class="citation" data-cites="McNemar1947">McNemar (<a href="references.html#ref-McNemar1947" role="doc-biblioref">1947</a>)</span>. The trick is to start by tabulating your data in a slightly different way:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Before: Yes</th>
<th>Before: No</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>After: Yes</td>
<td>5</td>
<td>5</td>
<td>10</td>
</tr>
<tr class="even">
<td>After: No</td>
<td>25</td>
<td>65</td>
<td>90</td>
</tr>
<tr class="odd">
<td>Total</td>
<td>30</td>
<td>70</td>
<td>100</td>
</tr>
</tbody>
</table>
<p>This is exactly the same data, but it’s been rewritten so that each of our 100 participants appears in only one cell. Because we’ve written our data this way, the independence assumption is now satisfied, and this is a contingency table that we <em>can</em> use to construct an <span class="math inline">\(X^2\)</span> goodness of fit statistic. However, as we’ll see, we need to do it in a slightly nonstandard way. To see what’s going on, it helps to label the entries in our table a little differently:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Before: Yes</th>
<th>Before: No</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>After: Yes</td>
<td><span class="math inline">\(a\)</span></td>
<td><span class="math inline">\(b\)</span></td>
<td><span class="math inline">\(a+b\)</span></td>
</tr>
<tr class="even">
<td>After: No</td>
<td><span class="math inline">\(c\)</span></td>
<td><span class="math inline">\(d\)</span></td>
<td><span class="math inline">\(c+d\)</span></td>
</tr>
<tr class="odd">
<td>Total</td>
<td><span class="math inline">\(a+c\)</span></td>
<td><span class="math inline">\(b+d\)</span></td>
<td><span class="math inline">\(n\)</span></td>
</tr>
</tbody>
</table>
<p>Next, let’s think about what our null hypothesis is: it’s that the “before” test and the “after” test have the same proportion of people saying “Yes, I will vote for AGPP”. Because of the way that we have rewritten the data, it means that we’re now testing the hypothesis that the <em>row totals</em> and <em>column totals</em> come from the same distribution. Thus, the null hypothesis in McNemar’s test is that we have “marginal homogeneity”. That is, the row totals and column totals have the same distribution: <span class="math inline">\(P_a + P_b = P_a + P_c\)</span>, and similarly that <span class="math inline">\(P_c + P_d = P_b + P_d\)</span>. Notice that this means that the null hypothesis actually simplifies to <span class="math inline">\(P_b = P_c\)</span>. In other words, as far as the McNemar test is concerned, it’s only the off-diagonal entries in this table (i.e., <span class="math inline">\(b\)</span> and <span class="math inline">\(c\)</span>) that matter! After noticing this, the <strong><em>McNemar test of marginal homogeneity</em></strong> is no different to a usual <span class="math inline">\(\chi^2\)</span> test. After applying the Yates correction, our test statistic becomes: <span class="math display">\[
X^2 = \frac{(|b-c| - 0.5)^2}{b+c}
\]</span> or, to revert to the notation that we used earlier in this chapter: <span class="math display">\[
X^2 = \frac{(|O_{12}-O_{21}| - 0.5)^2}{O_{12} + O_{21}}
\]</span> and this statistic has an (approximately) <span class="math inline">\(\chi^2\)</span> distribution with <span class="math inline">\(df=1\)</span>. However, remember that – just like the other <span class="math inline">\(\chi^2\)</span> tests – it’s only an approximation, so you need to have reasonably large expected cell counts for it to work.</p>
<section id="doing-the-mcnemar-test-in-r" class="level3" data-number="12.8.1">
<h3 data-number="12.8.1" class="anchored" data-anchor-id="doing-the-mcnemar-test-in-r"><span class="header-section-number">12.8.1</span> Doing the McNemar test in R</h3>
<p>Now that you know what the McNemar test is all about, let’s actually run one. The <code>agpp.Rdata</code> file contains the raw data that I discussed previously, so let’s have a look at it:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/agpp.Rdata"</span>)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">who</span>(<span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   -- Name --          -- Class --   -- Size --
   agpp                data.frame    100 x 3   
    $id                factor        100       
    $response_before   factor        100       
    $response_after    factor        100       
   salem_tabs          table         2 x 2     </code></pre>
</div>
</div>
<p>The <code>agpp</code> data frame contains three variables, an <code>id</code> variable that labels each participant in the data set (we’ll see why that’s useful in a moment), a <code>response_before</code> variable that records the person’s answer when they were asked the question the first time, and a <code>response_after</code> variable that shows the answer that they gave when asked the same question a second time. As usual, here’s the first 6 entries:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(agpp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      id response_before response_after
1 subj.1              no            yes
2 subj.2             yes             no
3 subj.3             yes             no
4 subj.4             yes             no
5 subj.5              no             no
6 subj.6              no             no</code></pre>
</div>
</div>
<p>and here’s a summary:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(agpp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        id     response_before response_after
 subj.1  : 1   no :70          no :90        
 subj.10 : 1   yes:30          yes:10        
 subj.100: 1                                 
 subj.11 : 1                                 
 subj.12 : 1                                 
 subj.13 : 1                                 
 (Other) :94                                 </code></pre>
</div>
</div>
<p>Notice that each participant appears only once in this data frame. When we tabulate this data frame using <code>xtabs()</code>, we get the appropriate table:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>right_table <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(<span class="sc">~</span> response_before <span class="sc">+</span> response_after, <span class="at">data =</span> agpp)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(right_table)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>               response_after
response_before no yes
            no  65   5
            yes 25   5</code></pre>
</div>
</div>
<p>and from there, we can run the McNemar test by using the <code>mcnemar.test()</code> function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mcnemar.test</span>(right_table)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    McNemar's Chi-squared test with continuity correction

data:  right_table
McNemar's chi-squared = 12.033, df = 1, p-value = 0.0005226</code></pre>
</div>
</div>
<p>And we’re done. We’ve just run a McNemar’s test to determine if people were just as likely to vote AGPP after the ads as they were before hand. The test was significant (<span class="math inline">\(\chi^2(1) = 12.03, p&lt;.001\)</span>), suggesting that they were not. And in fact, it looks like the ads had a negative effect: people were less likely to vote AGPP after seeing the ads. Which makes a lot of sense when you consider the quality of a typical political advertisement.</p>
</section>
</section>
<section id="whats-the-difference-between-mcnemar-and-independence" class="level2" data-number="12.9">
<h2 data-number="12.9" class="anchored" data-anchor-id="whats-the-difference-between-mcnemar-and-independence"><span class="header-section-number">12.9</span> What’s the difference between McNemar and independence?</h2>
<p>Let’s go all the way back to the beginning of the chapter, and look at the <code>cards</code> data set again. If you recall, the actual experimental design that I described involved people making <em>two</em> choices. Because we have information about the first choice and the second choice that everyone made, we can construct the following contingency table that cross-tabulates the first choice against the second choice.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>card_choices <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(<span class="sc">~</span> choice_1 <span class="sc">+</span> choice_2, <span class="at">data =</span> cards)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>card_choices</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          choice_2
choice_1   clubs diamonds hearts spades
  clubs       10        9     10      6
  diamonds    20        4     13     14
  hearts      20       18      3     23
  spades      18       13     15      4</code></pre>
</div>
</div>
<p>Suppose I wanted to know whether the choice you make the second time is dependent on the choice you made the first time. This is where a test of independence is useful, and what we’re trying to do is see if there’s some relationship between the rows and columns of this table. Here’s the result:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(card_choices)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  card_choices
X-squared = 29.237, df = 9, p-value = 0.0005909</code></pre>
</div>
</div>
<p>Alternatively, suppose I wanted to know if <em>on average</em>, the frequencies of suit choices were different the second time than the first time. In that situation, what I’m really trying to see is if the row totals in <code>card_choices</code> (i.e., the frequencies for <code>choice_1</code>) are different from the column totals (i.e., the frequencies for <code>choice_2</code>). That’s when you use the McNemar test:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mcnemar.test</span>(card_choices)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    McNemar's Chi-squared test

data:  card_choices
McNemar's chi-squared = 16.033, df = 6, p-value = 0.01358</code></pre>
</div>
</div>
<p>Notice that the results are different! These aren’t the same test.</p>
</section>
<section id="summary" class="level2" data-number="12.10">
<h2 data-number="12.10" class="anchored" data-anchor-id="summary"><span class="header-section-number">12.10</span> Summary</h2>
<p>The key ideas discussed in this chapter are:</p>
<ul>
<li>The chi-square goodness of fit test (<a href="#sec-goftest" class="quarto-xref"><span>Section 12.1</span></a>) is used when you have a table of observed frequencies of different categories; and the null hypothesis gives you a set of “known” probabilities to compare them to. You can either use the <code>goodnessOfFitTest()</code> function in the <code>lsr</code> package to run this test, or the <code>chisq.test()</code> function.</li>
<li>The chi-square test of independence (<a href="#sec-chisqindependence" class="quarto-xref"><span>Section 12.2</span></a>) is used when you have a contingency table (cross-tabulation) of two categorical variables. The null hypothesis is that there is no relationship/association between the variables. You can either use the <code>associationTest()</code> function in the <code>lsr</code> package, or you can use <code>chisq.test()</code>.</li>
<li>Effect size for a contingency table can be measured in several ways (<a href="#sec-chisqeffectsize" class="quarto-xref"><span>Section 12.4</span></a>). In particular we noted the Cramér’s <span class="math inline">\(V\)</span> statistic, which can be calculated using <code>cramersV()</code>. This is also part of the output produced by <code>associationTest()</code>.</li>
<li>Both versions of the Pearson test rely on two assumptions: that the expected frequencies are sufficiently large, and that the observations are independent (<a href="#sec-chisqassumptions" class="quarto-xref"><span>Section 12.5</span></a>). The Fisher exact test (<a href="#sec-fisherexacttest" class="quarto-xref"><span>Section 12.7</span></a>) can be used when the expected frequencies are small, <code>fisher.test(x = contingency.table)</code>. The McNemar test (<a href="#sec-mcnemar" class="quarto-xref"><span>Section 12.8</span></a>) can be used for some kinds of violations of independence, <code>mcnemar.test(x = contingency.table)</code>.</li>
</ul>
<p>If you’re interested in learning more about categorical data analysis, a good first choice would be <span class="citation" data-cites="Agresti1996">Agresti (<a href="references.html#ref-Agresti1996" role="doc-biblioref">1996</a>)</span> which, as the title suggests, provides an <em>Introduction to Categorical Data Analysis</em>. If the introductory book isn’t enough for you (or can’t solve the problem you’re working on) you could consider <span class="citation" data-cites="Agresti2002">Agresti (<a href="references.html#ref-Agresti2002" role="doc-biblioref">2002</a>)</span>, <em>Categorical Data Analysis</em>. The latter is a more advanced text, so it’s probably not wise to jump straight from this book to that one.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-Agresti1996" class="csl-entry" role="listitem">
Agresti, A. (1996). <em>An introduction to categorical data analysis</em>. Wiley.
</div>
<div id="ref-Agresti2002" class="csl-entry" role="listitem">
Agresti, A. (2002). <em>Categorical data analysis</em> (2nd ed.). Wiley.
</div>
<div id="ref-Cochran1954" class="csl-entry" role="listitem">
Cochran, W. G. (1954). The <span class="math inline">\(\chi^2\)</span> test of goodness of fit. <em>The Annals of Mathematical Statistics</em>, <em>23</em>, 315–345.
</div>
<div id="ref-Cramer1946" class="csl-entry" role="listitem">
Cramér, H. (1946). <em>Mathematical methods of statistics</em>. Princeton University Press.
</div>
<div id="ref-Fisher1922" class="csl-entry" role="listitem">
Fisher, R. A. (1922). On the interpretation of <span class="math inline">\(\chi^2\)</span> from contingency tables, and the calculation of <span class="math inline">\(p\)</span>. <em>Journal of the Royal Statistical Society</em>, <em>84</em>, 87–94.
</div>
<div id="ref-Hogg2005" class="csl-entry" role="listitem">
Hogg, R. V., McKean, J. V., &amp; Craig, A. T. (2005). <em>Introduction to mathematical statistics</em> (6th ed.). Pearson.
</div>
<div id="ref-Larntz1978" class="csl-entry" role="listitem">
Larntz, K. (1978). Small-sample comparisons of exact levels for chi-squared goodness-of-fit statistics. <em>Journal of the American Statistical Association</em>, <em>73</em>, 253–263.
</div>
<div id="ref-McNemar1947" class="csl-entry" role="listitem">
McNemar, Q. (1947). Note on the sampling error of the difference between correlated proportions or percentages. <em>Psychometrika</em>, <em>12</em>, 153–157.
</div>
<div id="ref-Pearson1900" class="csl-entry" role="listitem">
Pearson, K. (1900). On the criterion that a given system of deviations from the probable in the case of a correlated system of variables is such that it can be reasonably supposed to have arisen from random sampling. <em>Philosophical Magazine</em>, <em>50</em>, 157–175.
</div>
<div id="ref-Sokal1994" class="csl-entry" role="listitem">
Sokal, R. R., &amp; Rohlf, F. J. (1994). <em>Biometry: The principles and practice of statistics in biological research</em> (3rd ed.). Freeman.
</div>
<div id="ref-Yates1934" class="csl-entry" role="listitem">
Yates, F. (1934). Contingency tables involving small numbers and the <span class="math inline">\(\chi^2\)</span> test. <em>Supplement to the Journal of the Royal Statistical Society</em>, <em>1</em>, 217–235.
</div>
</div>
</section>


</main> <!-- /main -->
<!-- plausible -->
<script async="" defer="" data-domain="learningstatisticswithr.com" src="https://plausible.io/js/plausible.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/learningstatisticswithr\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./11-hypothesistesting.html" class="pagination-link" aria-label="Hypothesis testing">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./13-ttest.html" class="pagination-link" aria-label="The $t$-test">
        <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">The <span class="math inline">\(t\)</span>-test</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>