<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.52">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>17&nbsp; Bayesian statistics – Learning Statistics with R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./epilogue.html" rel="next">
<link href="./16-anova2.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="17&nbsp; Bayesian statistics – Learning Statistics with R">
<meta property="og:description" content="">
<meta property="og:image" content="https://learningstatisticswithr.com/cover/cover-social.jpg">
<meta property="og:site_name" content="Learning Statistics with R">
<meta name="twitter:title" content="17&nbsp; Bayesian statistics – Learning Statistics with R">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://learningstatisticswithr.com/cover/cover-social.jpg">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./17-bayes.html">Endings, alternatives and prospects</a></li><li class="breadcrumb-item"><a href="./17-bayes.html"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Bayesian statistics</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Learning Statistics with R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Background</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./background-preamble.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">A word on statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-whystats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why do we learn statistics?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-studydesign.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">A brief introduction to research design</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">An introduction to R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-introR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Getting started with R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-mechanics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">R mechanics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Working with data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-descriptives.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Descriptive statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-graphics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Drawing graphs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-datahandling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Pragmatic matters</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-scripting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Basic programming</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical theory</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./theory-preamble.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">A chat about inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Introduction to probability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Estimating unknown quantities from a sample</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-hypothesistesting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical tools</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-chisquare.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Categorical data analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-ttest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">The <span class="math inline">\(t\)</span>-test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Comparing several means (one-way ANOVA)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Linear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-anova2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Endings, alternatives and prospects</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-bayes.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Bayesian statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./epilogue.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Epilogue</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./changelog.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Changelog</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-basicbayes" id="toc-sec-basicbayes" class="nav-link active" data-scroll-target="#sec-basicbayes"><span class="header-section-number">17.1</span> Probabilistic reasoning by rational agents</a>
  <ul class="collapse">
  <li><a href="#priors-what-you-believed-before" id="toc-priors-what-you-believed-before" class="nav-link" data-scroll-target="#priors-what-you-believed-before"><span class="header-section-number">17.1.1</span> Priors: what you believed before</a></li>
  <li><a href="#likelihoods-theories-about-the-data" id="toc-likelihoods-theories-about-the-data" class="nav-link" data-scroll-target="#likelihoods-theories-about-the-data"><span class="header-section-number">17.1.2</span> Likelihoods: theories about the data</a></li>
  <li><a href="#the-joint-probability-of-data-and-hypothesis" id="toc-the-joint-probability-of-data-and-hypothesis" class="nav-link" data-scroll-target="#the-joint-probability-of-data-and-hypothesis"><span class="header-section-number">17.1.3</span> The joint probability of data and hypothesis</a></li>
  <li><a href="#updating-beliefs-using-bayes-rule" id="toc-updating-beliefs-using-bayes-rule" class="nav-link" data-scroll-target="#updating-beliefs-using-bayes-rule"><span class="header-section-number">17.1.4</span> Updating beliefs using Bayes’ rule</a></li>
  </ul></li>
  <li><a href="#sec-bayesianhypothesistests" id="toc-sec-bayesianhypothesistests" class="nav-link" data-scroll-target="#sec-bayesianhypothesistests"><span class="header-section-number">17.2</span> Bayesian hypothesis tests</a>
  <ul class="collapse">
  <li><a href="#the-bayes-factor" id="toc-the-bayes-factor" class="nav-link" data-scroll-target="#the-bayes-factor"><span class="header-section-number">17.2.1</span> The Bayes factor</a></li>
  <li><a href="#interpreting-bayes-factors" id="toc-interpreting-bayes-factors" class="nav-link" data-scroll-target="#interpreting-bayes-factors"><span class="header-section-number">17.2.2</span> Interpreting Bayes factors</a></li>
  </ul></li>
  <li><a href="#sec-whybayes" id="toc-sec-whybayes" class="nav-link" data-scroll-target="#sec-whybayes"><span class="header-section-number">17.3</span> Why be a Bayesian?</a>
  <ul class="collapse">
  <li><a href="#statistics-that-mean-what-you-think-they-mean" id="toc-statistics-that-mean-what-you-think-they-mean" class="nav-link" data-scroll-target="#statistics-that-mean-what-you-think-they-mean"><span class="header-section-number">17.3.1</span> Statistics that mean what you think they mean</a></li>
  <li><a href="#evidentiary-standards-you-can-believe" id="toc-evidentiary-standards-you-can-believe" class="nav-link" data-scroll-target="#evidentiary-standards-you-can-believe"><span class="header-section-number">17.3.2</span> Evidentiary standards you can believe</a></li>
  <li><a href="#the-p-value-is-a-lie" id="toc-the-p-value-is-a-lie" class="nav-link" data-scroll-target="#the-p-value-is-a-lie"><span class="header-section-number">17.3.3</span> The <span class="math inline">\(p\)</span>-value is a lie</a></li>
  <li><a href="#is-it-really-this-bad" id="toc-is-it-really-this-bad" class="nav-link" data-scroll-target="#is-it-really-this-bad"><span class="header-section-number">17.3.4</span> Is it really this bad?</a></li>
  </ul></li>
  <li><a href="#sec-bayescontingency" id="toc-sec-bayescontingency" class="nav-link" data-scroll-target="#sec-bayescontingency"><span class="header-section-number">17.4</span> Bayesian analysis of contingency tables</a>
  <ul class="collapse">
  <li><a href="#the-orthodox-test" id="toc-the-orthodox-test" class="nav-link" data-scroll-target="#the-orthodox-test"><span class="header-section-number">17.4.1</span> The orthodox test</a></li>
  <li><a href="#the-bayesian-test" id="toc-the-bayesian-test" class="nav-link" data-scroll-target="#the-bayesian-test"><span class="header-section-number">17.4.2</span> The Bayesian test</a></li>
  <li><a href="#writing-up-the-results" id="toc-writing-up-the-results" class="nav-link" data-scroll-target="#writing-up-the-results"><span class="header-section-number">17.4.3</span> Writing up the results</a></li>
  <li><a href="#other-sampling-plans" id="toc-other-sampling-plans" class="nav-link" data-scroll-target="#other-sampling-plans"><span class="header-section-number">17.4.4</span> Other sampling plans</a></li>
  </ul></li>
  <li><a href="#sec-ttestbf" id="toc-sec-ttestbf" class="nav-link" data-scroll-target="#sec-ttestbf"><span class="header-section-number">17.5</span> Bayesian <span class="math inline">\(t\)</span>-tests</a>
  <ul class="collapse">
  <li><a href="#independent-samples-t-test" id="toc-independent-samples-t-test" class="nav-link" data-scroll-target="#independent-samples-t-test"><span class="header-section-number">17.5.1</span> Independent samples <span class="math inline">\(t\)</span>-test</a></li>
  <li><a href="#paired-samples-t-test" id="toc-paired-samples-t-test" class="nav-link" data-scroll-target="#paired-samples-t-test"><span class="header-section-number">17.5.2</span> Paired samples <span class="math inline">\(t\)</span>-test</a></li>
  </ul></li>
  <li><a href="#sec-bayesregression" id="toc-sec-bayesregression" class="nav-link" data-scroll-target="#sec-bayesregression"><span class="header-section-number">17.6</span> Bayesian regression</a>
  <ul class="collapse">
  <li><a href="#a-quick-refresher" id="toc-a-quick-refresher" class="nav-link" data-scroll-target="#a-quick-refresher"><span class="header-section-number">17.6.1</span> A quick refresher</a></li>
  <li><a href="#the-bayesian-version" id="toc-the-bayesian-version" class="nav-link" data-scroll-target="#the-bayesian-version"><span class="header-section-number">17.6.2</span> The Bayesian version</a></li>
  <li><a href="#finding-the-best-model" id="toc-finding-the-best-model" class="nav-link" data-scroll-target="#finding-the-best-model"><span class="header-section-number">17.6.3</span> Finding the best model</a></li>
  <li><a href="#extracting-bayes-factors-for-all-included-terms" id="toc-extracting-bayes-factors-for-all-included-terms" class="nav-link" data-scroll-target="#extracting-bayes-factors-for-all-included-terms"><span class="header-section-number">17.6.4</span> Extracting Bayes factors for all included terms</a></li>
  </ul></li>
  <li><a href="#sec-bayesanova" id="toc-sec-bayesanova" class="nav-link" data-scroll-target="#sec-bayesanova"><span class="header-section-number">17.7</span> Bayesian ANOVA</a>
  <ul class="collapse">
  <li><a href="#a-quick-refresher-1" id="toc-a-quick-refresher-1" class="nav-link" data-scroll-target="#a-quick-refresher-1"><span class="header-section-number">17.7.1</span> A quick refresher</a></li>
  <li><a href="#the-bayesian-version-1" id="toc-the-bayesian-version-1" class="nav-link" data-scroll-target="#the-bayesian-version-1"><span class="header-section-number">17.7.2</span> The Bayesian version</a></li>
  <li><a href="#constructing-bayesian-type-ii-tests" id="toc-constructing-bayesian-type-ii-tests" class="nav-link" data-scroll-target="#constructing-bayesian-type-ii-tests"><span class="header-section-number">17.7.3</span> Constructing Bayesian Type II tests</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">17.8</span> Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./17-bayes.html">Endings, alternatives and prospects</a></li><li class="breadcrumb-item"><a href="./17-bayes.html"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Bayesian statistics</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-bayes" class="quarto-section-identifier"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Bayesian statistics</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="pullquote">
<p><em>In our reasonings concerning matter of fact, there are all imaginable degrees of assurance, from the highest certainty to the lowest species of moral evidence. A wise man, therefore, proportions his belief to the evidence.</em></p>
<p>— David Hume</p>
<p><a href="http://en.wikiquote.org/wiki/David_Hume" class="uri">http://en.wikiquote.org/wiki/David_Hume</a></p>
</div>
<p>The ideas I’ve presented to you in this book describe inferential statistics from the frequentist perspective. I’m not alone in doing this. In fact, almost every textbook given to undergraduate psychology students presents the opinions of the frequentist statistician as <em>the</em> theory of inferential statistics, the one true way to do things. I have taught this way for practical reasons. The frequentist view of statistics dominated the academic field of statistics for most of the 20th century, and this dominance is even more extreme among applied scientists. It was and is current practice among psychologists to use frequentist methods. Because frequentist methods are ubiquitous in scientific papers, every student of statistics needs to understand those methods, otherwise they will be unable to make sense of what those papers are saying! Unfortunately – in my opinion at least – the current practice in psychology is often misguided, and the reliance on frequentist methods is partly to blame. In this chapter I explain why I think this, and provide an introduction to Bayesian statistics, an approach that I think is generally superior to the orthodox approach.</p>
<p>This chapter comes in two parts. In <a href="#sec-basicbayes" class="quarto-xref"><span>Section 17.1</span></a> through <a href="#sec-whybayes" class="quarto-xref"><span>Section 17.3</span></a> I talk about what Bayesian statistics are all about, covering the basic mathematical rules for how it works as well as an explanation for why I think the Bayesian approach is so useful. Afterwards, I provide a brief overview of how you can do Bayesian versions of chi-square tests (<a href="#sec-bayescontingency" class="quarto-xref"><span>Section 17.4</span></a>), <span class="math inline">\(t\)</span>-tests (<a href="#sec-ttestbf" class="quarto-xref"><span>Section 17.5</span></a>), regression (<a href="#sec-bayesregression" class="quarto-xref"><span>Section 17.6</span></a>) and ANOVA (<a href="#sec-bayesanova" class="quarto-xref"><span>Section 17.7</span></a>).</p>
<section id="sec-basicbayes" class="level2 page-columns page-full" data-number="17.1">
<h2 data-number="17.1" class="anchored" data-anchor-id="sec-basicbayes"><span class="header-section-number">17.1</span> Probabilistic reasoning by rational agents</h2>
<p>From a Bayesian perspective, statistical inference is all about <em>belief revision</em>. I start out with a set of candidate hypotheses <span class="math inline">\(h\)</span> about the world. I don’t know which of these hypotheses is true, but I do have some beliefs about which hypotheses are plausible and which are not. When I observe the data <span class="math inline">\(d\)</span>, I have to revise those beliefs. If the data are consistent with a hypothesis, my belief in that hypothesis is strengthened. If the data are inconsistent with the hypothesis, my belief in that hypothesis is weakened. That’s it! At the end of this section I’ll give a precise description of how Bayesian reasoning works, but first I want to work through a simple example in order to introduce the key ideas. Consider the following reasoning problem:</p>
<blockquote class="blockquote">
<p><em>I’m carrying an umbrella. Do you think it will rain?</em></p>
</blockquote>
<p>In this problem, I have presented you with a single piece of data (<span class="math inline">\(d =\)</span> I’m carrying the umbrella), and I’m asking you to tell me your beliefs about whether it’s raining. You have two possible <strong><em>hypotheses</em></strong>, <span class="math inline">\(h\)</span>: either it rains today or it does not. How should you solve this problem?</p>
<section id="priors-what-you-believed-before" class="level3 page-columns page-full" data-number="17.1.1">
<h3 data-number="17.1.1" class="anchored" data-anchor-id="priors-what-you-believed-before"><span class="header-section-number">17.1.1</span> Priors: what you believed before</h3>
<p>The first thing you need to do is ignore what I told you about the umbrella, and write down your pre-existing beliefs about rain. This is important: if you want to be honest about how your beliefs have been revised in the light of new evidence, then you <em>must</em> say something about what you believed before those data appeared! So, what might you believe about whether it will rain today? You probably know that I live in Australia, and that much of Australia is hot and dry. And in fact you’re right: the city of Adelaide where I live has a Mediterranean climate, very similar to southern California, southern Europe or northern Africa. I’m writing this in January, and so you can assume it’s the middle of summer. In fact, you might have decided to take a quick look on Wikipedia<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> and discovered that Adelaide gets an average of 4.4 days of rain across the 31 days of January. Without knowing anything else, you might conclude that the probability of January rain in Adelaide is about 15%, and the probability of a dry day is 85%. If this is really what you believe about Adelaide rainfall (and now that I’ve told it to you, I’m betting that this really <em>is</em> what you believe) then what I have written here is your <strong><em>prior distribution</em></strong>, written <span class="math inline">\(P(h)\)</span>:</p>
<div class="no-row-height column-margin column-container"><div id="fn1"><p><sup>1</sup>&nbsp;<a href="http://en.wikipedia.org/wiki/Climate_of_Adelaide" class="uri">http://en.wikipedia.org/wiki/Climate_of_Adelaide</a>.</p></div></div><table class="caption-top table">
<thead>
<tr class="header">
<th>Hypothesis</th>
<th>Degree of Belief</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rainy day</td>
<td>0.15</td>
</tr>
<tr class="even">
<td>Dry day</td>
<td>0.85</td>
</tr>
</tbody>
</table>
</section>
<section id="likelihoods-theories-about-the-data" class="level3 page-columns page-full" data-number="17.1.2">
<h3 data-number="17.1.2" class="anchored" data-anchor-id="likelihoods-theories-about-the-data"><span class="header-section-number">17.1.2</span> Likelihoods: theories about the data</h3>
<p>To solve the reasoning problem, you need a theory about my behaviour. When does Danielle carry an umbrella? You might guess that I’m not a complete idiot,<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> and I try to carry umbrellas only on rainy days. On the other hand, you also know that I have young kids, and you wouldn’t be all that surprised to know that I’m pretty forgetful about this sort of thing. Let’s suppose that on rainy days I remember my umbrella about 30% of the time (I really am awful at this). But let’s say that on dry days I’m only about 5% likely to be carrying an umbrella. So you might write out a little table like this:</p>
<div class="no-row-height column-margin column-container"><div id="fn2"><p><sup>2</sup>&nbsp;It’s a leap of faith, I know, but let’s run with it okay?</p></div></div><table class="caption-top table">
<thead>
<tr class="header">
<th>Hypothesis</th>
<th>Umbrella</th>
<th>No umbrella</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rainy day</td>
<td>0.30</td>
<td>0.70</td>
</tr>
<tr class="even">
<td>Dry day</td>
<td>0.05</td>
<td>0.95</td>
</tr>
</tbody>
</table>
<p>It’s important to remember that each cell in this table describes your beliefs about what data <span class="math inline">\(d\)</span> will be observed, <em>given</em> the truth of a particular hypothesis <span class="math inline">\(h\)</span>. This “conditional probability” is written <span class="math inline">\(P(d|h)\)</span>, which you can read as “the probability of <span class="math inline">\(d\)</span> given <span class="math inline">\(h\)</span>”. In Bayesian statistics, this is referred to as the <strong><em>likelihood</em></strong> of data <span class="math inline">\(d\)</span> given hypothesis <span class="math inline">\(h\)</span>.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn3"><p><sup>3</sup>&nbsp;Um. I hate to bring this up, but some statisticians would object to me using the word “likelihood” here. The problem is that the word “likelihood” has a very specific meaning in frequentist statistics, and it’s not quite the same as what it means in Bayesian statistics. As far as I can tell, Bayesians didn’t originally have any agreed upon name for the likelihood, and so it became common practice for people to use the frequentist terminology. This wouldn’t have been a problem, except for the fact that the way that Bayesians use the word turns out to be quite different to the way frequentists do. This isn’t the place for yet another lengthy history lesson, but to put it crudely: when a Bayesian says “<em>a</em> likelihood function” they’re usually referring to one of the <em>rows</em> of the table. When a frequentist says the same thing, they’re referring to the same table, but to them “<em>a</em> likelihood function” almost always refers to one of the <em>columns</em>. This distinction matters in some contexts, but it’s not important for our purposes.</p></div></div></section>
<section id="the-joint-probability-of-data-and-hypothesis" class="level3" data-number="17.1.3">
<h3 data-number="17.1.3" class="anchored" data-anchor-id="the-joint-probability-of-data-and-hypothesis"><span class="header-section-number">17.1.3</span> The joint probability of data and hypothesis</h3>
<p>At this point, all the elements are in place. Having written down the priors and the likelihood, you have all the information you need to do Bayesian reasoning. The question now becomes, <em>how</em> do we use this information? As it turns out, there’s a very simple equation that we can use here, but it’s important that you understand why we use it, so I’m going to try to build it up from more basic ideas.</p>
<p>Let’s start out with one of the rules of probability theory. I listed it way back in <a href="09-probability.html#tbl-probrules" class="quarto-xref">Table&nbsp;<span>9.1</span></a>, but I didn’t make a big deal out of it at the time and you probably ignored it. The rule in question is the one that talks about the probability that <em>two</em> things are true. In our example, you might want to calculate the probability that today is rainy (i.e., hypothesis <span class="math inline">\(h\)</span> is true) <em>and</em> I’m carrying an umbrella (i.e., data <span class="math inline">\(d\)</span> is observed). The <strong><em>joint probability</em></strong> of the hypothesis and the data is written <span class="math inline">\(P(d,h)\)</span>, and you can calculate it by multiplying the prior <span class="math inline">\(P(h)\)</span> by the likelihood <span class="math inline">\(P(d|h)\)</span>. Mathematically, we say that: <span class="math display">\[
P(d,h) = P(d|h) P(h)
\]</span></p>
<p>So, what is the probability that today is a rainy day <em>and</em> I remember to carry an umbrella? As we discussed earlier, the prior tells us that the probability of a rainy day is 15%, and the likelihood tells us that the probability of me remembering my umbrella on a rainy day is 30%. So the probability that both of these things are true is calculated by multiplying the two: <span class="math display">\[
\begin{aligned}
P(\mbox{rainy}, \mbox{umbrella}) &amp;= P(\mbox{umbrella} | \mbox{rainy}) \times P(\mbox{rainy}) \\
&amp;= 0.30 \times 0.15 \\
&amp;= 0.045
\end{aligned}
\]</span></p>
<p>In other words, before being told anything about what actually happened, you think that there is a 4.5% probability that today will be a rainy day and that I will remember an umbrella. However, there are of course <em>four</em> possible things that could happen, right? So let’s repeat the exercise for all four. If we do that, we end up with the following table:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Umbrella</th>
<th>No-umbrella</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rainy</td>
<td>0.045</td>
<td>0.105</td>
</tr>
<tr class="even">
<td>Dry</td>
<td>0.0425</td>
<td>0.8075</td>
</tr>
</tbody>
</table>
<p>This table captures all the information about which of the four possibilities are likely. To really get the full picture, though, it helps to add the row totals and column totals. That gives us this table:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Umbrella</th>
<th>No-umbrella</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rainy</td>
<td>0.0450</td>
<td>0.1050</td>
<td>0.15</td>
</tr>
<tr class="even">
<td>Dry</td>
<td>0.0425</td>
<td>0.8075</td>
<td>0.85</td>
</tr>
<tr class="odd">
<td>Total</td>
<td>0.0875</td>
<td>0.9125</td>
<td>1</td>
</tr>
</tbody>
</table>
<p>This is a very useful table, so it’s worth taking a moment to think about what all these numbers are telling us. First, notice that the row sums aren’t telling us anything new at all. For example, the first row tells us that if we ignore all this umbrella business, the chance that today will be a rainy day is 15%. That’s not surprising, of course: that’s our prior. The important thing isn’t the number itself: rather, the important thing is that it gives us some confidence that our calculations are sensible! Now take a look at the column sums, and notice that they tell us something that we haven’t explicitly stated yet. In the same way that the row sums tell us the probability of rain, the column sums tell us the probability of me carrying an umbrella. Specifically, the first column tells us that on average (i.e., ignoring whether it’s a rainy day or not), the probability of me carrying an umbrella is 8.75%. Finally, notice that when we sum across all four logically-possible events, everything adds up to 1. In other words, what we have written down is a proper probability distribution defined over all possible combinations of data and hypothesis.</p>
<p>Now, because this table is so useful, I want to make sure you understand what all the elements correspond to, and how they are written:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Umbrella</th>
<th>No-umbrella</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rainy</td>
<td><span class="math inline">\(P\)</span>(Umbrella, Rainy)</td>
<td><span class="math inline">\(P\)</span>(No-umbrella, Rainy)</td>
<td><span class="math inline">\(P\)</span>(Rainy)</td>
</tr>
<tr class="even">
<td>Dry</td>
<td><span class="math inline">\(P\)</span>(Umbrella, Dry)</td>
<td><span class="math inline">\(P\)</span>(No-umbrella, Dry)</td>
<td><span class="math inline">\(P\)</span>(Dry)</td>
</tr>
<tr class="odd">
<td></td>
<td><span class="math inline">\(P\)</span>(Umbrella)</td>
<td><span class="math inline">\(P\)</span>(No-umbrella)</td>
<td></td>
</tr>
</tbody>
</table>
<p>Finally, let’s use “proper” statistical notation. In the rainy day problem, the data corresponds to the observation that I do or do not have an umbrella. So we’ll let <span class="math inline">\(d_1\)</span> refer to the possibility that you observe me carrying an umbrella, and <span class="math inline">\(d_2\)</span> refers to you observing me not carrying one. Similarly, <span class="math inline">\(h_1\)</span> is your hypothesis that today is rainy, and <span class="math inline">\(h_2\)</span> is the hypothesis that it is not. Using this notation, the table looks like this:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th><span class="math inline">\(d_1\)</span></th>
<th><span class="math inline">\(d_2\)</span></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(h_1\)</span></td>
<td><span class="math inline">\(P(h_1, d_1)\)</span></td>
<td><span class="math inline">\(P(h_1, d_2)\)</span></td>
<td><span class="math inline">\(P(h_1)\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(h_2\)</span></td>
<td><span class="math inline">\(P(h_2, d_1)\)</span></td>
<td><span class="math inline">\(P(h_2, d_2)\)</span></td>
<td><span class="math inline">\(P(h_2)\)</span></td>
</tr>
<tr class="odd">
<td></td>
<td><span class="math inline">\(P(d_1)\)</span></td>
<td><span class="math inline">\(P(d_2)\)</span></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="updating-beliefs-using-bayes-rule" class="level3 page-columns page-full" data-number="17.1.4">
<h3 data-number="17.1.4" class="anchored" data-anchor-id="updating-beliefs-using-bayes-rule"><span class="header-section-number">17.1.4</span> Updating beliefs using Bayes’ rule</h3>
<p>The table we laid out in the last section is a very powerful tool for solving the rainy day problem, because it considers all four logical possibilities and states exactly how confident you are in each of them before being given any data. It’s now time to consider what happens to our beliefs when we are actually given the data. In the rainy day problem, you are told that I really <em>am</em> carrying an umbrella. This is something of a surprising event: according to our table, the probability of me carrying an umbrella is only 8.75%. But that makes sense, right? A guy carrying an umbrella on a summer day in a hot dry city is pretty unusual, and so you really weren’t expecting that. Nevertheless, the problem tells you that it is true. No matter how unlikely you thought it was, you must now adjust your beliefs to accommodate the fact that you now <em>know</em> that I have an umbrella.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> To reflect this new knowledge, our <em>revised</em> table must have the following numbers:</p>
<div class="no-row-height column-margin column-container"><div id="fn4"><p><sup>4</sup>&nbsp;If we were being a bit more sophisticated, we could extend the example to accommodate the possibility that I’m lying about the umbrella. But let’s keep things simple, shall we?</p></div></div><table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Umbrella</th>
<th>No-umbrella</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rainy</td>
<td></td>
<td>0</td>
</tr>
<tr class="even">
<td>Dry</td>
<td></td>
<td>0</td>
</tr>
<tr class="odd">
<td>Total</td>
<td>1</td>
<td>0</td>
</tr>
</tbody>
</table>
<p>In other words, the facts have eliminated any possibility of “no umbrella”, so we have to put zeros into any cell in the table that implies that I’m not carrying an umbrella. Also, you know for a fact that I am carrying an umbrella, so the column sum on the left must be 1 to correctly describe the fact that <span class="math inline">\(P(\mbox{umbrella})=1\)</span>.</p>
<p>What two numbers should we put in the empty cells? Again, let’s not worry about the maths, and instead think about our intuitions. When we wrote out our table the first time, it turned out that those two cells had almost identical numbers, right? We worked out that the joint probability of “rain and umbrella” was 4.5%, and the joint probability of “dry and umbrella” was 4.25%. In other words, before I told you that I am in fact carrying an umbrella, you’d have said that these two events were almost identical in probability, yes? But notice that <em>both</em> of these possibilities are consistent with the fact that I actually am carrying an umbrella. From the perspective of these two possibilities, very little has changed. I hope you’d agree that it’s <em>still</em> true that these two possibilities are equally plausible. So what we expect to see in our final table is some numbers that preserve the fact that “rain and umbrella” is <em>slightly</em> more plausible than “dry and umbrella”, while still ensuring that the numbers in the table add up. Something like this, perhaps?</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Umbrella</th>
<th>No-umbrella</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rainy</td>
<td>0.514</td>
<td>0</td>
</tr>
<tr class="even">
<td>Dry</td>
<td>0.486</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Total</td>
<td>1</td>
<td>0</td>
</tr>
</tbody>
</table>
<p>What this table is telling you is that, after being told that I’m carrying an umbrella, you believe that there’s a 51.4% chance that today will be a rainy day, and a 48.6% chance that it won’t. That’s the answer to our problem! The <strong><em>posterior probability</em></strong> of rain <span class="math inline">\(P(h|d)\)</span> given that I am carrying an umbrella is 51.4%.</p>
<p>How did I calculate these numbers? You can probably guess. To work out that there was a 0.514 probability of “rain”, all I did was take the 0.045 probability of “rain and umbrella” and divide it by the 0.0875 chance of “umbrella”. This produces a table that satisfies our need to have everything sum to 1, and our need not to interfere with the relative plausibility of the two events that are actually consistent with the data. To say the same thing using fancy statistical jargon, what I’ve done here is divide the joint probability of the hypothesis and the data <span class="math inline">\(P(d,h)\)</span> by the <strong><em>marginal probability</em></strong> of the data <span class="math inline">\(P(d)\)</span>, and this is what gives us the posterior probability of the hypothesis <em>given</em> that we know the data have been observed. To write this as an equation:<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> <span class="math display">\[
P(h | d) = \frac{P(d,h)}{P(d)}
\]</span></p>
<div class="no-row-height column-margin column-container"><div id="fn5"><p><sup>5</sup>&nbsp;You might notice that this equation is actually a restatement of the same basic rule I listed at the start of the last section. If you multiply both sides of the equation by <span class="math inline">\(P(d)\)</span>, then you get <span class="math inline">\(P(d) P(h|d) = P(d,h)\)</span>, which is the rule for how joint probabilities are calculated. So I’m not actually introducing any “new” rules here, I’m just using the same rule in a different way.</p></div></div><p>However, remember what I said at the start of the last section, namely that the joint probability <span class="math inline">\(P(d,h)\)</span> is calculated by multiplying the prior <span class="math inline">\(P(h)\)</span> by the likelihood <span class="math inline">\(P(d|h)\)</span>. In real life, the things we actually know how to write down are the priors and the likelihood, so let’s substitute those back into the equation. This gives us the following formula for the posterior probability: <span class="math display">\[
P(h | d) = \frac{P(d|h) P(h)}{P(d)}
\]</span></p>
<p>And this formula, folks, is known as <strong><em>Bayes’ rule</em></strong>. It describes how a learner starts out with prior beliefs about the plausibility of different hypotheses, and tells you how those beliefs should be revised in the face of data. In the Bayesian paradigm, all statistical inference flows from this one simple rule.</p>
</section>
</section>
<section id="sec-bayesianhypothesistests" class="level2 page-columns page-full" data-number="17.2">
<h2 data-number="17.2" class="anchored" data-anchor-id="sec-bayesianhypothesistests"><span class="header-section-number">17.2</span> Bayesian hypothesis tests</h2>
<p>In <a href="./11-hypothesistesting.html">Hypothesis testing</a> I described the orthodox approach to hypothesis testing. It took an entire chapter to describe, because null hypothesis testing is a very elaborate contraption that people find very hard to make sense of. In contrast, the Bayesian approach to hypothesis testing is incredibly simple. Let’s pick a setting that is closely analogous to the orthodox scenario. There are two hypotheses that we want to compare, a null hypothesis <span class="math inline">\(h_0\)</span> and an alternative hypothesis <span class="math inline">\(h_1\)</span>. Prior to running the experiment we have some beliefs <span class="math inline">\(P(h)\)</span> about which hypotheses are true. We run an experiment and obtain data <span class="math inline">\(d\)</span>. Unlike frequentist statistics, Bayesian statistics does allow us to talk about the probability that the null hypothesis is true. Better yet, it allows us to calculate the <strong><em>posterior probability of the null hypothesis</em></strong>, using Bayes’ rule: <span class="math display">\[
P(h_0 | d) = \frac{P(d|h_0) P(h_0)}{P(d)}
\]</span></p>
<p>This formula tells us exactly how much belief we should have in the null hypothesis after having observed the data <span class="math inline">\(d\)</span>. Similarly, we can work out how much belief to place in the alternative hypothesis using essentially the same equation. All we do is change the subscript: <span class="math display">\[
P(h_1 | d) = \frac{P(d|h_1) P(h_1)}{P(d)}
\]</span></p>
<p>It’s all so simple that I feel like an idiot even bothering to write these equations down, since all I’m doing is copying Bayes’ rule from the previous section.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn6"><p><sup>6</sup>&nbsp;Obviously, this is a highly simplified story. All the complexity of real life Bayesian hypothesis testing comes down to how you calculate the likelihood <span class="math inline">\(P(d|h)\)</span> when the hypothesis <span class="math inline">\(h\)</span> is a complex and vague thing. I’m not going to talk about those complexities in this book, but I do want to highlight that although this simple story is true as far as it goes, real life is messier than I’m able to cover in an introductory stats textbook.</p></div></div><section id="the-bayes-factor" class="level3" data-number="17.2.1">
<h3 data-number="17.2.1" class="anchored" data-anchor-id="the-bayes-factor"><span class="header-section-number">17.2.1</span> The Bayes factor</h3>
<p>In practice, most Bayesian data analysts tend not to talk in terms of the raw posterior probabilities <span class="math inline">\(P(h_0|d)\)</span> and <span class="math inline">\(P(h_1|d)\)</span>. Instead, we tend to talk in terms of the <strong><em>posterior odds</em></strong> ratio. Think of it like betting. Suppose, for instance, the posterior probability of the null hypothesis is 25%, and the posterior probability of the alternative is 75%. The alternative hypothesis is three times as probable as the null, so we say that the <em>odds</em> are 3:1 in favour of the alternative. Mathematically, all we have to do to calculate the posterior odds is divide one posterior probability by the other: <span class="math display">\[
\frac{P(h_1 | d)}{P(h_0 | d)} = \frac{0.75}{0.25} = 3
\]</span></p>
<p>Or, to write the same thing in terms of the equations above: <span class="math display">\[
\frac{P(h_1 | d)}{P(h_0 | d)} = \frac{P(d|h_1)}{P(d|h_0)} \times \frac{P(h_1)}{P(h_0)}
\]</span></p>
<p>Actually, this equation is worth expanding on. There are three different terms here that you should know. On the left hand side, we have the posterior odds, which tells you what you believe about the relative plausibility of the null hypothesis and the alternative hypothesis <em>after</em> seeing the data. On the right hand side, we have the <strong><em>prior odds</em></strong>, which indicates what you thought <em>before</em> seeing the data. In the middle, we have the <strong><em>Bayes factor</em></strong>, which describes the amount of evidence provided by the data:</p>
<p><span class="math display">\[
\underbrace{\frac{P(h_1 | d)}{P(h_0 | d)}}_{\text{Posterior odds}} = \underbrace{\frac{P(d|h_1)}{P(d|h_0)}}_{\text{Bayes factor}} \times \underbrace{\frac{P(h_1)}{P(h_0)}}_{\text{Prior odds}}
\]</span></p>
<p>The Bayes factor (sometimes abbreviated as <strong><em>BF</em></strong>) has a special place in Bayesian hypothesis testing, because it serves a similar role to the <span class="math inline">\(p\)</span>-value in orthodox hypothesis testing: it quantifies the strength of evidence provided by the data, and as such it is the Bayes factor that people tend to report when running a Bayesian hypothesis test. The reason for reporting Bayes factors rather than posterior odds is that different researchers will have different priors. Some people might have a strong bias to believe the null hypothesis is true, others might have a strong bias to believe it is false. Because of this, the polite thing for an applied researcher to do is report the Bayes factor. That way, anyone reading the paper can multiply the Bayes factor by their own <em>personal</em> prior odds, and they can work out for themselves what the posterior odds would be. In any case, by convention we like to pretend that we give equal consideration to both the null hypothesis and the alternative, in which case the prior odds equals 1, and the posterior odds becomes the same as the Bayes factor.</p>
</section>
<section id="interpreting-bayes-factors" class="level3" data-number="17.2.2">
<h3 data-number="17.2.2" class="anchored" data-anchor-id="interpreting-bayes-factors"><span class="header-section-number">17.2.2</span> Interpreting Bayes factors</h3>
<p>One of the really nice things about the Bayes factor is that the numbers are inherently meaningful. If you run an experiment and you compute a Bayes factor of 4, it means that the evidence provided by your data corresponds to betting odds of 4:1 in favour of the alternative. However, there have been some attempts to quantify the standards of evidence that would be considered meaningful in a scientific context. The two most widely used are from <span class="citation" data-cites="Jeffreys1961">Jeffreys (<a href="references.html#ref-Jeffreys1961" role="doc-biblioref">1961</a>)</span> and <span class="citation" data-cites="Kass1995">Kass &amp; Raftery (<a href="references.html#ref-Kass1995" role="doc-biblioref">1995</a>)</span>. Of the two, I tend to prefer the <span class="citation" data-cites="Kass1995">Kass &amp; Raftery (<a href="references.html#ref-Kass1995" role="doc-biblioref">1995</a>)</span> table because it’s a bit more conservative. So here it is:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Bayes factor</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1 - 3</td>
<td>Negligible evidence</td>
</tr>
<tr class="even">
<td>3 - 20</td>
<td>Positive evidence</td>
</tr>
<tr class="odd">
<td>20 - 150</td>
<td>Strong evidence</td>
</tr>
<tr class="even">
<td>$&gt;$150</td>
<td>Very strong evidence</td>
</tr>
</tbody>
</table>
<p>And to be perfectly honest, I think that even the Kass and Raftery standards are being a bit charitable. If it were up to me, I’d have called the “positive evidence” category “weak evidence”. To me, anything in the range 3:1 to 20:1 is “weak” or “modest” evidence at best. But there are no hard and fast rules here: what counts as strong or weak evidence depends entirely on how conservative you are, and upon the standards that your community insists upon before it is willing to label a finding as “true”.</p>
<p>In any case, note that all the numbers listed above make sense if the Bayes factor is greater than 1 (i.e., the evidence favours the alternative hypothesis). However, one big practical advantage of the Bayesian approach relative to the orthodox approach is that it also allows you to quantify evidence <em>for</em> the null. When that happens, the Bayes factor will be less than 1. You can choose to report a Bayes factor less than 1, but to be honest I find it confusing. For example, suppose that the likelihood of the data under the null hypothesis <span class="math inline">\(P(d|h_0)\)</span> is equal to 0.2, and the corresponding likelihood <span class="math inline">\(P(d|h_1)\)</span> under the alternative hypothesis is 0.1. Using the equations given above, the Bayes factor here would be: <span class="math display">\[
\mbox{BF} = \frac{P(d|h_1)}{P(d|h_0)} = \frac{0.1}{0.2} = 0.5
\]</span></p>
<p>Read literally, this result tells us that the evidence in favour of the alternative is 0.5 to 1. I find this hard to understand. To me, it makes a lot more sense to turn the equation “upside down”, and report the amount of evidence in favour of the <em>null</em>. In other words, what we calculate is this: <span class="math display">\[
\mbox{BF}^\prime = \frac{P(d|h_0)}{P(d|h_1)} = \frac{0.2}{0.1} = 2
\]</span></p>
<p>And what we would report is a Bayes factor of 2:1 in favour of the null. Much easier to understand, and you can interpret this using the table above.</p>
</section>
</section>
<section id="sec-whybayes" class="level2 page-columns page-full" data-number="17.3">
<h2 data-number="17.3" class="anchored" data-anchor-id="sec-whybayes"><span class="header-section-number">17.3</span> Why be a Bayesian?</h2>
<p>Up to this point I’ve focused exclusively on the logic underpinning Bayesian statistics. We’ve talked about the idea of “probability as a degree of belief”, and what it implies about how a rational agent should reason about the world. The question that you have to answer for yourself is this: how do <em>you</em> want to do your statistics? Do you want to be an orthodox statistician, relying on sampling distributions and <span class="math inline">\(p\)</span>-values to guide your decisions? Or do you want to be a Bayesian, relying on Bayes factors and the rules for rational belief revision? And to be perfectly honest, I can’t answer this question for you. Ultimately it depends on what you think is right. It’s your call, and your call alone. That being said, I can talk a little about why <em>I</em> prefer the Bayesian approach.</p>
<section id="statistics-that-mean-what-you-think-they-mean" class="level3 page-columns page-full" data-number="17.3.1">
<h3 data-number="17.3.1" class="anchored" data-anchor-id="statistics-that-mean-what-you-think-they-mean"><span class="header-section-number">17.3.1</span> Statistics that mean what you think they mean</h3>
<div class="pullquote">
<p><em>You keep using that word. I do not think it means what you think it means.</em></p>
<p>— Inigo Montoya, The Princess Bride</p>
<p><a href="http://www.imdb.com/title/tt0093779/quotes" class="uri">http://www.imdb.com/title/tt0093779/quotes</a>. I should note in passing that I’m not the first person to use this quote to complain about frequentist methods. Rich Morey and colleagues had the idea first. I’m shamelessly stealing it because it’s such an awesome pull quote to use in this context and I refuse to miss any opportunity to quote <em>The Princess Bride</em>.</p>
</div>
<p>To me, one of the biggest advantages to the Bayesian approach is that it answers the right questions. Within the Bayesian framework, it is perfectly sensible and allowable to refer to “the probability that a hypothesis is true”. You can even try to calculate this probability. Ultimately, isn’t that what you <em>want</em> your statistical tests to tell you? To an actual human being, this would seem to be the whole <em>point</em> of doing statistics: to determine what is true and what isn’t. Any time that you aren’t exactly sure about what the truth is, you should use the language of probability theory to say things like “there is an 80% chance that Theory A is true, but a 20% chance that Theory B is true instead”.</p>
<p>This seems so obvious to a human, yet it is explicitly forbidden within the orthodox framework. To a frequentist, such statements are a nonsense because “the theory is true” is not a repeatable event. A theory is true or it is not, and no probabilistic statements are allowed, no matter how much you might want to make them. There’s a reason why, back in <a href="11-hypothesistesting.html#sec-pvalue" class="quarto-xref"><span>Section 11.5</span></a>, I repeatedly warned you <em>not</em> to interpret the <span class="math inline">\(p\)</span>-value as the probability that the null hypothesis is true. There’s a reason why almost every textbook on statistics is forced to repeat that warning. It’s because people desperately <em>want</em> that to be the correct interpretation. Frequentist dogma notwithstanding, a lifetime of experience of teaching undergraduates and of doing data analysis on a daily basis suggests to me that most actual humans think that “the probability that the hypothesis is true” is not only meaningful, it’s the thing we care <em>most</em> about. It’s such an appealing idea that even trained statisticians fall prey to the mistake of trying to interpret a <span class="math inline">\(p\)</span>-value this way. For example, here is a quote from an official Newspoll report in 2013, explaining how to interpret their (frequentist) data analysis:<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn7"><p><sup>7</sup>&nbsp;<a href="http://about.abc.net.au/reports-publications/appreciation-survey-summary-report-2013/" class="uri">http://about.abc.net.au/reports-publications/appreciation-survey-summary-report-2013/</a>.</p></div></div><blockquote class="blockquote">
<p>Throughout the report, where relevant, statistically significant changes have been noted. All significance tests have been based on the 95 percent level of confidence. <strong>This means that if a change is noted as being statistically significant, there is a 95 percent probability that a real change has occurred</strong>, and is not simply due to chance variation. (emphasis added)</p>
</blockquote>
<p>Nope! That’s <em>not</em> what <span class="math inline">\(p&lt;.05\)</span> means. That’s <em>not</em> what 95% confidence means to a frequentist statistician. The bolded section is just plain wrong. Orthodox methods cannot tell you that “there is a 95% chance that a real change has occurred”, because this is not the kind of event to which frequentist probabilities may be assigned. To an ideological frequentist, this sentence should be meaningless. Even if you’re a more pragmatic frequentist, it’s still the wrong definition of a <span class="math inline">\(p\)</span>-value. It is simply not an allowed or correct thing to say if you want to rely on orthodox statistical tools.</p>
<p>On the other hand, let’s suppose you are a Bayesian. Although the bolded passage is the wrong definition of a <span class="math inline">\(p\)</span>-value, it’s pretty much exactly what a Bayesian means when they say that the posterior probability of the alternative hypothesis is greater than 95%. And here’s the thing. If the Bayesian posterior is actually the thing you <em>want</em> to report, why are you even trying to use orthodox methods? If you want to make Bayesian claims, all you have to do is be a Bayesian and use Bayesian tools.</p>
<p>Speaking for myself, I found this to be the most liberating thing about switching to the Bayesian view. Once you’ve made the jump, you no longer have to wrap your head around counterintuitive definitions of <span class="math inline">\(p\)</span>-values. You don’t have to bother remembering why you can’t say that you’re 95% confident that the true mean lies within some interval. All you have to do is be honest about what you believed before you ran the study, and then report what you learned from doing it. Sounds nice, doesn’t it? To me, this is the big promise of the Bayesian approach: you do the analysis you really want to do, and express what you really believe the data are telling you.</p>
</section>
<section id="evidentiary-standards-you-can-believe" class="level3" data-number="17.3.2">
<h3 data-number="17.3.2" class="anchored" data-anchor-id="evidentiary-standards-you-can-believe"><span class="header-section-number">17.3.2</span> Evidentiary standards you can believe</h3>
<div class="pullquote">
<p><em>If [<span class="math inline">\(p\)</span>] is below .02 it is strongly indicated that the [null] hypothesis fails to account for the whole of the facts. We shall not often be astray if we draw a conventional line at .05 and consider that [smaller values of <span class="math inline">\(p\)</span>] indicate a real discrepancy.</em></p>
<p>— Sir Ronald <span class="citation" data-cites="Fisher1925">Fisher (<a href="references.html#ref-Fisher1925" role="doc-biblioref">1925</a>)</span></p>
</div>
<p>Consider the quote above by Sir Ronald Fisher, one of the founders of what has become the orthodox approach to statistics. If anyone has ever been entitled to express an opinion about the intended function of <span class="math inline">\(p\)</span>-values, it’s Fisher. In this passage, taken from his classic guide <em>Statistical Methods for Research Workers</em>, he’s pretty clear about what it means to reject a null hypothesis at <span class="math inline">\(p&lt;.05\)</span>. In his opinion, if we take <span class="math inline">\(p&lt;.05\)</span> to mean there is “a real effect”, then “we shall not often be astray”. This view is hardly unusual: in my experience, most practitioners express views very similar to Fisher’s. In essence, the <span class="math inline">\(p&lt;.05\)</span> convention is assumed to represent a fairly stringent evidentiary standard.</p>
<p>Well, how true is that? One way to approach this question is to try to convert <span class="math inline">\(p\)</span>-values to Bayes factors, and see how the two compare. It’s not an easy thing to do because a <span class="math inline">\(p\)</span>-value is a fundamentally different kind of calculation to a Bayes factor, and they don’t measure the same thing. However, there have been some attempts to work out the relationship between the two, and it’s somewhat surprising. For example, <span class="citation" data-cites="Johnson2013">Johnson (<a href="references.html#ref-Johnson2013" role="doc-biblioref">2013</a>)</span> presents a pretty compelling case that (for <span class="math inline">\(t\)</span>-tests at least) the <span class="math inline">\(p&lt;.05\)</span> threshold corresponds roughly to a Bayes factor of somewhere between 3:1 and 5:1 in favour of the alternative. If that’s right, then Fisher’s claim is a bit of a stretch. Let’s suppose that the null hypothesis is true about half the time (i.e., the prior probability of <span class="math inline">\(H_0\)</span> is 0.5), and we use those numbers to work out the posterior probability of the null hypothesis given that it has been rejected at <span class="math inline">\(p&lt;.05\)</span>. Using the data from <span class="citation" data-cites="Johnson2013">Johnson (<a href="references.html#ref-Johnson2013" role="doc-biblioref">2013</a>)</span>, we see that if you reject the null at <span class="math inline">\(p&lt;.05\)</span>, you’ll be correct about 80% of the time. I don’t know about you, but in my opinion an evidentiary standard that ensures you’ll be wrong on 20% of your decisions isn’t good enough. The fact remains that, quite contrary to Fisher’s claim, if you reject at <span class="math inline">\(p&lt;.05\)</span> you shall quite often go astray. It’s not a very stringent evidentiary threshold at all.</p>
</section>
<section id="the-p-value-is-a-lie" class="level3 page-columns page-full" data-number="17.3.3">
<h3 data-number="17.3.3" class="anchored" data-anchor-id="the-p-value-is-a-lie"><span class="header-section-number">17.3.3</span> The <span class="math inline">\(p\)</span>-value is a lie</h3>
<div class="pullquote">
<p><em>The cake is a lie.</em><br>
<em>The cake is a lie.</em><br>
<em>The cake is a lie.</em><br>
<em>The cake is a lie.</em></p>
<p>— Portal</p>
<p><a href="http://knowyourmeme.com/memes/the-cake-is-a-lie" class="uri">http://knowyourmeme.com/memes/the-cake-is-a-lie</a>.</p>
</div>
<p>Okay, at this point you might be thinking that the real problem is not with orthodox statistics, just the <span class="math inline">\(p&lt;.05\)</span> standard. In one sense, that’s true. The recommendation that <span class="citation" data-cites="Johnson2013">Johnson (<a href="references.html#ref-Johnson2013" role="doc-biblioref">2013</a>)</span> gives is not that “everyone must be a Bayesian now”. Instead, the suggestion is that it would be wiser to shift the conventional standard to something like a <span class="math inline">\(p&lt;.01\)</span> level. That’s not an unreasonable view to take, but in my view the problem is a little more severe than that. In my opinion, there’s a fairly big problem built into the way most (but not all) orthodox hypothesis tests are constructed. They are grossly naive about how humans actually do research, and because of this most <span class="math inline">\(p\)</span>-values are wrong.</p>
<p>Sounds like an absurd claim, right? Well, consider the following scenario. You’ve come up with a really exciting research hypothesis and you design a study to test it. You’re very diligent, so you run a power analysis to work out what your sample size should be, and you run the study. You run your hypothesis test and out pops a <span class="math inline">\(p\)</span>-value of 0.072. Really bloody annoying, right?</p>
<p>What should you do? Here are some possibilities:</p>
<ol type="1">
<li>You conclude that there is no effect, and try to publish it as a null result.</li>
<li>You guess that there might be an effect, and try to publish it as a “borderline significant” result.</li>
<li>You give up and try a new study.</li>
<li>You collect some more data to see if the <span class="math inline">\(p\)</span> value goes up or (preferably!) drops below the “magic” criterion of <span class="math inline">\(p&lt;.05\)</span>.</li>
</ol>
<p>Which would <em>you</em> choose? Before reading any further, I urge you to take some time to think about it. Be honest with yourself. But don’t stress about it too much, because you’re screwed no matter what you choose. Based on my own experiences as an author, reviewer and editor, as well as stories I’ve heard from others, here’s what will happen in each case:</p>
<ol type="1">
<li>Let’s start with option 1. If you try to publish it as a null result, the paper will struggle to be published. Some reviewers will think that <span class="math inline">\(p=.072\)</span> is not really a null result. They’ll argue it’s borderline significant. Other reviewers will agree it’s a null result, but will claim that even though some null results <em>are</em> publishable, yours isn’t. One or two reviewers might even be on your side, but you’ll be fighting an uphill battle to get it through.</li>
<li>Okay, let’s think about option number 2. Suppose you try to publish it as a borderline significant result. Some reviewers will claim that it’s a null result and should not be published. Others will claim that the evidence is ambiguous, and that you should collect more data until you get a clear significant result. Again, the publication process does not favour you.</li>
<li>Given the difficulties in publishing an “ambiguous” result like <span class="math inline">\(p=.072\)</span>, option number 3 might seem tempting: give up and do something else. But that’s a recipe for career suicide. If you give up and try a new project every time you find yourself faced with ambiguity, your work will never be published. And if you’re in academia without a publication record you can lose your job. So that option is out.</li>
<li>It looks like you’re stuck with option 4. You don’t have conclusive results, so you decide to collect some more data and re-run the analysis. Seems sensible, but unfortunately for you, if you do this all of your <span class="math inline">\(p\)</span>-values are now incorrect. <em>All</em> of them. Not just the <span class="math inline">\(p\)</span>-values that you calculated for <em>this</em> study. All of them. All the <span class="math inline">\(p\)</span>-values you calculated in the past and all the <span class="math inline">\(p\)</span>-values you will calculate in the future. Fortunately, no-one will notice. You’ll get published, and you’ll have lied.</li>
</ol>
<p>Wait, what? How can that last part be true? I mean, it sounds like a perfectly reasonable strategy doesn’t it? You collected some data, the results weren’t conclusive, so now what you want to do is collect more data until the results <em>are</em> conclusive. What’s wrong with that?</p>
<p>Honestly, there’s nothing wrong with it. It’s a reasonable, sensible and rational thing to do. In real life, this is exactly what every researcher does. Unfortunately, the theory of null hypothesis testing as I described it in <a href="./11-hypothesistesting.html">Hypothesis testing</a> <em>forbids</em> you from doing this.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> The reason is that the theory assumes that the experiment is finished and all the data are in. And because it assumes the experiment is over, it only considers <em>two</em> possible decisions. If you’re using the conventional <span class="math inline">\(p&lt;.05\)</span> threshold, those decisions are:</p>
<div class="no-row-height column-margin column-container"><div id="fn8"><p><sup>8</sup>&nbsp;In the interests of being completely honest, I should acknowledge that not all orthodox statistical tests rely on this silly assumption. There are a number of <em>sequential analysis</em> tools that are sometimes used in clinical trials and the like. These methods are built on the assumption that data are analysed as they arrive, and these tests aren’t horribly broken in the way I’m complaining about here. However, sequential analysis methods are constructed in a very different fashion to the “standard” version of null hypothesis testing. They don’t make it into any introductory textbooks, and they’re not very widely used in the psychological literature. The concern I’m raising here is valid for every single orthodox test I’ve presented so far, and for almost every test I’ve seen reported in the papers I read.</p></div></div><table class="caption-top table">
<thead>
<tr class="header">
<th>Outcome</th>
<th>Action</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(p\)</span> less than .05</td>
<td>Reject the null</td>
</tr>
<tr class="even">
<td><span class="math inline">\(p\)</span> greater than .05</td>
<td>Retain the null</td>
</tr>
</tbody>
</table>
<p>What <em>you’re</em> doing is adding a third possible action to the decision making problem. Specifically, what you’re doing is using the <span class="math inline">\(p\)</span>-value itself as a reason to justify continuing the experiment. And as a consequence you’ve transformed the decision-making procedure into one that looks more like this:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Outcome</th>
<th>Action</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(p\)</span> less than .05</td>
<td>Stop the experiment and reject the null</td>
</tr>
<tr class="even">
<td><span class="math inline">\(p\)</span> between .05 and .1</td>
<td>Continue the experiment</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(p\)</span> greater than .1</td>
<td>Stop the experiment and retain the null</td>
</tr>
</tbody>
</table>
<p>The “basic” theory of null hypothesis testing isn’t built to handle this sort of thing, not in the form I described back in <a href="./11-hypothesistesting.html">Hypothesis testing</a>. If you’re the kind of person who would choose to “collect more data” in real life, it implies that you are <em>not</em> making decisions in accordance with the rules of null hypothesis testing. Even if you happen to arrive at the same decision as the hypothesis test, you aren’t following the decision <em>process</em> it implies, and it’s this failure to follow the process that is causing the problem.<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a> Your <span class="math inline">\(p\)</span>-values are a lie.</p>
<div class="no-row-height column-margin column-container"><div id="fn9"><p><sup>9</sup>&nbsp;A related problem: <a href="http://xkcd.com/1478/" class="uri">http://xkcd.com/1478/</a>.</p></div></div><p>Worse yet, they’re a lie in a dangerous way, because they’re all <em>too small</em>. To give you a sense of just how bad it can be, consider the following (worst case) scenario. Imagine you’re a really super-enthusiastic researcher on a tight budget who didn’t pay any attention to my warnings above. You design a study comparing two groups. You desperately want to see a significant result at the <span class="math inline">\(p&lt;.05\)</span> level, but you really don’t want to collect any more data than you have to (because it’s expensive). In order to cut costs, you start collecting data, but every time a new observation arrives you run a <span class="math inline">\(t\)</span>-test on your data. If the <span class="math inline">\(t\)</span>-test says <span class="math inline">\(p&lt;.05\)</span> then you stop the experiment and report a significant result. If not, you keep collecting data. You keep doing this until you reach your pre-defined spending limit for this experiment. Let’s say that limit kicks in at <span class="math inline">\(N=1000\)</span> observations. As it turns out, the truth of the matter is that there is no real effect to be found: the null hypothesis is true. So, what’s the chance that you’ll make it to the end of the experiment and (correctly) conclude that there is no effect? In an ideal world, the answer here should be 95%. After all, the whole <em>point</em> of the <span class="math inline">\(p&lt;.05\)</span> criterion is to control the Type I error rate at 5%, so what we’d hope is that there’s only a 5% chance of falsely rejecting the null hypothesis in this situation. However, there’s no guarantee that will be true. You’re breaking the rules: you’re running tests repeatedly, “peeking” at your data to see if you’ve gotten a significant result, and all bets are off.</p>
<p>So how bad is it? The original edition of this book answers this question with a figure (<code>fig:type1</code>) built from a two-stage simulation: <code>bayesnhst.R</code> fits <span class="math inline">\(1000\)</span> independent-samples <span class="math inline">\(t\)</span>-tests <em>and</em> <span class="math inline">\(1000\)</span> Bayesian <span class="math inline">\(t\)</span>-tests (via <code>ttestBF()</code>) at every sample size from <span class="math inline">\(N=1\)</span> up to <span class="math inline">\(N=1000\)</span>, repeated over <span class="math inline">\(1000\)</span> simulated experiments – roughly a million calls to <code>ttestBF()</code> in total – and <code>falsepositives.R</code> turns the results into a plot of the cumulative Type I error rate as a function of how long you keep “peeking”. That’s far too expensive to re-run live for this book (<code>ttestBF()</code> alone would need on the order of a million evaluations), so the figure isn’t reproduced here. The punchline, though, is worth keeping regardless: if you peek at your data after every single observation and use <span class="math inline">\(p&lt;.05\)</span> as your stopping rule, there is a 49% chance that you will make a Type I error – nearly ten times the nominal 5% rate. If you use the same peeking strategy but with a Bayes-factor-based stopping rule instead (stop and reject the null once the Bayes factor favours the alternative by 3:1 or more, or stop and retain the null once it favours the null by 3:1 or more), the Type I error rate under continuous peeking stays far below 49%, even though Bayesian methods were never designed with Type I error control in mind.</p>
<p>In some ways, this is remarkable. The entire <em>point</em> of orthodox null hypothesis testing is to control the Type I error rate. Bayesian methods aren’t actually designed to do this at all. Yet, as it turns out, when faced with a “trigger happy” researcher who keeps running hypothesis tests as the data come in, the Bayesian approach is much more effective. Even the 3:1 standard, which most Bayesians would consider unacceptably lax, is much safer than the <span class="math inline">\(p&lt;.05\)</span> rule.</p>
</section>
<section id="is-it-really-this-bad" class="level3 page-columns page-full" data-number="17.3.4">
<h3 data-number="17.3.4" class="anchored" data-anchor-id="is-it-really-this-bad"><span class="header-section-number">17.3.4</span> Is it really this bad?</h3>
<p>The example I gave in the previous section is a pretty extreme situation. In real life, people don’t run hypothesis tests every time a new observation arrives. So it’s not fair to say that the <span class="math inline">\(p&lt;.05\)</span> threshold “really” corresponds to a 49% Type I error rate (i.e., <span class="math inline">\(p=.49\)</span>). But the fact remains that if you want your <span class="math inline">\(p\)</span>-values to be honest, then you either have to switch to a completely different way of doing hypothesis tests, or you must enforce a strict rule: <em>no peeking</em>. You are <em>not</em> allowed to use the data to decide when to terminate the experiment. You are <em>not</em> allowed to look at a “borderline” <span class="math inline">\(p\)</span>-value and decide to collect more data. You aren’t even allowed to change your data analysis strategy after looking at data. You are strictly required to follow these rules, otherwise the <span class="math inline">\(p\)</span>-values you calculate will be nonsense.</p>
<p>And yes, these rules are surprisingly strict. As a class exercise a couple of years back, I asked students to think about this scenario. Suppose you started running your study with the intention of collecting <span class="math inline">\(N=80\)</span> people. When the study starts out you follow the rules, refusing to look at the data or run any tests. But when you reach <span class="math inline">\(N=50\)</span> your willpower gives in… and you take a peek. Guess what? You’ve got a significant result! Now, sure, you know you <em>said</em> that you’d keep running the study out to a sample size of <span class="math inline">\(N=80\)</span>, but it seems sort of pointless now, right? The result is significant with a sample size of <span class="math inline">\(N=50\)</span>, so wouldn’t it be wasteful and inefficient to keep collecting data? Aren’t you tempted to stop? Just a little? Well, keep in mind that if you do, your Type I error rate at <span class="math inline">\(p&lt;.05\)</span> just ballooned out to 8%. When you report <span class="math inline">\(p&lt;.05\)</span> in your paper, what you’re <em>really</em> saying is <span class="math inline">\(p&lt;.08\)</span>. That’s how bad the consequences of “just one peek” can be.</p>
<p>Now consider this … the scientific literature is filled with <span class="math inline">\(t\)</span>-tests, ANOVAs, regressions and chi-square tests. When I wrote this book I didn’t pick these tests arbitrarily. The reason why these four tools appear in most introductory statistics texts is that these are the bread and butter tools of science. None of these tools include a correction to deal with “data peeking”: they all assume that you’re not doing it. But how realistic is that assumption? In real life, how many people do you think have “peeked” at their data before the experiment was finished and adapted their subsequent behaviour after seeing what the data looked like? Except when the sampling procedure is fixed by an external constraint, I’m guessing the answer is “most people have done it”. If that has happened, you can infer that the reported <span class="math inline">\(p\)</span>-values are wrong. Worse yet, because we don’t know what decision process they actually followed, we have no way to know what the <span class="math inline">\(p\)</span>-values <em>should</em> have been. You can’t compute a <span class="math inline">\(p\)</span>-value when you don’t know the decision making procedure that the researcher used. And so the reported <span class="math inline">\(p\)</span>-value remains a lie.</p>
<p>Given all of the above, what is the take home message? It’s not that Bayesian methods are foolproof. If a researcher is determined to cheat, they can always do so. Bayes’ rule cannot stop people from lying, nor can it stop them from rigging an experiment. That’s not my point here. My point is the same one I made at the very beginning of the book in <a href="./01-whystats.html#sec-whywhywhy">On the psychology of statistics</a>: the reason why we run statistical tests is to protect us from ourselves. And the reason why “data peeking” is such a concern is that it’s so tempting, <em>even for honest researchers</em>. A theory for statistical inference has to acknowledge this. Yes, you might try to defend <span class="math inline">\(p\)</span>-values by saying that it’s the fault of the researcher for not using them properly. But to my mind that misses the point. A theory of statistical inference that is so completely naive about humans that it doesn’t even consider the possibility that the researcher might <em>look at their own data</em> isn’t a theory worth having. In essence, my point is this:</p>
<div class="pullquote">
<p><em>Good laws have their origins in bad morals.</em></p>
<p>— Ambrosius Macrobius</p>
<p><a href="http://www.quotationspage.com/quotes/Ambrosius_Macrobius/" class="uri">http://www.quotationspage.com/quotes/Ambrosius_Macrobius/</a>.</p>
</div>
<p>Good rules for statistical testing have to acknowledge human frailty. None of us are without sin. None of us are beyond temptation. A good system for statistical inference should still work even when it is used by actual humans. Orthodox null hypothesis testing does not.<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn10"><p><sup>10</sup>&nbsp;Okay, I just <em>know</em> that some knowledgeable frequentists will read this and start complaining about this section. Look, I’m not dumb. I absolutely know that if you adopt a sequential analysis perspective you can avoid these errors within the orthodox framework. I also know that you can explicitly design studies with interim analyses in mind. So yes, in one sense I’m attacking a “straw man” version of orthodox methods. However, the straw man that I’m attacking is the one that <em>is used by almost every single practitioner</em>. If it ever reaches the point where sequential methods become the norm among experimental psychologists and I’m no longer forced to read 20 extremely dubious ANOVAs a day, I promise I’ll rewrite this section and dial down the vitriol. But until that day arrives, I stand by my claim that <em>default</em> Bayes factor methods are much more robust in the face of data analysis practices as they exist in the real world. <em>Default</em> orthodox methods suck, and we all know it.</p></div></div></section>
</section>
<section id="sec-bayescontingency" class="level2 page-columns page-full" data-number="17.4">
<h2 data-number="17.4" class="anchored" data-anchor-id="sec-bayescontingency"><span class="header-section-number">17.4</span> Bayesian analysis of contingency tables</h2>
<p>Time to change gears. Up to this point I’ve been talking about what Bayesian inference is and why you might consider using it. I now want to briefly describe how to do Bayesian versions of various statistical tests. The discussions in the next few sections are not as detailed as I’d like, but I hope they’re enough to help you get started. So let’s begin.</p>
<p>The first kind of statistical inference problem I discussed in this book appeared in <a href="./12-chisquare.html">Categorical data analysis</a>, in which we discussed categorical data analysis problems. In that chapter I talked about several different statistical problems that you might be interested in, but the one that appears most often in real life is the analysis of <em>contingency tables</em>. In this kind of data analysis situation, we have a cross-tabulation of one variable against another one, and the goal is to find out if there is some <em>association</em> between these variables. The data set I used to illustrate this problem is found in the <code>chapek9.Rdata</code> file, and it contains a single data frame <code>chapek9</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/chapek9.Rdata"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(chapek9)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  species choice
1   robot flower
2   human   data
3   human   data
4   human   data
5   robot   data
6   human flower</code></pre>
</div>
</div>
<p>In this data set, we supposedly sampled 180 beings and measured two things. First, we checked whether they were humans or robots, as captured by the <code>species</code> variable. Second, we asked them to nominate whether they most preferred flowers, puppies, or data. When we produce the cross-tabulation, we get this as the results:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>crosstab <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(<span class="sc">~</span> species <span class="sc">+</span> choice, chapek9)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>crosstab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       choice
species puppy flower data
  robot    13     30   44
  human    15     13   65</code></pre>
</div>
</div>
<p>Surprisingly, the humans seemed to show a much stronger preference for data than the robots did. At the time we speculated that this might have been because the questioner was a large robot carrying a gun, and the humans might have been scared.</p>
<section id="the-orthodox-test" class="level3" data-number="17.4.1">
<h3 data-number="17.4.1" class="anchored" data-anchor-id="the-orthodox-test"><span class="header-section-number">17.4.1</span> The orthodox test</h3>
<p>Just to refresh your memory, here’s how we analysed these data back in <a href="./12-chisquare.html">Categorical data analysis</a>. Because we want to determine if there is some <em>association</em> between <code>species</code> and <code>choice</code>, we used the <code>associationTest()</code> function in the <code>lsr</code> package to run a chi-square test of association. The results looked like this:</p>
<div class="cell" data-trunc-head="3" data-trunc-tail="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">associationTest</span>(<span class="sc">~</span> species <span class="sc">+</span> choice, chapek9)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Chi-square test of categorical association


BLAH BLAH BLAH

   p-value:  0.005 

Other information: 
   estimated effect size (Cramer's v):  0.244 </code></pre>
</div>
</div>
<p>Because we found a small <span class="math inline">\(p\)</span> value (in this case <span class="math inline">\(p&lt;.01\)</span>), we concluded that the data are inconsistent with the null hypothesis of no association, and we rejected it.</p>
</section>
<section id="the-bayesian-test" class="level3 page-columns page-full" data-number="17.4.2">
<h3 data-number="17.4.2" class="anchored" data-anchor-id="the-bayesian-test"><span class="header-section-number">17.4.2</span> The Bayesian test</h3>
<p>How do we run an equivalent test as a Bayesian? Well, like every other bloody thing in statistics, there’s a lot of different ways you <em>could</em> do it. However, for the sake of everyone’s sanity, throughout this chapter I’ve decided to rely on one R package to do the work. Specifically, I’m going to use the <code>BayesFactor</code> package written by Jeff Rouder and Rich Morey.</p>
<p>For the analysis of contingency tables, the <code>BayesFactor</code> package contains a function called <code>contingencyTableBF()</code>. The data that you need to give to this function is the contingency table itself (i.e., the <code>crosstab</code> variable above), so you might be expecting to use a command like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contingencyTableBF</span>(crosstab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in `contingencyTableBF()`:
! argument "sampleType" is missing, with no default</code></pre>
</div>
</div>
<p>However, if you try this you’ll get an error message. This is because the <code>contingencyTableBF()</code> function needs one other piece of information from you: it needs to know what <em>sampling plan</em> you used to run your experiment. You can specify the sampling plan using the <code>sampleType</code> argument. So I should probably tell you what your options are! The <code>contingencyTableBF()</code> function distinguishes between four different types of experiment:</p>
<ul>
<li><strong>Fixed sample size</strong>. Suppose that in our <code>chapek9</code> example, our experiment was designed like this: we deliberately set out to test 180 people, but we didn’t try to control the number of humans or robots, nor did we try to control the choices they made. In this design, the total number of observations <span class="math inline">\(N\)</span> is fixed, but everything else is random. This is referred to as “joint multinomial” sampling, and if that’s what you did you should specify <code>sampleType = "jointMulti"</code>. In the case of the <code>chapek9</code> data, that’s actually what I had in mind when I invented the data set.</li>
<li><strong>Fixed row (or column) totals</strong>. A different kind of design might work like this. We decide ahead of time that we want 180 people, but we try to be a little more systematic about it. Specifically, the <em>experimenter</em> constrains it so that we get a predetermined number of humans and robots (e.g., 90 of each). In this design, <em>either</em> the row totals or the column totals are fixed, but not both. This is referred to as “independent multinomial” sampling, and if that’s what you did you should specify <code>sampleType = "indepMulti"</code>.</li>
<li><strong>Both row and column totals fixed</strong>. Another logical possibility is that you designed the experiment so that <em>both</em> the row totals and the column totals are fixed. This doesn’t make any sense at all in the <code>chapek9</code> example, but there are other designs that can work this way. Suppose that I show you a collection of 20 toys, and then give them 10 stickers that say <code>boy</code> and another 10 that say <code>girl</code>. I then give them 10 <code>blue</code> stickers and 10 <code>pink</code> stickers. I then ask you to put the stickers on the 20 toys such that every toy has a colour and every toy has a gender. No matter how you assign the stickers, the total number of pink and blue toys will be 10, as will the number of boys and girls. In this design <em>both</em> the rows and columns of the contingency table are fixed. This is referred to as “hypergeometric” sampling, and if that’s what you’ve done you should specify <code>sampleType = "hypergeom"</code>.</li>
<li><strong>Nothing is fixed</strong>. Finally, it might be the case that <em>nothing</em> is fixed. Not the row totals, not the column totals, and not the total sample size either. For instance, in the <code>chapek9</code> scenario, suppose what I’d done is run the study for a fixed length of <em>time</em>. By chance, it turned out that I got 180 people to turn up to the study, but it could easily have been something else. This is referred to as “Poisson” sampling, and if that’s what you’ve done you should specify <code>sampleType = "poisson"</code>.</li>
</ul>
<p>Okay, so now we have enough knowledge to actually run a test. For the <code>chapek9</code> data, I implied that we designed the study such that the total sample size <span class="math inline">\(N\)</span> was fixed, so we should set <code>sampleType = "jointMulti"</code>. The command that we need is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contingencyTableBF</span>(crosstab, <span class="at">sampleType =</span> <span class="st">"jointMulti"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bayes factor analysis
--------------
[1] Non-indep. (a=1) : 15.92684 ±0%

Against denominator:
  Null, independence, a = 1 
---
Bayes factor type: BFcontingencyTable, joint multinomial</code></pre>
</div>
</div>
<p>As with most R commands, the output initially looks suspiciously similar to utter gibberish. Fortunately, it’s actually pretty simple once you get past the initial impression. Firstly, note that the stuff at the top and bottom are irrelevant fluff. You already know that you’re doing a Bayes factor analysis. You already know that you’re analysing a contingency table, and you already know that you specified a joint multinomial sampling plan. Let’s also ignore the <code>a=1</code> bit, since it’s a technical detail that you don’t need to know about at this stage.<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a> The rest of the output is actually pretty straightforward. At the bottom, the output defines the null hypothesis for you: in this case, the null hypothesis is that there is no relationship between <code>species</code> and <code>choice</code>. Or, to put it another way, the null hypothesis is that these two variables are <em>independent</em>. Now if you look at the line above it, you might (correctly) guess that the <code>Non-indep.</code> part refers to the <em>alternative</em> hypothesis. In this case, the alternative is that there <em>is</em> a relationship between <code>species</code> and <code>choice</code>: that is, they are not independent. So the only thing left in the output is the number reporting the Bayes factor, which tells you that the odds for the alternative hypothesis against the null are about 16:1. The <span class="math inline">\(\pm0\%\)</span> part is not very interesting: essentially, all it’s telling you is that R has calculated an exact Bayes factor, so the uncertainty about the Bayes factor is 0%.<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a> In any case, the data are telling us that we have moderate evidence for the alternative hypothesis.</p>
<div class="no-row-height column-margin column-container"><div id="fn11"><p><sup>11</sup>&nbsp;If you’re desperate to know, you can find all the gory details in <span class="citation" data-cites="Gunel1974">Gunel &amp; Dickey (<a href="references.html#ref-Gunel1974" role="doc-biblioref">1974</a>)</span>. However, that’s a pretty technical paper. The help documentation to <code>contingencyTableBF()</code> gives this explanation: “the argument <code>priorConcentration</code> indexes the expected deviation from the null hypothesis under the alternative, and corresponds to Gunel and Dickey’s (1974) <span class="math inline">\(a\)</span> parameter.” Setting <span class="math inline">\(a=1\)</span> is a pretty sensible default choice, since it corresponds to an assumption that you have very little <em>a priori</em> knowledge about the contingency table.</p></div><div id="fn12"><p><sup>12</sup>&nbsp;In some of the later examples, you’ll see that this number is not always 0%. This is because the <code>BayesFactor</code> package often has to run some simulations to compute approximate Bayes factors. So the answers you get won’t always be identical when you run the command a second time. That’s why the output of these functions tells you what the margin for error is.</p></div></div></section>
<section id="writing-up-the-results" class="level3" data-number="17.4.3">
<h3 data-number="17.4.3" class="anchored" data-anchor-id="writing-up-the-results"><span class="header-section-number">17.4.3</span> Writing up the results</h3>
<p>When writing up the results, my experience has been that there aren’t quite so many “rules” for how you “should” report Bayesian hypothesis tests. That might change in the future if Bayesian methods become standard and some task force starts writing up style guides, but in the meantime I would suggest using some common sense. For example, I would avoid writing this:</p>
<blockquote class="blockquote">
<p>A Bayesian test of association found a significant result (BF=15.92)</p>
</blockquote>
<p>To my mind, this write up is unclear. Even assuming that you’ve already reported the relevant descriptive statistics, there are a number of things I am unhappy with. First, the concept of “statistical significance” is pretty closely tied with <span class="math inline">\(p\)</span>-values, so it reads slightly strangely. Second, the “BF=15.92” part will only make sense to people who already understand Bayesian methods, and not everyone does. Third, it is somewhat unclear exactly which test was run and what software was used to do so.</p>
<p>On the other hand, unless precision is <em>extremely</em> important, I think that this is taking things a step too far:</p>
<blockquote class="blockquote">
<p>We ran a Bayesian test of association <span class="citation" data-cites="Gunel1974">(see <a href="references.html#ref-Gunel1974" role="doc-biblioref">Gunel &amp; Dickey, 1974</a>)</span> using the BayesFactor package <span class="citation" data-cites="Morey2015">(<a href="references.html#ref-Morey2015" role="doc-biblioref">Morey &amp; Rouder, 2015</a>)</span> using default priors and a joint multinomial sampling plan. The resulting Bayes factor of 15.92 to 1 in favour of the alternative hypothesis indicates that there is moderately strong evidence for the non-independence of species and choice.</p>
</blockquote>
<p>Everything about that passage is correct, of course. <span class="citation" data-cites="Morey2015">Morey &amp; Rouder (<a href="references.html#ref-Morey2015" role="doc-biblioref">2015</a>)</span> built their Bayesian tests of association using the paper by <span class="citation" data-cites="Gunel1974">Gunel &amp; Dickey (<a href="references.html#ref-Gunel1974" role="doc-biblioref">1974</a>)</span>, the specific test we used assumes that the experiment relied on a joint multinomial sampling plan, and indeed the Bayes factor of 15.92 is moderately strong evidence. It’s just far too wordy.</p>
<p>In most situations you just don’t need that much information. My preference is usually to go for something a little briefer. First, if you’re reporting multiple Bayes factor analyses in your write up, then somewhere you only need to cite the software once, at the beginning of the results section. So you might have one sentence like this:</p>
<blockquote class="blockquote">
<p>All analyses were conducted using the BayesFactor package in R <span class="citation" data-cites="Morey2015">(<a href="references.html#ref-Morey2015" role="doc-biblioref">Morey &amp; Rouder, 2015</a>)</span>, and unless otherwise stated default parameter values were used.</p>
</blockquote>
<p>Notice that I don’t bother including the version number? That’s because the citation itself includes that information (go check my reference list if you don’t believe me). There’s no need to clutter up your results with redundant information that almost no-one will actually need. When you get to the actual test you can get away with this:</p>
<blockquote class="blockquote">
<p>A test of association produced a Bayes factor of 16:1 in favour of a relationship between species and choice.</p>
</blockquote>
<p>Short and sweet. I’ve rounded 15.92 to 16, because there’s not really any important difference between 15.92:1 and 16:1. I spelled out “Bayes factor” rather than truncating it to “BF” because not everyone knows the abbreviation. I indicated exactly what the effect is (i.e., “a relationship between species and choice”) and how strong the evidence was. I <em>didn’t</em> bother indicating whether this was “moderate” evidence or “strong” evidence, because the odds themselves tell you! There’s nothing stopping you from including that information, and I’ve done so myself on occasions, but you don’t strictly need it. Similarly, I didn’t bother to indicate that I ran the “joint multinomial” sampling plan, because I’m assuming that the method section of my write up would make clear how the experiment was designed. (I might change my mind about that if the method section was ambiguous.) Neither did I bother indicating that this was a <em>Bayesian</em> test of association: if your reader can’t work that out from the fact that you’re reporting a Bayes factor and the fact that you’re citing the <code>BayesFactor</code> package for all your analyses, then there’s no chance they’ll understand anything you’ve written. Besides, if you keep writing the word “Bayes” over and over again it starts to look stupid. Bayes Bayes Bayes Bayes Bayes. See?</p>
</section>
<section id="other-sampling-plans" class="level3" data-number="17.4.4">
<h3 data-number="17.4.4" class="anchored" data-anchor-id="other-sampling-plans"><span class="header-section-number">17.4.4</span> Other sampling plans</h3>
<p>Up to this point all I’ve shown you is how to use the <code>contingencyTableBF()</code> function for the joint multinomial sampling plan (i.e., when the total sample size <span class="math inline">\(N\)</span> is fixed, but nothing else is). For the Poisson sampling plan (i.e., nothing fixed), the command you need is identical except for the <code>sampleType</code> argument:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contingencyTableBF</span>(crosstab, <span class="at">sampleType =</span> <span class="st">"poisson"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bayes factor analysis
--------------
[1] Non-indep. (a=1) : 28.20757 ±0%

Against denominator:
  Null, independence, a = 1 
---
Bayes factor type: BFcontingencyTable, poisson</code></pre>
</div>
</div>
<p>Notice that the Bayes factor here is <em>not</em> identical to the one we obtained from the last test. The sampling plan actually does matter.</p>
<p>What about the design in which the row totals (or column totals) are fixed? As I mentioned earlier, this corresponds to the “independent multinomial” sampling plan. Again, you need to specify the <code>sampleType</code> argument, but this time you need to specify whether you fixed the rows or the columns. For example, suppose I deliberately sampled 87 humans and 93 robots, then I would need to indicate that the <code>fixedMargin</code> of the contingency table is the <code>"rows"</code>. So the command I would use is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contingencyTableBF</span>(crosstab, <span class="at">sampleType =</span> <span class="st">"indepMulti"</span>, <span class="at">fixedMargin =</span> <span class="st">"rows"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bayes factor analysis
--------------
[1] Non-indep. (a=1) : 8.605897 ±0%

Against denominator:
  Null, independence, a = 1 
---
Bayes factor type: BFcontingencyTable, independent multinomial</code></pre>
</div>
</div>
<p>Again, the Bayes factor is different, with the evidence for the alternative dropping to about 9:1. As you might expect, the answers would be different again if it were the columns of the contingency table that the experimental design fixed.</p>
<p>Finally, if we turn to hypergeometric sampling in which everything is fixed, we get…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contingencyTableBF</span>(crosstab, <span class="at">sampleType =</span> <span class="st">"hypergeom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in `contingencyHypergeometric()`:
! hypergeometric contingency tables restricted to 2 x 2 tables; see help for contingencyTableBF()</code></pre>
</div>
</div>
<p>… an error message. This is because hypergeometric sampling is restricted to <span class="math inline">\(2 \times 2\)</span> contingency tables. In the meantime, let’s imagine we have data from the “toy labelling” experiment I described earlier in this section. Specifically, let’s say our data look like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>toys <span class="ot">&lt;-</span> <span class="fu">matrix</span>(</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">8</span>),</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">"girl"</span>, <span class="st">"boy"</span>), <span class="fu">c</span>(<span class="st">"pink"</span>, <span class="st">"blue"</span>))</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>toys</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     pink blue
girl    8    2
boy     2    8</code></pre>
</div>
</div>
<p>The Bayesian test with hypergeometric sampling gives us this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contingencyTableBF</span>(toys, <span class="at">sampleType =</span> <span class="st">"hypergeom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bayes factor analysis
--------------
[1] Non-indep. (a=1) : 8.294321 ±0%

Against denominator:
  Null, independence, a = 1 
---
Bayes factor type: BFcontingencyTable, hypergeometric</code></pre>
</div>
</div>
<p>The Bayes factor of about 8:1 provides modest evidence that the labels were being assigned in a way that correlates gender with colour, but it’s not conclusive.</p>
</section>
</section>
<section id="sec-ttestbf" class="level2 page-columns page-full" data-number="17.5">
<h2 data-number="17.5" class="anchored" data-anchor-id="sec-ttestbf"><span class="header-section-number">17.5</span> Bayesian <span class="math inline">\(t\)</span>-tests</h2>
<p>The second type of statistical inference problem discussed in this book is the comparison between two means, discussed in some detail in the chapter on <span class="math inline">\(t\)</span>-tests (<a href="./13-ttest.html">The <span class="math inline">\(t\)</span>-test</a>). If you can remember back that far, you’ll recall that there are several versions of the <span class="math inline">\(t\)</span>-test. The <code>BayesFactor</code> package contains a function called <code>ttestBF()</code> that is flexible enough to run several different versions of the <span class="math inline">\(t\)</span>-test. I’ll talk a little about Bayesian versions of the independent samples <span class="math inline">\(t\)</span>-test and the paired samples <span class="math inline">\(t\)</span>-test in this section.</p>
<section id="independent-samples-t-test" class="level3 page-columns page-full" data-number="17.5.1">
<h3 data-number="17.5.1" class="anchored" data-anchor-id="independent-samples-t-test"><span class="header-section-number">17.5.1</span> Independent samples <span class="math inline">\(t\)</span>-test</h3>
<p>The most common type of <span class="math inline">\(t\)</span>-test is the independent samples <span class="math inline">\(t\)</span>-test, and it arises when you have data that look something like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/harpo.Rdata"</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(harpo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  grade      tutor
1    65  Anastasia
2    72 Bernadette
3    66 Bernadette
4    74  Anastasia
5    73  Anastasia
6    71 Bernadette</code></pre>
</div>
</div>
<p>In this data set, we have two groups of students, those who received lessons from Anastasia and those who took their classes with Bernadette. The question we want to answer is whether there’s any difference in the grades received by these two groups of students. Back in <a href="./13-ttest.html">The <span class="math inline">\(t\)</span>-test</a> I suggested you could analyse this kind of data using the <code>independentSamplesTTest()</code> function in the <code>lsr</code> package. For example, if you want to run a Student’s <span class="math inline">\(t\)</span>-test, you’d use a command like this:</p>
<div class="cell" data-trunc-head="8" data-trunc-tail="5">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">independentSamplesTTest</span>(</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> grade <span class="sc">~</span> tutor,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> harpo,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">var.equal =</span> <span class="cn">TRUE</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   Student's independent samples t-test 

Outcome variable:   grade 
Grouping variable:  tutor 

Descriptive statistics: 
            Anastasia Bernadette

BLAH BLAH BLAH

   p-value:  0.043 

Other information: 
   two-sided 95% confidence interval:  [0.197, 10.759] 
   estimated effect size (Cohen's d):  0.74 </code></pre>
</div>
</div>
<p>Like most of the functions that I wrote for this book, <code>independentSamplesTTest()</code> is very wordy. It prints out a bunch of descriptive statistics and a reminder of what the null and alternative hypotheses are, before finally getting to the test results. I wrote it that way deliberately, in order to help make things a little clearer for people who are new to statistics. Focusing just on the test results: we obtain a <span class="math inline">\(p\)</span>-value less than 0.05, so we reject the null hypothesis.</p>
<p>What does the Bayesian version of the <span class="math inline">\(t\)</span>-test look like? Using the <code>ttestBF()</code> function, we can obtain a Bayesian analog of Student’s independent samples <span class="math inline">\(t\)</span>-test using the following command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ttestBF</span>(<span class="at">formula =</span> grade <span class="sc">~</span> tutor, <span class="at">data =</span> harpo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bayes factor analysis
--------------
[1] Alt., r=0.707 : 1.754927 ±0.01%

Against denominator:
  Null, mu1-mu2 = 0 
---
Bayes factor type: BFindepSample, JZS</code></pre>
</div>
</div>
<p>Notice the format of this command is pretty standard. As usual we have a <code>formula</code> argument in which we specify the outcome variable on the left hand side and the grouping variable on the right. The <code>data</code> argument is used to specify the data frame containing the variables. However, notice that there’s no analog of the <code>var.equal</code> argument. This is because the <code>BayesFactor</code> package does not include an analog of the Welch test, only the Student test.<a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn13"><p><sup>13</sup>&nbsp;Apparently this omission is deliberate. I have this vague recollection that I spoke to Jeff Rouder about this once, and his opinion was that when homogeneity of variance is violated the results of a <span class="math inline">\(t\)</span>-test are uninterpretable. I can see the argument for this, but I’ve never really held a strong opinion myself. (Jeff, if you never said that, I’m sorry.)</p></div><div id="fn14"><p><sup>14</sup>&nbsp;Just in case you’re interested: the “JZS” part of the output relates to how the Bayesian test expresses the prior uncertainty about the variance <span class="math inline">\(\sigma^2\)</span>, and it’s short for the names of three people: “Jeffreys Zellner Siow”. See <span class="citation" data-cites="Rouder2009">Rouder et al. (<a href="references.html#ref-Rouder2009" role="doc-biblioref">2009</a>)</span> for details.</p></div><div id="fn15"><p><sup>15</sup>&nbsp;Again, in case you care … the null hypothesis here specifies an effect size of 0, since the two means are identical. The alternative hypothesis states that there <em>is</em> an effect, but it doesn’t specify exactly how big the effect will be. The <span class="math inline">\(r\)</span> value here relates to how big the effect is expected to be according to the alternative. You can type <code>?ttestBF</code> to get more details.</p></div></div><p>So what does all this mean? Just as we saw with the <code>contingencyTableBF()</code> function, the output is pretty dense. But, just like last time, there’s not a lot of information here that you actually need to process. Firstly, let’s examine the bottom line. The <code>BFindepSample</code> part just tells you that you ran an independent samples <span class="math inline">\(t\)</span>-test, and the <code>JZS</code> part is technical information that is a little beyond the scope of this book.<a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a> In the line above, the text <code>Null, mu1-mu2 = 0</code> is just telling you that the null hypothesis is that there are no differences between means. But you already knew that. Ignore the <code>r=0.707</code> part: it refers to a technical detail that we won’t worry about in this chapter.<a href="#fn15" class="footnote-ref" id="fnref15" role="doc-noteref"><sup>15</sup></a> Instead, you should focus on the Bayes factor itself: the evidence provided by these data are only about 2:1 in favour of the alternative.</p>
<p>Before moving on, it’s worth highlighting the difference between the orthodox test results and the Bayesian one. According to the orthodox test, we obtained a significant result, though only barely. Nevertheless, many people would happily accept <span class="math inline">\(p=.043\)</span> as reasonably strong evidence for an effect. In contrast, notice that the Bayesian test doesn’t even reach 2:1 odds in favour of an effect, and would be considered very weak evidence at best. In my experience that’s a pretty typical outcome. Bayesian methods usually require more evidence before rejecting the null.</p>
</section>
<section id="paired-samples-t-test" class="level3" data-number="17.5.2">
<h3 data-number="17.5.2" class="anchored" data-anchor-id="paired-samples-t-test"><span class="header-section-number">17.5.2</span> Paired samples <span class="math inline">\(t\)</span>-test</h3>
<p>Back in <a href="./13-ttest.html#sec-pairedsamplesttest">The paired-samples <span class="math inline">\(t\)</span>-test</a> I discussed the <code>chico</code> data frame in which students’ grades were measured on two tests, and we were interested in finding out whether grades went up from test 1 to test 2. Because every student did both tests, the tool we used to analyse the data was a paired samples <span class="math inline">\(t\)</span>-test. To remind you of what the data look like, here’s the first few cases:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/chico.Rdata"</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(chico)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        id grade_test1 grade_test2
1 student1        42.9        44.6
2 student2        51.8        54.0
3 student3        71.7        72.3
4 student4        51.6        53.4
5 student5        63.5        63.8
6 student6        58.0        59.3</code></pre>
</div>
</div>
<p>We originally analysed the data using the <code>pairedSamplesTTest()</code> function in the <code>lsr</code> package, but this time we’ll use the <code>ttestBF()</code> function from the <code>BayesFactor</code> package to do the same thing. The easiest way to do it with this data set is to use the <code>x</code> argument to specify one variable and the <code>y</code> argument to specify the other. All we need to do then is specify <code>paired = TRUE</code> to tell R that this is a paired samples test. So here’s our command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ttestBF</span>(</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> chico<span class="sc">$</span>grade_test1,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> chico<span class="sc">$</span>grade_test2,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">paired =</span> <span class="cn">TRUE</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bayes factor analysis
--------------
[1] Alt., r=0.707 : 5992.05 ±0%

Against denominator:
  Null, mu = 0 
---
Bayes factor type: BFoneSample, JZS</code></pre>
</div>
</div>
<p>At this point, I hope you can read this output without any difficulty. The data provide evidence of about 6000:1 in favour of the alternative. We could probably reject the null with some confidence!</p>
</section>
</section>
<section id="sec-bayesregression" class="level2" data-number="17.6">
<h2 data-number="17.6" class="anchored" data-anchor-id="sec-bayesregression"><span class="header-section-number">17.6</span> Bayesian regression</h2>
<p>Okay, so now we’ve seen Bayesian equivalents to orthodox chi-square tests and <span class="math inline">\(t\)</span>-tests. What’s next? If I were to follow the same progression that I used when developing the orthodox tests you’d expect to see ANOVA next, but I think it’s a little clearer if we start with regression.</p>
<section id="a-quick-refresher" class="level3" data-number="17.6.1">
<h3 data-number="17.6.1" class="anchored" data-anchor-id="a-quick-refresher"><span class="header-section-number">17.6.1</span> A quick refresher</h3>
<p>In <a href="./15-regression.html">Linear regression</a> I used the <code>parenthood</code> data to illustrate the basic ideas behind regression. To remind you of what that data set looks like, here’s the first six observations:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/parenthood.Rdata"</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(parenthood)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  danielle_sleep baby_sleep danielle_grump day
1           7.59      10.18             56   1
2           7.91      11.66             60   2
3           5.14       7.92             82   3
4           7.71       9.61             55   4
5           6.68       9.75             67   5
6           5.99       5.04             72   6</code></pre>
</div>
</div>
<p>Back in <a href="./15-regression.html">Linear regression</a> I proposed a theory in which my grumpiness (<code>danielle_grump</code>) on any given day is related to the amount of sleep I got the night before (<code>danielle_sleep</code>), and possibly to the amount of sleep our baby got (<code>baby_sleep</code>), though probably not to the <code>day</code> on which we took the measurement. We tested this using a regression model. In order to estimate the regression model we used the <code>lm()</code> function, like so:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> danielle_grump <span class="sc">~</span> danielle_sleep <span class="sc">+</span> day <span class="sc">+</span> baby_sleep,</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> parenthood</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The hypothesis tests for each of the terms in the regression model were extracted using the <code>summary()</code> function:</p>
<div class="cell" data-trunc-head="5" data-trunc-tail="3">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = danielle_grump ~ danielle_sleep + day + baby_sleep, 
    data = parenthood)


BLAH BLAH BLAH

Residual standard error: 4.375 on 96 degrees of freedom
Multiple R-squared:  0.8163,    Adjusted R-squared:  0.8105 
F-statistic: 142.2 on 3 and 96 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>When interpreting the results, each row in this table corresponds to one of the possible predictors. The <code>(Intercept)</code> term isn’t usually interesting, though it is highly significant. The important thing for our purposes is the fact that <code>danielle_sleep</code> is significant at <span class="math inline">\(p&lt;.001\)</span> and neither of the other variables are.</p>
</section>
<section id="the-bayesian-version" class="level3" data-number="17.6.2">
<h3 data-number="17.6.2" class="anchored" data-anchor-id="the-bayesian-version"><span class="header-section-number">17.6.2</span> The Bayesian version</h3>
<p>Okay, so how do we do the same thing using the <code>BayesFactor</code> package? The easiest way is to use the <code>regressionBF()</code> function instead of <code>lm()</code>. As before, we use <code>formula</code> to indicate what the full regression model looks like, and the <code>data</code> argument to specify the data frame. So the command is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">regressionBF</span>(</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> danielle_grump <span class="sc">~</span> danielle_sleep <span class="sc">+</span> day <span class="sc">+</span> baby_sleep,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> parenthood</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bayes factor analysis
--------------
[1] danielle_sleep                    : 1.622545e+34 ±0.01%
[2] day                               : 0.2724027    ±0%
[3] baby_sleep                        : 10018411     ±0%
[4] danielle_sleep + day              : 1.016576e+33 ±0%
[5] danielle_sleep + baby_sleep       : 9.77022e+32  ±0%
[6] day + baby_sleep                  : 2340755      ±0%
[7] danielle_sleep + day + baby_sleep : 7.835625e+31 ±0%

Against denominator:
  Intercept only 
---
Bayes factor type: BFlinearModel, JZS</code></pre>
</div>
</div>
<p>So that’s pretty straightforward: it’s exactly what we’ve been doing throughout the book. The output, however, is a little different from what you get from <code>lm()</code>. At the bottom we have some technical rubbish, and at the top we have some information about the Bayes factors. What’s new is the fact that we seem to have <em>lots</em> of Bayes factors here. What’s all this about?</p>
<p>The trick to understanding this output is to recognise that if we’re interested in working out which of the 3 predictor variables are related to <code>danielle_grump</code>, there are actually 8 possible regression models that could be considered. One possibility is the <em>intercept only model</em>, in which none of the three variables have an effect. At the other end of the spectrum is the <em>full model</em> in which all three variables matter. So what <code>regressionBF()</code> does is treat the <em>intercept only</em> model as the null hypothesis, and print out the Bayes factors for all other models when compared against that null. For example, if we look at the line for <code>danielle_sleep + day</code> in the table, we see that the evidence is about <span class="math inline">\(10^{33}\)</span> to 1 in favour of the claim that a model that includes both <code>danielle_sleep</code> and <code>day</code> is better than the intercept only model. Or if we look at the line for <code>danielle_sleep</code> alone, we can see that the odds are about <span class="math inline">\(1.6 \times 10^{34}\)</span> that a model containing the <code>danielle_sleep</code> variable (but no others) is better than the intercept only model.</p>
</section>
<section id="finding-the-best-model" class="level3" data-number="17.6.3">
<h3 data-number="17.6.3" class="anchored" data-anchor-id="finding-the-best-model"><span class="header-section-number">17.6.3</span> Finding the best model</h3>
<p>In practice, this isn’t super helpful. In most situations the intercept only model is one that you don’t really care about at all. What I find helpful is to start out by working out which model is the <em>best</em> one, and then seeing how well all the alternatives compare to it. Here’s how you do that. In this case, it’s easy enough to see that the best model is actually the one that contains <code>danielle_sleep</code> only, because it has the largest Bayes factor. However, if you’ve got a lot of possible models in the output, it’s handy to know that you can use the <code>head()</code> function to pick out the best few models. First, we have to go back and save the Bayes factor information to a variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>models <span class="ot">&lt;-</span> <span class="fu">regressionBF</span>(</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> danielle_grump <span class="sc">~</span> danielle_sleep <span class="sc">+</span> day <span class="sc">+</span> baby_sleep,</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> parenthood</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s say I want to see the best three models. To do this, I use the <code>head()</code> function specifying <code>n=3</code>, and here’s what I get as the result:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(models, <span class="at">n =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bayes factor analysis
--------------
[1] danielle_sleep              : 1.622545e+34 ±0.01%
[2] danielle_sleep + day        : 1.016576e+33 ±0%
[3] danielle_sleep + baby_sleep : 9.77022e+32  ±0%

Against denominator:
  Intercept only 
---
Bayes factor type: BFlinearModel, JZS</code></pre>
</div>
</div>
<p>This is telling us that the model <code>danielle_grump ~ danielle_sleep</code> is the best one. That’s <em>almost</em> what I’m looking for, but it’s still comparing all the models against the intercept only model. That seems silly. What I’d like to know is how big the difference is between the best model and the other good models. For that, there’s this trick:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(models <span class="sc">/</span> <span class="fu">max</span>(models), <span class="at">n =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bayes factor analysis
--------------
[1] danielle_sleep              : 1         ±0%
[2] danielle_sleep + day        : 0.0626532 ±0.01%
[3] danielle_sleep + baby_sleep : 0.0602154 ±0.01%

Against denominator:
  danielle_grump ~ danielle_sleep 
---
Bayes factor type: BFlinearModel, JZS</code></pre>
</div>
</div>
<p>Notice the bit at the bottom showing that the “denominator” has changed. What that means is that the Bayes factors are now comparing each of those 3 models listed against the <code>danielle_grump ~ danielle_sleep</code> model. Obviously, the Bayes factor for that model is exactly 1, since that’s just comparing the best model to itself. More to the point, the other two Bayes factors are both less than 1, indicating that they’re all worse than that model. You can also directly compare the best model to the second-best model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>models[<span class="dv">1</span>] <span class="sc">/</span> models[<span class="dv">4</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bayes factor analysis
--------------
[1] danielle_sleep : 15.96088 ±0.01%

Against denominator:
  danielle_grump ~ danielle_sleep + day 
---
Bayes factor type: BFlinearModel, JZS</code></pre>
</div>
</div>
<p>And there you have it. You’ve found the regression model with the highest Bayes factor (i.e., <code>danielle_grump ~ danielle_sleep</code>), and you know that the evidence for that model over the next best alternative (i.e., <code>danielle_grump ~ danielle_sleep + day</code>) is about 16:1.</p>
</section>
<section id="extracting-bayes-factors-for-all-included-terms" class="level3" data-number="17.6.4">
<h3 data-number="17.6.4" class="anchored" data-anchor-id="extracting-bayes-factors-for-all-included-terms"><span class="header-section-number">17.6.4</span> Extracting Bayes factors for all included terms</h3>
<p>Okay, let’s say you’ve settled on a specific regression model. What Bayes factors should you report? In this example, I’m going to pretend that you decided that <code>danielle_grump ~ danielle_sleep + baby_sleep</code> is the model you think is best. Sometimes it’s sensible to do this, even when it’s not the one with the highest Bayes factor. Usually this happens because you have a substantive theoretical reason to prefer one model over the other. However, in this case I’m doing it because I want to use a model with more than one predictor as my example!</p>
<p>Having figured out which model you prefer, it can be really useful to call the <code>regressionBF()</code> function and specify <code>whichModels = "top"</code>. You use your “preferred” model as the <code>formula</code> argument, and then the output will show you the Bayes factors that result when you try to drop predictors from this model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">regressionBF</span>(</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> danielle_grump <span class="sc">~</span> danielle_sleep <span class="sc">+</span> baby_sleep,</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> parenthood,</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">whichModels =</span> <span class="st">"top"</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bayes factor top-down analysis
--------------
When effect is omitted from danielle_sleep + baby_sleep , BF is...
[1] Omit baby_sleep     : 16.60705     ±0.01%
[2] Omit danielle_sleep : 1.025403e-26 ±0.01%

Against denominator:
  danielle_grump ~ danielle_sleep + baby_sleep 
---
Bayes factor type: BFlinearModel, JZS</code></pre>
</div>
</div>
<p>Okay, so now you can see the results a bit more clearly. The Bayes factor when you try to drop the <code>danielle_sleep</code> predictor is extremely small (around <span class="math inline">\(10^{-26}\)</span>), which is very strong evidence that you <em>shouldn’t</em> drop it. On the other hand, the Bayes factor actually goes up to around 17 if you drop <code>baby_sleep</code>, so you’d usually say that’s pretty strong evidence for dropping that one.</p>
</section>
</section>
<section id="sec-bayesanova" class="level2 page-columns page-full" data-number="17.7">
<h2 data-number="17.7" class="anchored" data-anchor-id="sec-bayesanova"><span class="header-section-number">17.7</span> Bayesian ANOVA</h2>
<p>As you can tell, the <code>BayesFactor</code> package is pretty flexible, and it can do Bayesian versions of pretty much everything in this book. In fact, it can do a few other neat things that I haven’t covered in the book at all. However, I have to stop somewhere, and so there’s only one other topic I want to cover: Bayesian ANOVA.</p>
<section id="a-quick-refresher-1" class="level3" data-number="17.7.1">
<h3 data-number="17.7.1" class="anchored" data-anchor-id="a-quick-refresher-1"><span class="header-section-number">17.7.1</span> A quick refresher</h3>
<p>As with the other examples, I think it’s useful to start with a reminder of how I discussed ANOVA earlier in the book. First, let’s remind ourselves of what the data were. The example I used originally is the <code>clin_trial</code> data frame, which looks like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/clinicaltrial.Rdata"</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(clin_trial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      drug    therapy mood_gain
1  placebo no.therapy       0.5
2  placebo no.therapy       0.3
3  placebo no.therapy       0.1
4 anxifree no.therapy       0.6
5 anxifree no.therapy       0.4
6 anxifree no.therapy       0.2</code></pre>
</div>
</div>
<p>To run our orthodox analysis in earlier chapters we used the <code>aov()</code> function to do all the heavy lifting. In <a href="./16-anova2.html">Factorial ANOVA</a> I recommended using the <code>Anova()</code> function from the <code>car</code> package to produce the ANOVA table, because it uses Type II tests by default. If you’ve forgotten what “Type II tests” are, it might be a good idea to re-read <a href="./16-anova2.html#sec-unbalancedanova">Factorial ANOVA 3: unbalanced designs</a>, because it will become relevant again in a moment. In any case, here’s what our analysis looked like:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">aov</span>(mood_gain <span class="sc">~</span> drug <span class="sc">*</span> therapy, <span class="at">data =</span> clin_trial)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type II tests)

Response: mood_gain
             Sum Sq Df F value    Pr(&gt;F)    
drug         3.4533  2 31.7143 1.621e-05 ***
therapy      0.4672  1  8.5816   0.01262 *  
drug:therapy 0.2711  2  2.4898   0.12460    
Residuals    0.6533 12                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>That’s pretty clearly showing us evidence for a main effect of <code>drug</code> at <span class="math inline">\(p&lt;.001\)</span>, an effect of <code>therapy</code> at <span class="math inline">\(p&lt;.05\)</span> and no interaction.</p>
</section>
<section id="the-bayesian-version-1" class="level3 page-columns page-full" data-number="17.7.2">
<h3 data-number="17.7.2" class="anchored" data-anchor-id="the-bayesian-version-1"><span class="header-section-number">17.7.2</span> The Bayesian version</h3>
<p>How do we do the same thing using Bayesian methods? The <code>BayesFactor</code> package contains a function called <code>anovaBF()</code> that does this for you. It uses a pretty standard <code>formula</code> and <code>data</code> structure, so the command should look really familiar. Just like we did with regression, it will be useful to save the output to a variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>models <span class="ot">&lt;-</span> <span class="fu">anovaBF</span>(</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> mood_gain <span class="sc">~</span> drug <span class="sc">*</span> therapy,</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> clin_trial</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The output is quite different to the traditional ANOVA, but it’s not too bad once you understand what you’re looking for. Let’s take a look:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>models</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bayes factor analysis
--------------
[1] drug                          : 245.9026  ±0%
[2] therapy                       : 0.7316007 ±0%
[3] drug + therapy                : 703.9234  ±1.21%
[4] drug + therapy + drug:therapy : 689.5462  ±1.12%

Against denominator:
  Intercept only 
---
Bayes factor type: BFlinearModel, JZS</code></pre>
</div>
</div>
<p>This looks very similar to the output we obtained from the <code>regressionBF()</code> function, and with good reason. Remember what I said back in <a href="./16-anova2.html#sec-anovalm">ANOVA as a linear model</a>: under the hood, ANOVA is no different to regression, and both are just different examples of a linear model. Because of this, <code>anovaBF()</code> reports the output in much the same way. For instance, if we want to identify the best model we could use the same commands that we used in the last section. One variant that I find quite useful is this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>models <span class="sc">/</span> <span class="fu">max</span>(models)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bayes factor analysis
--------------
[1] drug                          : 0.3493315   ±1.21%
[2] therapy                       : 0.001039319 ±1.21%
[3] drug + therapy                : 1           ±0%
[4] drug + therapy + drug:therapy : 0.9795756   ±1.65%

Against denominator:
  mood_gain ~ drug + therapy 
---
Bayes factor type: BFlinearModel, JZS</code></pre>
</div>
</div>
<p>By “dividing” the <code>models</code> output by the best model (i.e., <code>max(models)</code>), what R is doing is using the best model as the denominator, which gives you a pretty good sense of how close the competitors are. As it happens, the model with the interaction term and the model without it are close competitors here – close enough that which one comes out “best” can flip depending on the Monte Carlo run,<a href="#fn16" class="footnote-ref" id="fnref16" role="doc-noteref"><sup>16</sup></a> which is itself a useful thing to know: the data do not clearly indicate whether there is or is not an interaction.</p>
<div class="no-row-height column-margin column-container"><div id="fn16"><p><sup>16</sup>&nbsp;Unlike the exact Bayes factors for the contingency-table tests earlier in the chapter, <code>anovaBF()</code>’s Bayes factors for models with more than one term are estimated by Monte Carlo integration, and the margin of error reported alongside each one (the <code>±...%</code> figure) reflects this. For these two closely-matched models the margin of error is large enough that the two can trade places from one render to the next – consistent with the book’s own point in the next section that “the data do not clearly indicate whether there is or is not an interaction”.</p></div></div></section>
<section id="constructing-bayesian-type-ii-tests" class="level3 page-columns page-full" data-number="17.7.3">
<h3 data-number="17.7.3" class="anchored" data-anchor-id="constructing-bayesian-type-ii-tests"><span class="header-section-number">17.7.3</span> Constructing Bayesian Type II tests</h3>
<p>Okay, that’s all well and good, you might be thinking, but what do I report as the alternative to the <span class="math inline">\(p\)</span>-value? In the classical ANOVA table, you get a single <span class="math inline">\(p\)</span>-value for every predictor in the model, so you can talk about the significance of each effect. What’s the Bayesian analog of this?</p>
<p>It’s a good question, but the answer is tricky. Remember what I said in <a href="./16-anova2.html#sec-unbalancedanova">Factorial ANOVA 3: unbalanced designs</a> about ANOVA being complicated. Even in the classical version of ANOVA there are several different “things” that ANOVA might correspond to. Specifically, I discussed how you get different <span class="math inline">\(p\)</span>-values depending on whether you use Type I tests, Type II tests or Type III tests. To work out which Bayes factor is analogous to “the” <span class="math inline">\(p\)</span>-value in a classical ANOVA, you need to work out which version of ANOVA you want an analog for. For the purposes of this section, I’ll assume you want Type II tests, because those are the ones I think are most sensible in general. As I discussed back in <a href="./16-anova2.html#sec-unbalancedanova">Factorial ANOVA 3: unbalanced designs</a>, Type II tests for a two-way ANOVA are reasonably straightforward, but if you have forgotten that section it wouldn’t be a bad idea to read it again before continuing.</p>
<p>Assuming you’ve had a refresher on Type II tests, let’s have a look at how to pull them from the Bayes factor table. Suppose we want to test the main effect of <code>drug</code>. The null hypothesis for this test corresponds to a model that includes an effect of <code>therapy</code>, but no effect of <code>drug</code>. The alternative hypothesis is the model that includes both. In other words, what we want is the Bayes factor corresponding to this comparison:</p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td>Null model:</td>
<td><code>mood_gain ~ therapy</code></td>
</tr>
<tr class="even">
<td>Alternative model:</td>
<td><code>mood_gain ~ therapy + drug</code></td>
</tr>
</tbody>
</table>
<p>As it happens, we can read the answer to this straight off the table because it corresponds to a comparison between the <code>therapy</code> model and the <code>drug + therapy</code> model. The main effect of <code>therapy</code> can be calculated in much the same way: the null model is the one that contains only an effect of drug, and the alternative is the model that contains both, so the relevant comparison is between the <code>drug</code> model and the <code>drug + therapy</code> model. Finally, in order to test an interaction effect, the null model here is one that contains both main effects but no interaction, and the alternative model adds the interaction:</p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td>Null model:</td>
<td><code>mood_gain ~ drug + therapy</code></td>
</tr>
<tr class="even">
<td>Alternative model:</td>
<td><code>mood_gain ~ drug + therapy + drug:therapy</code></td>
</tr>
</tbody>
</table>
<p>You might be thinking that this is all pretty laborious, and I’ll concede that’s true. At some stage the <code>lsr</code> package might grow a function to automate this process and construct something like a “Bayesian Type II ANOVA table” from the output of the <code>anovaBF()</code> function, but as of this writing that hasn’t happened yet. In the meantime, here’s the trick that I use in practice to grab the right Bayes factors for a Type II ANOVA:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(models) <span class="sc">/</span> models</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                denominator
numerator            drug  therapy drug + therapy drug + therapy + drug:therapy
  drug + therapy 2.862611 962.1688              1                       1.02085</code></pre>
</div>
</div>
<p>The output isn’t quite so pretty as the last one, but the nice thing is that you can read off everything you need. The best model is <code>drug + therapy</code>, so all the other models are being compared to that. What’s the Bayes factor <em>for</em> the main effect of <code>drug</code>? The relevant null hypothesis is the one that contains only <code>therapy</code>, and that’s the Bayes factor to read off from the <code>therapy</code> column. The main effect of <code>therapy</code> is weaker, and the evidence here is read off from the <code>drug</code> column. Finally, the evidence for or against an interaction is read off from the <code>drug + therapy</code> column.</p>
<p>Reading the results off this table is sort of counterintuitive, because you have to read off the answers from the “wrong” part of the table. For instance, the evidence for an effect of <code>drug</code> can be read from the column labelled <code>therapy</code>, which is pretty damned weird. To be fair to the authors of the package, I don’t think they ever intended for the <code>anovaBF()</code> function to be used this way. My understanding<a href="#fn17" class="footnote-ref" id="fnref17" role="doc-noteref"><sup>17</sup></a> is that their view is simply that you should find the best model and report that model: there’s no inherent reason why a Bayesian ANOVA should try to follow the exact same design as an orthodox ANOVA.<a href="#fn18" class="footnote-ref" id="fnref18" role="doc-noteref"><sup>18</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn17"><p><sup>17</sup>&nbsp;Again, guys, sorry if I’ve misread you.</p></div><div id="fn18"><p><sup>18</sup>&nbsp;I don’t even disagree with them: it’s <em>not</em> at all obvious why a Bayesian ANOVA should reproduce (say) the same set of model comparisons that the Type II testing strategy uses. It’s precisely because of the fact that I haven’t really come to any strong conclusions that I haven’t added anything to the <code>lsr</code> package to make Bayesian Type II tests easier to produce.</p></div></div><p>In any case, if you know what you’re looking for, you can look at this table and then report the results of the Bayesian analysis in a way that is pretty closely analogous to how you’d report a regular Type II ANOVA. As I mentioned earlier, there’s still no convention on how to do that, but I usually go for something like this:</p>
<blockquote class="blockquote">
<p>A Bayesian Type II ANOVA found evidence for main effects of drug and therapy, but no clear evidence for or against an interaction.</p>
</blockquote>
</section>
</section>
<section id="summary" class="level2" data-number="17.8">
<h2 data-number="17.8" class="anchored" data-anchor-id="summary"><span class="header-section-number">17.8</span> Summary</h2>
<p>The first half of this chapter was focused primarily on the theoretical underpinnings of Bayesian statistics. I introduced the mathematics for how Bayesian inference works (<a href="#sec-basicbayes" class="quarto-xref"><span>Section 17.1</span></a>), and gave a very basic overview of how Bayesian hypothesis testing is typically done (<a href="#sec-bayesianhypothesistests" class="quarto-xref"><span>Section 17.2</span></a>). Finally, I devoted some space to talking about why I think Bayesian methods are worth using (<a href="#sec-whybayes" class="quarto-xref"><span>Section 17.3</span></a>).</p>
<p>The second half of the chapter was a lot more practical, and focused on tools provided by the <code>BayesFactor</code> package. Specifically, I talked about using the <code>contingencyTableBF()</code> function to do Bayesian analogs of chi-square tests (<a href="#sec-bayescontingency" class="quarto-xref"><span>Section 17.4</span></a>), the <code>ttestBF()</code> function to do Bayesian <span class="math inline">\(t\)</span>-tests (<a href="#sec-ttestbf" class="quarto-xref"><span>Section 17.5</span></a>), the <code>regressionBF()</code> function to do Bayesian regressions, and finally the <code>anovaBF()</code> function for Bayesian ANOVA (<a href="#sec-bayesregression" class="quarto-xref"><span>Section 17.6</span></a>, <a href="#sec-bayesanova" class="quarto-xref"><span>Section 17.7</span></a>).</p>
<p>If you’re interested in learning more about the Bayesian approach, there are many good books you could look into. John Kruschke’s book <em>Doing Bayesian Data Analysis</em> is a pretty good place to start <span class="citation" data-cites="Kruschke2011">(<a href="references.html#ref-Kruschke2011" role="doc-biblioref">Kruschke, 2011</a>)</span>, and is a nice mix of theory and practice. His approach is a little different to the “Bayes factor” approach that I’ve discussed here, so you won’t be covering the same ground. If you’re a cognitive psychologist, you might want to check out Michael Lee and E.J. Wagenmakers’ book <em>Bayesian Cognitive Modeling</em> <span class="citation" data-cites="Lee2014">(<a href="references.html#ref-Lee2014" role="doc-biblioref">Lee &amp; Wagenmakers, 2014</a>)</span>. I picked these two because I think they’re especially useful for people in my discipline, but there’s a lot of good books out there, so look around!</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-Fisher1925" class="csl-entry" role="listitem">
Fisher, R. A. (1925). <em>Statistical methods for research workers</em>. Oliver; Boyd.
</div>
<div id="ref-Gunel1974" class="csl-entry" role="listitem">
Gunel, E., &amp; Dickey, J. (1974). Bayes factors for independence in contingency tables. <em>Biometrika</em>, 545–557.
</div>
<div id="ref-Jeffreys1961" class="csl-entry" role="listitem">
Jeffreys, H. (1961). <em>The theory of probability</em> (3rd ed.). Oxford.
</div>
<div id="ref-Johnson2013" class="csl-entry" role="listitem">
Johnson, V. E. (2013). Revised standards for statistical evidence. <em>Proceedings of the National Academy of Sciences</em>, (48), 19313–19317.
</div>
<div id="ref-Kass1995" class="csl-entry" role="listitem">
Kass, R. E., &amp; Raftery, A. E. (1995). Bayes factors. <em>Journal of the American Statistical Association</em>, <em>90</em>, 773–795.
</div>
<div id="ref-Kruschke2011" class="csl-entry" role="listitem">
Kruschke, J. K. (2011). <em>Doing <span>B</span>ayesian data analysis: A tutorial with <span>R</span> and <span>BUGS</span></em>. Academic Press.
</div>
<div id="ref-Lee2014" class="csl-entry" role="listitem">
Lee, M. D., &amp; Wagenmakers, E.-J. (2014). <em>Bayesian cognitive modeling: A practical course</em>. Cambridge University Press.
</div>
<div id="ref-Morey2015" class="csl-entry" role="listitem">
Morey, R. D., &amp; Rouder, J. N. (2015). <em>BayesFactor: Computation of bayes factors for common designs</em>. <a href="http://CRAN.R-project.org/package=BayesFactor">http://CRAN.R-project.org/package=BayesFactor</a>
</div>
<div id="ref-Rouder2009" class="csl-entry" role="listitem">
Rouder, J. N., Speckman, P. L., Sun, D., Morey, R. D., &amp; Iverson, G. (2009). Bayesian t-tests for accepting and rejecting the null hypothesis. <em>Psychonomic Bulletin &amp; Review</em>, <em>16</em>, 225–237.
</div>
</div>
</section>


</main> <!-- /main -->
<!-- plausible -->
<script async="" defer="" data-domain="learningstatisticswithr.com" src="https://plausible.io/js/plausible.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/learningstatisticswithr\.com");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./16-anova2.html" class="pagination-link" aria-label="Factorial ANOVA">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./epilogue.html" class="pagination-link" aria-label="Epilogue">
        <span class="nav-page-text">Epilogue</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>